// Code generated by cmd/tools/codegen/fakes. DO NOT EDIT.

package fakes

import (
	"math"
	"time"

	types "github.com/primandproper/dinnerdonebetter/backend/internal/domain/notifications"
	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/notifications/converters"

	"github.com/primandproper/platform-go/v10/filtering"
	"github.com/primandproper/platform-go/v10/identifiers"
	"github.com/primandproper/platform-go/v10/pointer"

	fake "github.com/brianvoe/gofakeit/v7"
)

func init() {
	if err := fake.Seed(time.Now().UnixNano()); err != nil {
		panic(err)
	}
}

// exampleQuantity is how many elements a faked list has.
const exampleQuantity = 3

// BuildFakeID builds a fake ID.
func BuildFakeID() string {
	return identifiers.New()
}

// BuildFakeTime builds a fake time.
func BuildFakeTime() time.Time {
	return fake.Date().Add(0).Truncate(time.Second).UTC()
}

// buildFakeNumber builds a fake number comfortably above zero and below every integer
// width the domains use, so that it survives a conversion to any of them and no validator
// mistakes it for unset.
func buildFakeNumber() float64 {
	return math.Round(float64((fake.Number(101, math.MaxInt8-1) * 100) / 100))
}

// pickOne returns one of the options at random.
//
// Enumerated fields are faked as a random member rather than a fixed one, so that code which
// only handles the member somebody happened to pick first fails here rather than in production.
func pickOne[T any](options ...T) T {
	return options[fake.Number(0, len(options)-1)]
}

// buildUniqueString builds a fake string.
func buildUniqueString() string {
	return fake.LoremIpsumSentence(7)
}

// BuildFakeUserDeviceToken builds a faked UserDeviceToken.
func BuildFakeUserDeviceToken() *types.UserDeviceToken {
	return &types.UserDeviceToken{
		CreatedAt:     BuildFakeTime(),
		LastUpdatedAt: pointer.To(BuildFakeTime()),
		ArchivedAt:    nil,
		ID:            BuildFakeID(),
		DeviceToken:   "a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456",
		Platform:      pickOne(types.UserDeviceTokenPlatformIOS, types.UserDeviceTokenPlatformAndroid),
		BelongsToUser: BuildFakeID(),
	}
}

// BuildFakeUserDeviceTokensList builds a faked UserDeviceToken list.
func BuildFakeUserDeviceTokensList() *filtering.QueryFilteredResult[types.UserDeviceToken] {
	var examples []*types.UserDeviceToken
	for range exampleQuantity {
		examples = append(examples, BuildFakeUserDeviceToken())
	}

	return &filtering.QueryFilteredResult[types.UserDeviceToken]{
		Pagination: filtering.Pagination{
			Cursor:          BuildFakeID(),
			MaxResponseSize: 50,
			FilteredCount:   exampleQuantity / 2,
			TotalCount:      exampleQuantity,
		},
		Data: examples,
	}
}

// BuildFakeUserDeviceTokenDatabaseCreationInput builds a faked
// UserDeviceTokenDatabaseCreationInput.
func BuildFakeUserDeviceTokenDatabaseCreationInput() *types.UserDeviceTokenDatabaseCreationInput {
	token := BuildFakeUserDeviceToken()

	return &types.UserDeviceTokenDatabaseCreationInput{
		ID:            token.ID,
		DeviceToken:   token.DeviceToken,
		Platform:      token.Platform,
		BelongsToUser: token.BelongsToUser,
	}
}

// BuildFakeUserNotification builds a faked UserNotification.
func BuildFakeUserNotification() *types.UserNotification {
	return &types.UserNotification{
		CreatedAt:     BuildFakeTime(),
		LastUpdatedAt: pointer.To(BuildFakeTime()),
		ID:            BuildFakeID(),
		Content:       buildUniqueString(),
		Status:        pickOne(types.UserNotificationStatusTypeUnread, types.UserNotificationStatusTypeRead, types.UserNotificationStatusTypeDismissed),
		BelongsToUser: BuildFakeID(),
	}
}

// BuildFakeUserNotificationsList builds a faked UserNotification list.
func BuildFakeUserNotificationsList() *filtering.QueryFilteredResult[types.UserNotification] {
	var examples []*types.UserNotification
	for range exampleQuantity {
		examples = append(examples, BuildFakeUserNotification())
	}

	return &filtering.QueryFilteredResult[types.UserNotification]{
		Pagination: filtering.Pagination{
			Cursor:          BuildFakeID(),
			MaxResponseSize: 50,
			FilteredCount:   exampleQuantity / 2,
			TotalCount:      exampleQuantity,
		},
		Data: examples,
	}
}

// BuildFakeUserNotificationUpdateRequestInput builds a faked UserNotificationUpdateRequestInput.
func BuildFakeUserNotificationUpdateRequestInput() *types.UserNotificationUpdateRequestInput {
	return converters.ConvertUserNotificationToUserNotificationUpdateRequestInput(BuildFakeUserNotification())
}

// BuildFakeUserNotificationCreationRequestInput builds a faked
// UserNotificationCreationRequestInput.
func BuildFakeUserNotificationCreationRequestInput() *types.UserNotificationCreationRequestInput {
	return converters.ConvertUserNotificationToUserNotificationCreationRequestInput(BuildFakeUserNotification())
}
