package main

import (
	"fmt"
	"go/format"
	"reflect"
	"sort"
	"strings"

	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/entitydecl"
)

// entityPlan is one declared entity, resolved against its actual type.
type entityPlan struct {
	// typ is the entity's struct type.
	typ reflect.Type
	// builderName is the function that returns a pointer to a fake of it.
	builderName string
	// fake is the declaration's fake section.
	fake entitydecl.Fake
}

// renderDomain generates one fakes package, gofmt'd and ready to write.
//
// dir is the fakes package on disk. It is read, not written: the helpers a package gets depend on
// what its hand-written builders call, and the only way to know that is to look at them.
func renderDomain(d domain, dir string) ([]byte, error) {
	plans, err := plan(d.decl)
	if err != nil {
		return nil, err
	}

	defaults := &defaulter{
		builders:   buildersByType(plans),
		domainPath: domainImportPath(d.name),
	}

	body, err := renderBuilders(plans, defaults)
	if err != nil {
		return nil, err
	}

	used, err := identifiersInPackage(dir, body)
	if err != nil {
		return nil, err
	}

	preamble := renderHelpers(used)

	source := header + "\n\npackage fakes\n\n" +
		renderImports(d.name, preamble+body) +
		"\n" + preamble + body

	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("formatting generated fakes for %s: %w\n%s", d.name, err, source)
	}

	return formatted, nil
}

// header is the generated-file marker every tool in cmd/tools/codegen emits.
const header = "// Code generated by cmd/tools/codegen/fakes. DO NOT EDIT."

// plan resolves a declaration into the entities to generate, in declaration order.
func plan(d entitydecl.Domain) ([]entityPlan, error) {
	plans := make([]entityPlan, 0, len(d.Entities))

	for _, e := range d.Entities {
		if e.Type == nil {
			return nil, fmt.Errorf("entity %d has no Type", len(plans))
		}

		t := reflect.TypeOf(e.Type)
		if t.Kind() != reflect.Struct {
			return nil, fmt.Errorf("entity %s is not a struct; declare the zero value, not a pointer to it", t)
		}

		plans = append(plans, entityPlan{
			typ:         t,
			builderName: "BuildFake" + t.Name(),
			fake:        e.Fake,
		})
	}

	return plans, nil
}

// buildersByType indexes every entity's builder, bespoke ones included.
//
// A bespoke builder is still a builder: a field whose type is one gets `*BuildFakeThat()` as its
// default exactly as it would if the declaration generated it.
func buildersByType(plans []entityPlan) map[reflect.Type]string {
	byType := make(map[reflect.Type]string, len(plans))
	for _, p := range plans {
		byType[p.typ] = p.builderName
	}

	return byType
}

// renderBuilders emits every generated function for a domain.
func renderBuilders(plans []entityPlan, defaults *defaulter) (string, error) {
	var sb strings.Builder

	for _, p := range plans {
		if !p.fake.Bespoke {
			entity, err := renderEntity(&p, defaults)
			if err != nil {
				return "", err
			}

			sb.WriteString(entity)
		}

		if p.fake.List != nil {
			sb.WriteString(renderList(&p))
		}

		for _, input := range p.fake.Inputs {
			rendered, err := renderInput(&p, input)
			if err != nil {
				return "", err
			}

			sb.WriteString(rendered)
		}
	}

	return sb.String(), nil
}

// renderEntity emits one entity's builder.
func renderEntity(p *entityPlan, defaults *defaulter) (string, error) {
	overrides := map[string]entitydecl.Field{}
	for _, f := range p.fake.Fields {
		if _, found := p.typ.FieldByName(f.Name); !found {
			return "", fmt.Errorf("%s declares an override for %s.%s, which is not a field", p.builderName, p.typ.Name(), f.Name)
		}

		if _, duplicate := overrides[f.Name]; duplicate {
			return "", fmt.Errorf("%s declares %s twice", p.builderName, f.Name)
		}

		overrides[f.Name] = f
	}

	var sb strings.Builder

	sb.WriteString(doc(p.builderName, p.fake.Doc, fmt.Sprintf("builds a faked %s.", p.typ.Name())))
	fmt.Fprintf(&sb, "func %s() *%s.%s {\n", p.builderName, domainAlias, p.typ.Name())

	for _, local := range p.fake.Locals {
		sb.WriteString(comment(local.Why, "\t"))
		fmt.Fprintf(&sb, "\t%s\n", local.Code)
	}

	if len(p.fake.Locals) > 0 {
		sb.WriteString("\n")
	}

	fmt.Fprintf(&sb, "\treturn &%s.%s{\n", domainAlias, p.typ.Name())

	for field := range p.typ.Fields() {
		if !field.IsExported() {
			// An unexported field cannot be set from another package, and the fakes
			// package is another package. Struct tag sentinels like `_ struct{}` land
			// here too.
			continue
		}

		if override, found := overrides[field.Name]; found {
			sb.WriteString(comment(override.Why, "\t\t"))
			fmt.Fprintf(&sb, "\t\t%s: %s,\n", field.Name, override.Expr)

			continue
		}

		expression, ok := defaults.expr(&field)
		if !ok {
			return "", fmt.Errorf(
				"%s: no default for %s.%s of type %s; declare an override for it in the domain's entities.go",
				p.builderName, p.typ.Name(), field.Name, field.Type,
			)
		}

		fmt.Fprintf(&sb, "\t\t%s: %s,\n", field.Name, expression)
	}

	sb.WriteString("\t}\n}\n\n")

	return sb.String(), nil
}

// renderList emits a paginated-list builder.
//
// The pagination is the same in all forty-odd of these because it was copied forty-odd times, and
// nothing ever needed it to differ: what the callers check is Data.
func renderList(p *entityPlan) string {
	name := p.fake.List.Name
	if name == "" {
		name = p.builderName + "sList"
	}

	qualified := domainAlias + "." + p.typ.Name()

	var sb strings.Builder

	sb.WriteString(doc(name, p.fake.List.Doc, fmt.Sprintf("builds a faked %s list.", p.typ.Name())))
	fmt.Fprintf(&sb, "func %s() *filtering.QueryFilteredResult[%s] {\n", name, qualified)
	fmt.Fprintf(&sb, "\tvar examples []*%s\n", qualified)
	sb.WriteString("\tfor range exampleQuantity {\n")
	fmt.Fprintf(&sb, "\t\texamples = append(examples, %s())\n", p.builderName)
	sb.WriteString("\t}\n\n")
	fmt.Fprintf(&sb, "\treturn &filtering.QueryFilteredResult[%s]{\n", qualified)
	sb.WriteString("\t\tPagination: filtering.Pagination{\n")
	sb.WriteString("\t\t\tCursor:          BuildFakeID(),\n")
	sb.WriteString("\t\t\tMaxResponseSize: 50,\n")
	sb.WriteString("\t\t\tFilteredCount:   exampleQuantity / 2,\n")
	sb.WriteString("\t\t\tTotalCount:      exampleQuantity,\n")
	sb.WriteString("\t\t},\n")
	sb.WriteString("\t\tData: examples,\n")
	sb.WriteString("\t}\n}\n\n")

	return sb.String()
}

// renderInput emits a builder that runs the entity's fake through a converter.
func renderInput(p *entityPlan, input entitydecl.Input) (string, error) {
	if input.Type == nil {
		return "", fmt.Errorf("%s declares an input with no Type", p.builderName)
	}

	t := reflect.TypeOf(input.Type)
	if t.Kind() != reflect.Struct {
		return "", fmt.Errorf("%s declares input %s, which is not a struct", p.builderName, t)
	}

	if input.Converter == "" {
		return "", fmt.Errorf("%s declares input %s with no Converter", p.builderName, t.Name())
	}

	name := input.Name
	if name == "" {
		name = "BuildFake" + t.Name()
	}

	var sb strings.Builder

	sb.WriteString(doc(name, input.Doc, fmt.Sprintf("builds a faked %s.", t.Name())))
	fmt.Fprintf(&sb, "func %s() *%s.%s {\n", name, domainAlias, t.Name())
	fmt.Fprintf(&sb, "\treturn converters.%s(%s())\n", input.Converter, p.builderName)
	sb.WriteString("}\n\n")

	return sb.String(), nil
}

// doc renders a function's doc comment.
func doc(name, declared, fallback string) string {
	sentence := declared
	if sentence == "" {
		sentence = fallback
	}

	return comment(name+" "+sentence, "")
}

// comment renders text as a wrapped Go comment at the given indent, or nothing when text is empty.
func comment(text, indent string) string {
	if strings.TrimSpace(text) == "" {
		return ""
	}

	var sb strings.Builder

	for _, line := range wrap(text, commentWidth-len(indent)) {
		fmt.Fprintf(&sb, "%s// %s\n", indent, line)
	}

	return sb.String()
}

// commentWidth is where a comment wraps, matching the rest of this tree.
const commentWidth = 96

// wrap breaks text into lines of at most width characters, preserving deliberate blank lines.
func wrap(text string, width int) []string {
	var lines []string

	for paragraph := range strings.SplitSeq(strings.TrimSpace(text), "\n\n") {
		if len(lines) > 0 {
			lines = append(lines, "")
		}

		line := ""
		for word := range strings.FieldsSeq(paragraph) {
			switch {
			case line == "":
				line = word
			case len(line)+1+len(word) <= width:
				line += " " + word
			default:
				lines = append(lines, line)
				line = word
			}
		}

		if line != "" {
			lines = append(lines, line)
		}
	}

	return lines
}

// renderImports emits the import block for a rendered body.
//
// The imports are derived from the body rather than declared, because the body is mostly
// expressions copied from a declaration and nobody writing one should have to also record that
// `fake.Bool()` needs gofakeit. A qualifier the table below does not know is an error rather than
// a silently missing import, so the failure lands here instead of in a compiler message about a
// file the reader did not write.
func renderImports(domainName, body string) string {
	known := knownImports(domainName)

	needed := map[string]string{}
	for identifier := range qualifiers(body) {
		if path, found := known[identifier]; found {
			needed[identifier] = path
		}
	}

	// gci's sections, from .golangci.yml: standard, this module, the rest of primandproper,
	// everything else. Emitting them in that order is what keeps `make format` from
	// rewriting this file and failing the drift check that follows it.
	groups := [][]string{{}, {}, {}, {}}

	for alias, path := range needed {
		line := fmt.Sprintf("%q", path)
		if alias != defaultAlias(path) {
			line = fmt.Sprintf("%s %q", alias, path)
		}

		groups[section(path)] = append(groups[section(path)], line)
	}

	var sb strings.Builder

	sb.WriteString("import (\n")

	first := true

	for _, group := range groups {
		if len(group) == 0 {
			continue
		}

		if !first {
			sb.WriteString("\n")
		}

		first = false

		sort.Strings(group)

		for _, line := range group {
			fmt.Fprintf(&sb, "\t%s\n", line)
		}
	}

	sb.WriteString(")\n")

	return sb.String()
}

// section is the gci section an import path belongs to.
func section(path string) int {
	switch {
	case strings.HasPrefix(path, backendPrefix):
		return 1
	case strings.HasPrefix(path, "github.com/primandproper"):
		return 2
	case strings.Contains(strings.SplitN(path, "/", 2)[0], "."):
		return 3
	default:
		return 0
	}
}

// backendPrefix is this module's import path.
const backendPrefix = "github.com/primandproper/dinnerdonebetter/backend"

// defaultAlias is the identifier an import binds without an explicit alias.
func defaultAlias(path string) string {
	segments := strings.Split(path, "/")
	last := segments[len(segments)-1]

	// A vN suffix is a module major version, not a package name.
	if len(segments) > 1 && strings.HasPrefix(last, "v") && strings.Trim(last[1:], "0123456789") == "" {
		last = segments[len(segments)-2]
	}

	return last
}
