// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/comments"

	"github.com/primandproper/platform-go/v13/filtering"
)

// Ensure, that RepositoryMock does implement comments.Repository.
// If this is not the case, regenerate this file with moq.
var _ comments.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of comments.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked comments.Repository
//		mockedRepository := &RepositoryMock{
//			ArchiveCommentFunc: func(ctx context.Context, id string) error {
//				panic("mock out the ArchiveComment method")
//			},
//			CreateCommentFunc: func(ctx context.Context, input *comments.CommentDatabaseCreationInput) (*comments.Comment, error) {
//				panic("mock out the CreateComment method")
//			},
//			GetCommentFunc: func(ctx context.Context, id string) (*comments.Comment, error) {
//				panic("mock out the GetComment method")
//			},
//			GetCommentsForReferenceFunc: func(ctx context.Context, targetType string, referencedID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
//				panic("mock out the GetCommentsForReference method")
//			},
//			GetCommentsForUserFunc: func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
//				panic("mock out the GetCommentsForUser method")
//			},
//			UpdateCommentFunc: func(ctx context.Context, id string, belongsToUser string, content string) error {
//				panic("mock out the UpdateComment method")
//			},
//		}
//
//		// use mockedRepository in code that requires comments.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// ArchiveCommentFunc mocks the ArchiveComment method.
	ArchiveCommentFunc func(ctx context.Context, id string) error

	// CreateCommentFunc mocks the CreateComment method.
	CreateCommentFunc func(ctx context.Context, input *comments.CommentDatabaseCreationInput) (*comments.Comment, error)

	// GetCommentFunc mocks the GetComment method.
	GetCommentFunc func(ctx context.Context, id string) (*comments.Comment, error)

	// GetCommentsForReferenceFunc mocks the GetCommentsForReference method.
	GetCommentsForReferenceFunc func(ctx context.Context, targetType string, referencedID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error)

	// GetCommentsForUserFunc mocks the GetCommentsForUser method.
	GetCommentsForUserFunc func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error)

	// UpdateCommentFunc mocks the UpdateComment method.
	UpdateCommentFunc func(ctx context.Context, id string, belongsToUser string, content string) error

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveComment holds details about calls to the ArchiveComment method.
		ArchiveComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// CreateComment holds details about calls to the CreateComment method.
		CreateComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *comments.CommentDatabaseCreationInput
		}
		// GetComment holds details about calls to the GetComment method.
		GetComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetCommentsForReference holds details about calls to the GetCommentsForReference method.
		GetCommentsForReference []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TargetType is the targetType argument value.
			TargetType string
			// ReferencedID is the referencedID argument value.
			ReferencedID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// GetCommentsForUser holds details about calls to the GetCommentsForUser method.
		GetCommentsForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// UpdateComment holds details about calls to the UpdateComment method.
		UpdateComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// BelongsToUser is the belongsToUser argument value.
			BelongsToUser string
			// Content is the content argument value.
			Content string
		}
	}
	lockArchiveComment          sync.RWMutex
	lockCreateComment           sync.RWMutex
	lockGetComment              sync.RWMutex
	lockGetCommentsForReference sync.RWMutex
	lockGetCommentsForUser      sync.RWMutex
	lockUpdateComment           sync.RWMutex
}

// ArchiveComment calls ArchiveCommentFunc.
func (mock *RepositoryMock) ArchiveComment(ctx context.Context, id string) error {
	if mock.ArchiveCommentFunc == nil {
		panic("RepositoryMock.ArchiveCommentFunc: method is nil but Repository.ArchiveComment was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockArchiveComment.Lock()
	mock.calls.ArchiveComment = append(mock.calls.ArchiveComment, callInfo)
	mock.lockArchiveComment.Unlock()
	return mock.ArchiveCommentFunc(ctx, id)
}

// ArchiveCommentCalls gets all the calls that were made to ArchiveComment.
// Check the length with:
//
//	len(mockedRepository.ArchiveCommentCalls())
func (mock *RepositoryMock) ArchiveCommentCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockArchiveComment.RLock()
	calls = mock.calls.ArchiveComment
	mock.lockArchiveComment.RUnlock()
	return calls
}

// CreateComment calls CreateCommentFunc.
func (mock *RepositoryMock) CreateComment(ctx context.Context, input *comments.CommentDatabaseCreationInput) (*comments.Comment, error) {
	if mock.CreateCommentFunc == nil {
		panic("RepositoryMock.CreateCommentFunc: method is nil but Repository.CreateComment was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *comments.CommentDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateComment.Lock()
	mock.calls.CreateComment = append(mock.calls.CreateComment, callInfo)
	mock.lockCreateComment.Unlock()
	return mock.CreateCommentFunc(ctx, input)
}

// CreateCommentCalls gets all the calls that were made to CreateComment.
// Check the length with:
//
//	len(mockedRepository.CreateCommentCalls())
func (mock *RepositoryMock) CreateCommentCalls() []struct {
	Ctx   context.Context
	Input *comments.CommentDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *comments.CommentDatabaseCreationInput
	}
	mock.lockCreateComment.RLock()
	calls = mock.calls.CreateComment
	mock.lockCreateComment.RUnlock()
	return calls
}

// GetComment calls GetCommentFunc.
func (mock *RepositoryMock) GetComment(ctx context.Context, id string) (*comments.Comment, error) {
	if mock.GetCommentFunc == nil {
		panic("RepositoryMock.GetCommentFunc: method is nil but Repository.GetComment was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetComment.Lock()
	mock.calls.GetComment = append(mock.calls.GetComment, callInfo)
	mock.lockGetComment.Unlock()
	return mock.GetCommentFunc(ctx, id)
}

// GetCommentCalls gets all the calls that were made to GetComment.
// Check the length with:
//
//	len(mockedRepository.GetCommentCalls())
func (mock *RepositoryMock) GetCommentCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetComment.RLock()
	calls = mock.calls.GetComment
	mock.lockGetComment.RUnlock()
	return calls
}

// GetCommentsForReference calls GetCommentsForReferenceFunc.
func (mock *RepositoryMock) GetCommentsForReference(ctx context.Context, targetType string, referencedID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
	if mock.GetCommentsForReferenceFunc == nil {
		panic("RepositoryMock.GetCommentsForReferenceFunc: method is nil but Repository.GetCommentsForReference was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TargetType   string
		ReferencedID string
		Filter       *filtering.QueryFilter
	}{
		Ctx:          ctx,
		TargetType:   targetType,
		ReferencedID: referencedID,
		Filter:       filter,
	}
	mock.lockGetCommentsForReference.Lock()
	mock.calls.GetCommentsForReference = append(mock.calls.GetCommentsForReference, callInfo)
	mock.lockGetCommentsForReference.Unlock()
	return mock.GetCommentsForReferenceFunc(ctx, targetType, referencedID, filter)
}

// GetCommentsForReferenceCalls gets all the calls that were made to GetCommentsForReference.
// Check the length with:
//
//	len(mockedRepository.GetCommentsForReferenceCalls())
func (mock *RepositoryMock) GetCommentsForReferenceCalls() []struct {
	Ctx          context.Context
	TargetType   string
	ReferencedID string
	Filter       *filtering.QueryFilter
} {
	var calls []struct {
		Ctx          context.Context
		TargetType   string
		ReferencedID string
		Filter       *filtering.QueryFilter
	}
	mock.lockGetCommentsForReference.RLock()
	calls = mock.calls.GetCommentsForReference
	mock.lockGetCommentsForReference.RUnlock()
	return calls
}

// GetCommentsForUser calls GetCommentsForUserFunc.
func (mock *RepositoryMock) GetCommentsForUser(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
	if mock.GetCommentsForUserFunc == nil {
		panic("RepositoryMock.GetCommentsForUserFunc: method is nil but Repository.GetCommentsForUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		UserID: userID,
		Filter: filter,
	}
	mock.lockGetCommentsForUser.Lock()
	mock.calls.GetCommentsForUser = append(mock.calls.GetCommentsForUser, callInfo)
	mock.lockGetCommentsForUser.Unlock()
	return mock.GetCommentsForUserFunc(ctx, userID, filter)
}

// GetCommentsForUserCalls gets all the calls that were made to GetCommentsForUser.
// Check the length with:
//
//	len(mockedRepository.GetCommentsForUserCalls())
func (mock *RepositoryMock) GetCommentsForUserCalls() []struct {
	Ctx    context.Context
	UserID string
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}
	mock.lockGetCommentsForUser.RLock()
	calls = mock.calls.GetCommentsForUser
	mock.lockGetCommentsForUser.RUnlock()
	return calls
}

// UpdateComment calls UpdateCommentFunc.
func (mock *RepositoryMock) UpdateComment(ctx context.Context, id string, belongsToUser string, content string) error {
	if mock.UpdateCommentFunc == nil {
		panic("RepositoryMock.UpdateCommentFunc: method is nil but Repository.UpdateComment was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ID            string
		BelongsToUser string
		Content       string
	}{
		Ctx:           ctx,
		ID:            id,
		BelongsToUser: belongsToUser,
		Content:       content,
	}
	mock.lockUpdateComment.Lock()
	mock.calls.UpdateComment = append(mock.calls.UpdateComment, callInfo)
	mock.lockUpdateComment.Unlock()
	return mock.UpdateCommentFunc(ctx, id, belongsToUser, content)
}

// UpdateCommentCalls gets all the calls that were made to UpdateComment.
// Check the length with:
//
//	len(mockedRepository.UpdateCommentCalls())
func (mock *RepositoryMock) UpdateCommentCalls() []struct {
	Ctx           context.Context
	ID            string
	BelongsToUser string
	Content       string
} {
	var calls []struct {
		Ctx           context.Context
		ID            string
		BelongsToUser string
		Content       string
	}
	mock.lockUpdateComment.RLock()
	calls = mock.calls.UpdateComment
	mock.lockUpdateComment.RUnlock()
	return calls
}
