// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/oauth"
	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/oauth/manager"

	"github.com/primandproper/platform-go/v11/filtering"
)

// Ensure, that OAuth2ManagerMock does implement manager.OAuth2Manager.
// If this is not the case, regenerate this file with moq.
var _ manager.OAuth2Manager = &OAuth2ManagerMock{}

// OAuth2ManagerMock is a mock implementation of manager.OAuth2Manager.
//
//	func TestSomethingThatUsesOAuth2Manager(t *testing.T) {
//
//		// make and configure a mocked manager.OAuth2Manager
//		mockedOAuth2Manager := &OAuth2ManagerMock{
//			ArchiveOAuth2ClientFunc: func(ctx context.Context, oauth2ClientID string) error {
//				panic("mock out the ArchiveOAuth2Client method")
//			},
//			CreateOAuth2ClientFunc: func(ctx context.Context, input *oauth.OAuth2ClientCreationRequestInput) (*oauth.OAuth2Client, error) {
//				panic("mock out the CreateOAuth2Client method")
//			},
//			GetOAuth2ClientFunc: func(ctx context.Context, oauth2ClientID string) (*oauth.OAuth2Client, error) {
//				panic("mock out the GetOAuth2Client method")
//			},
//			GetOAuth2ClientsFunc: func(ctx context.Context, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[oauth.OAuth2Client], error) {
//				panic("mock out the GetOAuth2Clients method")
//			},
//		}
//
//		// use mockedOAuth2Manager in code that requires manager.OAuth2Manager
//		// and then make assertions.
//
//	}
type OAuth2ManagerMock struct {
	// ArchiveOAuth2ClientFunc mocks the ArchiveOAuth2Client method.
	ArchiveOAuth2ClientFunc func(ctx context.Context, oauth2ClientID string) error

	// CreateOAuth2ClientFunc mocks the CreateOAuth2Client method.
	CreateOAuth2ClientFunc func(ctx context.Context, input *oauth.OAuth2ClientCreationRequestInput) (*oauth.OAuth2Client, error)

	// GetOAuth2ClientFunc mocks the GetOAuth2Client method.
	GetOAuth2ClientFunc func(ctx context.Context, oauth2ClientID string) (*oauth.OAuth2Client, error)

	// GetOAuth2ClientsFunc mocks the GetOAuth2Clients method.
	GetOAuth2ClientsFunc func(ctx context.Context, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[oauth.OAuth2Client], error)

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveOAuth2Client holds details about calls to the ArchiveOAuth2Client method.
		ArchiveOAuth2Client []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Oauth2ClientID is the oauth2ClientID argument value.
			Oauth2ClientID string
		}
		// CreateOAuth2Client holds details about calls to the CreateOAuth2Client method.
		CreateOAuth2Client []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *oauth.OAuth2ClientCreationRequestInput
		}
		// GetOAuth2Client holds details about calls to the GetOAuth2Client method.
		GetOAuth2Client []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Oauth2ClientID is the oauth2ClientID argument value.
			Oauth2ClientID string
		}
		// GetOAuth2Clients holds details about calls to the GetOAuth2Clients method.
		GetOAuth2Clients []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
	}
	lockArchiveOAuth2Client sync.RWMutex
	lockCreateOAuth2Client  sync.RWMutex
	lockGetOAuth2Client     sync.RWMutex
	lockGetOAuth2Clients    sync.RWMutex
}

// ArchiveOAuth2Client calls ArchiveOAuth2ClientFunc.
func (mock *OAuth2ManagerMock) ArchiveOAuth2Client(ctx context.Context, oauth2ClientID string) error {
	if mock.ArchiveOAuth2ClientFunc == nil {
		panic("OAuth2ManagerMock.ArchiveOAuth2ClientFunc: method is nil but OAuth2Manager.ArchiveOAuth2Client was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Oauth2ClientID string
	}{
		Ctx:            ctx,
		Oauth2ClientID: oauth2ClientID,
	}
	mock.lockArchiveOAuth2Client.Lock()
	mock.calls.ArchiveOAuth2Client = append(mock.calls.ArchiveOAuth2Client, callInfo)
	mock.lockArchiveOAuth2Client.Unlock()
	return mock.ArchiveOAuth2ClientFunc(ctx, oauth2ClientID)
}

// ArchiveOAuth2ClientCalls gets all the calls that were made to ArchiveOAuth2Client.
// Check the length with:
//
//	len(mockedOAuth2Manager.ArchiveOAuth2ClientCalls())
func (mock *OAuth2ManagerMock) ArchiveOAuth2ClientCalls() []struct {
	Ctx            context.Context
	Oauth2ClientID string
} {
	var calls []struct {
		Ctx            context.Context
		Oauth2ClientID string
	}
	mock.lockArchiveOAuth2Client.RLock()
	calls = mock.calls.ArchiveOAuth2Client
	mock.lockArchiveOAuth2Client.RUnlock()
	return calls
}

// CreateOAuth2Client calls CreateOAuth2ClientFunc.
func (mock *OAuth2ManagerMock) CreateOAuth2Client(ctx context.Context, input *oauth.OAuth2ClientCreationRequestInput) (*oauth.OAuth2Client, error) {
	if mock.CreateOAuth2ClientFunc == nil {
		panic("OAuth2ManagerMock.CreateOAuth2ClientFunc: method is nil but OAuth2Manager.CreateOAuth2Client was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *oauth.OAuth2ClientCreationRequestInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateOAuth2Client.Lock()
	mock.calls.CreateOAuth2Client = append(mock.calls.CreateOAuth2Client, callInfo)
	mock.lockCreateOAuth2Client.Unlock()
	return mock.CreateOAuth2ClientFunc(ctx, input)
}

// CreateOAuth2ClientCalls gets all the calls that were made to CreateOAuth2Client.
// Check the length with:
//
//	len(mockedOAuth2Manager.CreateOAuth2ClientCalls())
func (mock *OAuth2ManagerMock) CreateOAuth2ClientCalls() []struct {
	Ctx   context.Context
	Input *oauth.OAuth2ClientCreationRequestInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *oauth.OAuth2ClientCreationRequestInput
	}
	mock.lockCreateOAuth2Client.RLock()
	calls = mock.calls.CreateOAuth2Client
	mock.lockCreateOAuth2Client.RUnlock()
	return calls
}

// GetOAuth2Client calls GetOAuth2ClientFunc.
func (mock *OAuth2ManagerMock) GetOAuth2Client(ctx context.Context, oauth2ClientID string) (*oauth.OAuth2Client, error) {
	if mock.GetOAuth2ClientFunc == nil {
		panic("OAuth2ManagerMock.GetOAuth2ClientFunc: method is nil but OAuth2Manager.GetOAuth2Client was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Oauth2ClientID string
	}{
		Ctx:            ctx,
		Oauth2ClientID: oauth2ClientID,
	}
	mock.lockGetOAuth2Client.Lock()
	mock.calls.GetOAuth2Client = append(mock.calls.GetOAuth2Client, callInfo)
	mock.lockGetOAuth2Client.Unlock()
	return mock.GetOAuth2ClientFunc(ctx, oauth2ClientID)
}

// GetOAuth2ClientCalls gets all the calls that were made to GetOAuth2Client.
// Check the length with:
//
//	len(mockedOAuth2Manager.GetOAuth2ClientCalls())
func (mock *OAuth2ManagerMock) GetOAuth2ClientCalls() []struct {
	Ctx            context.Context
	Oauth2ClientID string
} {
	var calls []struct {
		Ctx            context.Context
		Oauth2ClientID string
	}
	mock.lockGetOAuth2Client.RLock()
	calls = mock.calls.GetOAuth2Client
	mock.lockGetOAuth2Client.RUnlock()
	return calls
}

// GetOAuth2Clients calls GetOAuth2ClientsFunc.
func (mock *OAuth2ManagerMock) GetOAuth2Clients(ctx context.Context, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[oauth.OAuth2Client], error) {
	if mock.GetOAuth2ClientsFunc == nil {
		panic("OAuth2ManagerMock.GetOAuth2ClientsFunc: method is nil but OAuth2Manager.GetOAuth2Clients was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetOAuth2Clients.Lock()
	mock.calls.GetOAuth2Clients = append(mock.calls.GetOAuth2Clients, callInfo)
	mock.lockGetOAuth2Clients.Unlock()
	return mock.GetOAuth2ClientsFunc(ctx, filter)
}

// GetOAuth2ClientsCalls gets all the calls that were made to GetOAuth2Clients.
// Check the length with:
//
//	len(mockedOAuth2Manager.GetOAuth2ClientsCalls())
func (mock *OAuth2ManagerMock) GetOAuth2ClientsCalls() []struct {
	Ctx    context.Context
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter *filtering.QueryFilter
	}
	mock.lockGetOAuth2Clients.RLock()
	calls = mock.calls.GetOAuth2Clients
	mock.lockGetOAuth2Clients.RUnlock()
	return calls
}
