// Code generated by cmd/tools/codegen/converters. DO NOT EDIT.

package converters

import (
	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/settings"

	"github.com/primandproper/platform-go/v11/identifiers"
)

// ConvertServiceSettingConfigurationToServiceSettingConfigurationUpdateRequestInput builds a ServiceSettingConfigurationUpdateRequestInput from a ServiceSettingConfiguration.
func ConvertServiceSettingConfigurationToServiceSettingConfigurationUpdateRequestInput(input *settings.ServiceSettingConfiguration) *settings.ServiceSettingConfigurationUpdateRequestInput {
	return &settings.ServiceSettingConfigurationUpdateRequestInput{
		Value:            &input.Value,
		Notes:            &input.Notes,
		ServiceSettingID: &input.ServiceSetting.ID,
	}
}

// ConvertServiceSettingConfigurationToServiceSettingConfigurationCreationRequestInput builds a ServiceSettingConfigurationCreationRequestInput from a ServiceSettingConfiguration.
func ConvertServiceSettingConfigurationToServiceSettingConfigurationCreationRequestInput(input *settings.ServiceSettingConfiguration) *settings.ServiceSettingConfigurationCreationRequestInput {
	return &settings.ServiceSettingConfigurationCreationRequestInput{
		Value:            input.Value,
		Notes:            input.Notes,
		ServiceSettingID: input.ServiceSetting.ID,
	}
}

// ConvertServiceSettingConfigurationToServiceSettingConfigurationDatabaseCreationInput builds a ServiceSettingConfigurationDatabaseCreationInput from a ServiceSettingConfiguration.
func ConvertServiceSettingConfigurationToServiceSettingConfigurationDatabaseCreationInput(input *settings.ServiceSettingConfiguration) *settings.ServiceSettingConfigurationDatabaseCreationInput {
	return &settings.ServiceSettingConfigurationDatabaseCreationInput{
		ID:               input.ID,
		Value:            input.Value,
		Notes:            input.Notes,
		ServiceSettingID: input.ServiceSetting.ID,
		BelongsToUser:    input.BelongsToUser,
		BelongsToAccount: input.BelongsToAccount,
	}
}

// ConvertServiceSettingCreationRequestInputToServiceSettingDatabaseCreationInput builds a ServiceSettingDatabaseCreationInput from a ServiceSettingCreationRequestInput.
func ConvertServiceSettingCreationRequestInputToServiceSettingDatabaseCreationInput(input *settings.ServiceSettingCreationRequestInput) *settings.ServiceSettingDatabaseCreationInput {
	return &settings.ServiceSettingDatabaseCreationInput{
		DefaultValue: input.DefaultValue,
		ID:           identifiers.New(),
		Name:         input.Name,
		Type:         input.Type,
		Description:  input.Description,
		Enumeration:  input.Enumeration,
		AdminsOnly:   input.AdminsOnly,
	}
}

// ConvertServiceSettingToServiceSettingCreationRequestInput builds a ServiceSettingCreationRequestInput from a ServiceSetting.
func ConvertServiceSettingToServiceSettingCreationRequestInput(input *settings.ServiceSetting) *settings.ServiceSettingCreationRequestInput {
	return &settings.ServiceSettingCreationRequestInput{
		DefaultValue: input.DefaultValue,
		Name:         input.Name,
		Type:         input.Type,
		Description:  input.Description,
		Enumeration:  input.Enumeration,
		AdminsOnly:   input.AdminsOnly,
	}
}

// ConvertServiceSettingToServiceSettingDatabaseCreationInput builds a ServiceSettingDatabaseCreationInput from a ServiceSetting.
func ConvertServiceSettingToServiceSettingDatabaseCreationInput(input *settings.ServiceSetting) *settings.ServiceSettingDatabaseCreationInput {
	return &settings.ServiceSettingDatabaseCreationInput{
		DefaultValue: input.DefaultValue,
		ID:           input.ID,
		Name:         input.Name,
		Type:         input.Type,
		Description:  input.Description,
		Enumeration:  input.Enumeration,
		AdminsOnly:   input.AdminsOnly,
	}
}
