package oauth

import (
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
)

// HashClientSecret returns the canonical stored form of an OAuth2 client secret.
// Client secrets are high-entropy random strings generated by the server, so an
// unsalted SHA-256 digest is sufficient (the same treatment API keys get); a
// work-factor hash like bcrypt adds nothing against offline attack of a random
// 128-bit value and would slow every token request.
func HashClientSecret(secret string) string {
	digest := sha256.Sum256([]byte(secret))
	return hex.EncodeToString(digest[:])
}

// ClientSecretMatches reports whether the presented plaintext secret matches the
// stored digest, in constant time.
func ClientSecretMatches(storedDigest, presented string) bool {
	presentedDigest := HashClientSecret(presented)
	return subtle.ConstantTimeCompare([]byte(storedDigest), []byte(presentedDigest)) == 1
}
