// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/webhooks"

	"github.com/primandproper/platform-go/v9/filtering"
)

// Ensure, that RepositoryMock does implement webhooks.Repository.
// If this is not the case, regenerate this file with moq.
var _ webhooks.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of webhooks.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked webhooks.Repository
//		mockedRepository := &RepositoryMock{
//			AddWebhookTriggerConfigFunc: func(ctx context.Context, accountID string, input *webhooks.WebhookTriggerConfigDatabaseCreationInput) (*webhooks.WebhookTriggerConfig, error) {
//				panic("mock out the AddWebhookTriggerConfig method")
//			},
//			ArchiveWebhookFunc: func(ctx context.Context, webhookID string, accountID string) error {
//				panic("mock out the ArchiveWebhook method")
//			},
//			ArchiveWebhookTriggerConfigFunc: func(ctx context.Context, webhookID string, accountID string, configID string) error {
//				panic("mock out the ArchiveWebhookTriggerConfig method")
//			},
//			CreateWebhookFunc: func(ctx context.Context, input *webhooks.WebhookDatabaseCreationInput) (*webhooks.WebhookCreationResponse, error) {
//				panic("mock out the CreateWebhook method")
//			},
//			GetWebhookFunc: func(ctx context.Context, webhookID string, accountID string) (*webhooks.Webhook, error) {
//				panic("mock out the GetWebhook method")
//			},
//			GetWebhooksFunc: func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Webhook], error) {
//				panic("mock out the GetWebhooks method")
//			},
//			RotateWebhookSecretFunc: func(ctx context.Context, webhookID string, accountID string) (string, error) {
//				panic("mock out the RotateWebhookSecret method")
//			},
//			WebhookExistsFunc: func(ctx context.Context, webhookID string, accountID string) (bool, error) {
//				panic("mock out the WebhookExists method")
//			},
//		}
//
//		// use mockedRepository in code that requires webhooks.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// AddWebhookTriggerConfigFunc mocks the AddWebhookTriggerConfig method.
	AddWebhookTriggerConfigFunc func(ctx context.Context, accountID string, input *webhooks.WebhookTriggerConfigDatabaseCreationInput) (*webhooks.WebhookTriggerConfig, error)

	// ArchiveWebhookFunc mocks the ArchiveWebhook method.
	ArchiveWebhookFunc func(ctx context.Context, webhookID string, accountID string) error

	// ArchiveWebhookTriggerConfigFunc mocks the ArchiveWebhookTriggerConfig method.
	ArchiveWebhookTriggerConfigFunc func(ctx context.Context, webhookID string, accountID string, configID string) error

	// CreateWebhookFunc mocks the CreateWebhook method.
	CreateWebhookFunc func(ctx context.Context, input *webhooks.WebhookDatabaseCreationInput) (*webhooks.WebhookCreationResponse, error)

	// GetWebhookFunc mocks the GetWebhook method.
	GetWebhookFunc func(ctx context.Context, webhookID string, accountID string) (*webhooks.Webhook, error)

	// GetWebhooksFunc mocks the GetWebhooks method.
	GetWebhooksFunc func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Webhook], error)

	// RotateWebhookSecretFunc mocks the RotateWebhookSecret method.
	RotateWebhookSecretFunc func(ctx context.Context, webhookID string, accountID string) (string, error)

	// WebhookExistsFunc mocks the WebhookExists method.
	WebhookExistsFunc func(ctx context.Context, webhookID string, accountID string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddWebhookTriggerConfig holds details about calls to the AddWebhookTriggerConfig method.
		AddWebhookTriggerConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID string
			// Input is the input argument value.
			Input *webhooks.WebhookTriggerConfigDatabaseCreationInput
		}
		// ArchiveWebhook holds details about calls to the ArchiveWebhook method.
		ArchiveWebhook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
			// AccountID is the accountID argument value.
			AccountID string
		}
		// ArchiveWebhookTriggerConfig holds details about calls to the ArchiveWebhookTriggerConfig method.
		ArchiveWebhookTriggerConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
			// AccountID is the accountID argument value.
			AccountID string
			// ConfigID is the configID argument value.
			ConfigID string
		}
		// CreateWebhook holds details about calls to the CreateWebhook method.
		CreateWebhook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *webhooks.WebhookDatabaseCreationInput
		}
		// GetWebhook holds details about calls to the GetWebhook method.
		GetWebhook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
			// AccountID is the accountID argument value.
			AccountID string
		}
		// GetWebhooks holds details about calls to the GetWebhooks method.
		GetWebhooks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// RotateWebhookSecret holds details about calls to the RotateWebhookSecret method.
		RotateWebhookSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
			// AccountID is the accountID argument value.
			AccountID string
		}
		// WebhookExists holds details about calls to the WebhookExists method.
		WebhookExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
			// AccountID is the accountID argument value.
			AccountID string
		}
	}
	lockAddWebhookTriggerConfig     sync.RWMutex
	lockArchiveWebhook              sync.RWMutex
	lockArchiveWebhookTriggerConfig sync.RWMutex
	lockCreateWebhook               sync.RWMutex
	lockGetWebhook                  sync.RWMutex
	lockGetWebhooks                 sync.RWMutex
	lockRotateWebhookSecret         sync.RWMutex
	lockWebhookExists               sync.RWMutex
}

// AddWebhookTriggerConfig calls AddWebhookTriggerConfigFunc.
func (mock *RepositoryMock) AddWebhookTriggerConfig(ctx context.Context, accountID string, input *webhooks.WebhookTriggerConfigDatabaseCreationInput) (*webhooks.WebhookTriggerConfig, error) {
	if mock.AddWebhookTriggerConfigFunc == nil {
		panic("RepositoryMock.AddWebhookTriggerConfigFunc: method is nil but Repository.AddWebhookTriggerConfig was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID string
		Input     *webhooks.WebhookTriggerConfigDatabaseCreationInput
	}{
		Ctx:       ctx,
		AccountID: accountID,
		Input:     input,
	}
	mock.lockAddWebhookTriggerConfig.Lock()
	mock.calls.AddWebhookTriggerConfig = append(mock.calls.AddWebhookTriggerConfig, callInfo)
	mock.lockAddWebhookTriggerConfig.Unlock()
	return mock.AddWebhookTriggerConfigFunc(ctx, accountID, input)
}

// AddWebhookTriggerConfigCalls gets all the calls that were made to AddWebhookTriggerConfig.
// Check the length with:
//
//	len(mockedRepository.AddWebhookTriggerConfigCalls())
func (mock *RepositoryMock) AddWebhookTriggerConfigCalls() []struct {
	Ctx       context.Context
	AccountID string
	Input     *webhooks.WebhookTriggerConfigDatabaseCreationInput
} {
	var calls []struct {
		Ctx       context.Context
		AccountID string
		Input     *webhooks.WebhookTriggerConfigDatabaseCreationInput
	}
	mock.lockAddWebhookTriggerConfig.RLock()
	calls = mock.calls.AddWebhookTriggerConfig
	mock.lockAddWebhookTriggerConfig.RUnlock()
	return calls
}

// ArchiveWebhook calls ArchiveWebhookFunc.
func (mock *RepositoryMock) ArchiveWebhook(ctx context.Context, webhookID string, accountID string) error {
	if mock.ArchiveWebhookFunc == nil {
		panic("RepositoryMock.ArchiveWebhookFunc: method is nil but Repository.ArchiveWebhook was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
		AccountID: accountID,
	}
	mock.lockArchiveWebhook.Lock()
	mock.calls.ArchiveWebhook = append(mock.calls.ArchiveWebhook, callInfo)
	mock.lockArchiveWebhook.Unlock()
	return mock.ArchiveWebhookFunc(ctx, webhookID, accountID)
}

// ArchiveWebhookCalls gets all the calls that were made to ArchiveWebhook.
// Check the length with:
//
//	len(mockedRepository.ArchiveWebhookCalls())
func (mock *RepositoryMock) ArchiveWebhookCalls() []struct {
	Ctx       context.Context
	WebhookID string
	AccountID string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}
	mock.lockArchiveWebhook.RLock()
	calls = mock.calls.ArchiveWebhook
	mock.lockArchiveWebhook.RUnlock()
	return calls
}

// ArchiveWebhookTriggerConfig calls ArchiveWebhookTriggerConfigFunc.
func (mock *RepositoryMock) ArchiveWebhookTriggerConfig(ctx context.Context, webhookID string, accountID string, configID string) error {
	if mock.ArchiveWebhookTriggerConfigFunc == nil {
		panic("RepositoryMock.ArchiveWebhookTriggerConfigFunc: method is nil but Repository.ArchiveWebhookTriggerConfig was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
		ConfigID  string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
		AccountID: accountID,
		ConfigID:  configID,
	}
	mock.lockArchiveWebhookTriggerConfig.Lock()
	mock.calls.ArchiveWebhookTriggerConfig = append(mock.calls.ArchiveWebhookTriggerConfig, callInfo)
	mock.lockArchiveWebhookTriggerConfig.Unlock()
	return mock.ArchiveWebhookTriggerConfigFunc(ctx, webhookID, accountID, configID)
}

// ArchiveWebhookTriggerConfigCalls gets all the calls that were made to ArchiveWebhookTriggerConfig.
// Check the length with:
//
//	len(mockedRepository.ArchiveWebhookTriggerConfigCalls())
func (mock *RepositoryMock) ArchiveWebhookTriggerConfigCalls() []struct {
	Ctx       context.Context
	WebhookID string
	AccountID string
	ConfigID  string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
		ConfigID  string
	}
	mock.lockArchiveWebhookTriggerConfig.RLock()
	calls = mock.calls.ArchiveWebhookTriggerConfig
	mock.lockArchiveWebhookTriggerConfig.RUnlock()
	return calls
}

// CreateWebhook calls CreateWebhookFunc.
func (mock *RepositoryMock) CreateWebhook(ctx context.Context, input *webhooks.WebhookDatabaseCreationInput) (*webhooks.WebhookCreationResponse, error) {
	if mock.CreateWebhookFunc == nil {
		panic("RepositoryMock.CreateWebhookFunc: method is nil but Repository.CreateWebhook was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *webhooks.WebhookDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateWebhook.Lock()
	mock.calls.CreateWebhook = append(mock.calls.CreateWebhook, callInfo)
	mock.lockCreateWebhook.Unlock()
	return mock.CreateWebhookFunc(ctx, input)
}

// CreateWebhookCalls gets all the calls that were made to CreateWebhook.
// Check the length with:
//
//	len(mockedRepository.CreateWebhookCalls())
func (mock *RepositoryMock) CreateWebhookCalls() []struct {
	Ctx   context.Context
	Input *webhooks.WebhookDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *webhooks.WebhookDatabaseCreationInput
	}
	mock.lockCreateWebhook.RLock()
	calls = mock.calls.CreateWebhook
	mock.lockCreateWebhook.RUnlock()
	return calls
}

// GetWebhook calls GetWebhookFunc.
func (mock *RepositoryMock) GetWebhook(ctx context.Context, webhookID string, accountID string) (*webhooks.Webhook, error) {
	if mock.GetWebhookFunc == nil {
		panic("RepositoryMock.GetWebhookFunc: method is nil but Repository.GetWebhook was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
		AccountID: accountID,
	}
	mock.lockGetWebhook.Lock()
	mock.calls.GetWebhook = append(mock.calls.GetWebhook, callInfo)
	mock.lockGetWebhook.Unlock()
	return mock.GetWebhookFunc(ctx, webhookID, accountID)
}

// GetWebhookCalls gets all the calls that were made to GetWebhook.
// Check the length with:
//
//	len(mockedRepository.GetWebhookCalls())
func (mock *RepositoryMock) GetWebhookCalls() []struct {
	Ctx       context.Context
	WebhookID string
	AccountID string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}
	mock.lockGetWebhook.RLock()
	calls = mock.calls.GetWebhook
	mock.lockGetWebhook.RUnlock()
	return calls
}

// GetWebhooks calls GetWebhooksFunc.
func (mock *RepositoryMock) GetWebhooks(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Webhook], error) {
	if mock.GetWebhooksFunc == nil {
		panic("RepositoryMock.GetWebhooksFunc: method is nil but Repository.GetWebhooks was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}{
		Ctx:       ctx,
		AccountID: accountID,
		Filter:    filter,
	}
	mock.lockGetWebhooks.Lock()
	mock.calls.GetWebhooks = append(mock.calls.GetWebhooks, callInfo)
	mock.lockGetWebhooks.Unlock()
	return mock.GetWebhooksFunc(ctx, accountID, filter)
}

// GetWebhooksCalls gets all the calls that were made to GetWebhooks.
// Check the length with:
//
//	len(mockedRepository.GetWebhooksCalls())
func (mock *RepositoryMock) GetWebhooksCalls() []struct {
	Ctx       context.Context
	AccountID string
	Filter    *filtering.QueryFilter
} {
	var calls []struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}
	mock.lockGetWebhooks.RLock()
	calls = mock.calls.GetWebhooks
	mock.lockGetWebhooks.RUnlock()
	return calls
}

// RotateWebhookSecret calls RotateWebhookSecretFunc.
func (mock *RepositoryMock) RotateWebhookSecret(ctx context.Context, webhookID string, accountID string) (string, error) {
	if mock.RotateWebhookSecretFunc == nil {
		panic("RepositoryMock.RotateWebhookSecretFunc: method is nil but Repository.RotateWebhookSecret was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
		AccountID: accountID,
	}
	mock.lockRotateWebhookSecret.Lock()
	mock.calls.RotateWebhookSecret = append(mock.calls.RotateWebhookSecret, callInfo)
	mock.lockRotateWebhookSecret.Unlock()
	return mock.RotateWebhookSecretFunc(ctx, webhookID, accountID)
}

// RotateWebhookSecretCalls gets all the calls that were made to RotateWebhookSecret.
// Check the length with:
//
//	len(mockedRepository.RotateWebhookSecretCalls())
func (mock *RepositoryMock) RotateWebhookSecretCalls() []struct {
	Ctx       context.Context
	WebhookID string
	AccountID string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}
	mock.lockRotateWebhookSecret.RLock()
	calls = mock.calls.RotateWebhookSecret
	mock.lockRotateWebhookSecret.RUnlock()
	return calls
}

// WebhookExists calls WebhookExistsFunc.
func (mock *RepositoryMock) WebhookExists(ctx context.Context, webhookID string, accountID string) (bool, error) {
	if mock.WebhookExistsFunc == nil {
		panic("RepositoryMock.WebhookExistsFunc: method is nil but Repository.WebhookExists was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
		AccountID: accountID,
	}
	mock.lockWebhookExists.Lock()
	mock.calls.WebhookExists = append(mock.calls.WebhookExists, callInfo)
	mock.lockWebhookExists.Unlock()
	return mock.WebhookExistsFunc(ctx, webhookID, accountID)
}

// WebhookExistsCalls gets all the calls that were made to WebhookExists.
// Check the length with:
//
//	len(mockedRepository.WebhookExistsCalls())
func (mock *RepositoryMock) WebhookExistsCalls() []struct {
	Ctx       context.Context
	WebhookID string
	AccountID string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
		AccountID string
	}
	mock.lockWebhookExists.RLock()
	calls = mock.calls.WebhookExists
	mock.lockWebhookExists.RUnlock()
	return calls
}
