// Code generated by cmd/tools/codegen/fakes. DO NOT EDIT.

package fakes

import (
	"math"
	"time"

	types "github.com/primandproper/dinnerdonebetter/backend/internal/domain/webhooks"
	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/webhooks/converters"

	"github.com/primandproper/platform-go/v10/filtering"
	"github.com/primandproper/platform-go/v10/identifiers"

	fake "github.com/brianvoe/gofakeit/v7"
)

func init() {
	if err := fake.Seed(time.Now().UnixNano()); err != nil {
		panic(err)
	}
}

// exampleQuantity is how many elements a faked list has.
const exampleQuantity = 3

// BuildFakeID builds a fake ID.
func BuildFakeID() string {
	return identifiers.New()
}

// BuildFakeTime builds a fake time.
func BuildFakeTime() time.Time {
	return fake.Date().Add(0).Truncate(time.Second).UTC()
}

// buildFakeNumber builds a fake number comfortably above zero and below every integer
// width the domains use, so that it survives a conversion to any of them and no validator
// mistakes it for unset.
func buildFakeNumber() float64 {
	return math.Round(float64((fake.Number(101, math.MaxInt8-1) * 100) / 100))
}

// BuildFakeWebhook builds a faked Webhook.
func BuildFakeWebhook() *types.Webhook {
	webhookID := BuildFakeID()
	cfg := BuildFakeWebhookTriggerConfig()
	cfg.BelongsToWebhook = webhookID

	return &types.Webhook{
		CreatedAt:     BuildFakeTime(),
		ArchivedAt:    nil,
		LastUpdatedAt: nil,
		Name:          fake.UUID(),
		// A literal address from RFC 5737's TEST-NET-1, the range IANA reserves for exactly this.
		// Registration runs webhooks.CheckEndpointURL, which requires https and refuses any host that is
		// not globally routable — so a random fake domain is rejected for failing to resolve, and a
		// resolvable one would make every test that creates a webhook depend on DNS. A literal address
		// needs no lookup, and this one is nobody's.
		URL: "https://192.0.2.1/webhook",
		// The only method a webhook is delivered with, and the only one validation accepts. Named rather
		// than spelled so the fake follows the constant if it ever moves.
		Method:           types.DeliveryMethod,
		ID:               webhookID,
		BelongsToAccount: fake.UUID(),
		CreatedByUser:    fake.UUID(),
		// Validation pins this to encoding.ContentTypeJSON; the delivery worker no longer varies it, so
		// anything else is rejected at registration.
		ContentType:    "application/json",
		TriggerConfigs: []*types.WebhookTriggerConfig{cfg},
	}
}

// BuildFakeWebhooksList builds a faked Webhook list.
func BuildFakeWebhooksList() *filtering.QueryFilteredResult[types.Webhook] {
	var examples []*types.Webhook
	for range exampleQuantity {
		examples = append(examples, BuildFakeWebhook())
	}

	return &filtering.QueryFilteredResult[types.Webhook]{
		Pagination: filtering.Pagination{
			Cursor:          BuildFakeID(),
			MaxResponseSize: 50,
			FilteredCount:   exampleQuantity / 2,
			TotalCount:      exampleQuantity,
		},
		Data: examples,
	}
}

// BuildFakeWebhookCreationRequestInput builds a faked WebhookCreationRequestInput.
func BuildFakeWebhookCreationRequestInput() *types.WebhookCreationRequestInput {
	return converters.ConvertWebhookToWebhookCreationRequestInput(BuildFakeWebhook())
}

// BuildFakeWebhookTriggerConfig builds a faked WebhookTriggerConfig.
func BuildFakeWebhookTriggerConfig() *types.WebhookTriggerConfig {
	return &types.WebhookTriggerConfig{
		CreatedAt:        BuildFakeTime(),
		ArchivedAt:       nil,
		ID:               BuildFakeID(),
		BelongsToWebhook: BuildFakeID(),
		// An event type from the real catalog. An event type outside it is rejected at every boundary
		// that takes one, so a fake that invented them would only ever exercise the rejection path.
		EventType: BuildFakeWebhookEventType(),
	}
}
