// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: dataprivacy/dataprivacy_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import {
  AggregateUserDataReportRequest,
  AggregateUserDataReportResponse,
  DestroyAllUserDataRequest,
  DestroyAllUserDataResponse,
  FetchUserDataReportRequest,
  FetchUserDataReportResponse,
  GetDataPrivacyRequestRequest,
  GetDataPrivacyRequestResponse,
  ListDataPrivacyRequestsRequest,
  ListDataPrivacyRequestsResponse,
} from './dataprivacy_service_types';

export const protobufPackage = 'dataprivacy';

export type DataPrivacyServiceService = typeof DataPrivacyServiceService;
export const DataPrivacyServiceService = {
  aggregateUserDataReport: {
    path: '/dataprivacy.DataPrivacyService/AggregateUserDataReport' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AggregateUserDataReportRequest): Buffer =>
      Buffer.from(AggregateUserDataReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AggregateUserDataReportRequest => AggregateUserDataReportRequest.decode(value),
    responseSerialize: (value: AggregateUserDataReportResponse): Buffer =>
      Buffer.from(AggregateUserDataReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AggregateUserDataReportResponse =>
      AggregateUserDataReportResponse.decode(value),
  },
  destroyAllUserData: {
    path: '/dataprivacy.DataPrivacyService/DestroyAllUserData' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DestroyAllUserDataRequest): Buffer =>
      Buffer.from(DestroyAllUserDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DestroyAllUserDataRequest => DestroyAllUserDataRequest.decode(value),
    responseSerialize: (value: DestroyAllUserDataResponse): Buffer =>
      Buffer.from(DestroyAllUserDataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DestroyAllUserDataResponse => DestroyAllUserDataResponse.decode(value),
  },
  fetchUserDataReport: {
    path: '/dataprivacy.DataPrivacyService/FetchUserDataReport' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: FetchUserDataReportRequest): Buffer =>
      Buffer.from(FetchUserDataReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): FetchUserDataReportRequest => FetchUserDataReportRequest.decode(value),
    responseSerialize: (value: FetchUserDataReportResponse): Buffer =>
      Buffer.from(FetchUserDataReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FetchUserDataReportResponse => FetchUserDataReportResponse.decode(value),
  },
  getDataPrivacyRequest: {
    path: '/dataprivacy.DataPrivacyService/GetDataPrivacyRequest' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetDataPrivacyRequestRequest): Buffer =>
      Buffer.from(GetDataPrivacyRequestRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetDataPrivacyRequestRequest => GetDataPrivacyRequestRequest.decode(value),
    responseSerialize: (value: GetDataPrivacyRequestResponse): Buffer =>
      Buffer.from(GetDataPrivacyRequestResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetDataPrivacyRequestResponse => GetDataPrivacyRequestResponse.decode(value),
  },
  listDataPrivacyRequests: {
    path: '/dataprivacy.DataPrivacyService/ListDataPrivacyRequests' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListDataPrivacyRequestsRequest): Buffer =>
      Buffer.from(ListDataPrivacyRequestsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListDataPrivacyRequestsRequest => ListDataPrivacyRequestsRequest.decode(value),
    responseSerialize: (value: ListDataPrivacyRequestsResponse): Buffer =>
      Buffer.from(ListDataPrivacyRequestsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListDataPrivacyRequestsResponse =>
      ListDataPrivacyRequestsResponse.decode(value),
  },
} as const;

export interface DataPrivacyServiceServer extends UntypedServiceImplementation {
  aggregateUserDataReport: handleUnaryCall<AggregateUserDataReportRequest, AggregateUserDataReportResponse>;
  destroyAllUserData: handleUnaryCall<DestroyAllUserDataRequest, DestroyAllUserDataResponse>;
  fetchUserDataReport: handleUnaryCall<FetchUserDataReportRequest, FetchUserDataReportResponse>;
  getDataPrivacyRequest: handleUnaryCall<GetDataPrivacyRequestRequest, GetDataPrivacyRequestResponse>;
  listDataPrivacyRequests: handleUnaryCall<ListDataPrivacyRequestsRequest, ListDataPrivacyRequestsResponse>;
}

export interface DataPrivacyServiceClient extends Client {
  aggregateUserDataReport(
    request: AggregateUserDataReportRequest,
    callback: (error: ServiceError | null, response: AggregateUserDataReportResponse) => void,
  ): ClientUnaryCall;
  aggregateUserDataReport(
    request: AggregateUserDataReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AggregateUserDataReportResponse) => void,
  ): ClientUnaryCall;
  aggregateUserDataReport(
    request: AggregateUserDataReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AggregateUserDataReportResponse) => void,
  ): ClientUnaryCall;
  destroyAllUserData(
    request: DestroyAllUserDataRequest,
    callback: (error: ServiceError | null, response: DestroyAllUserDataResponse) => void,
  ): ClientUnaryCall;
  destroyAllUserData(
    request: DestroyAllUserDataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DestroyAllUserDataResponse) => void,
  ): ClientUnaryCall;
  destroyAllUserData(
    request: DestroyAllUserDataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DestroyAllUserDataResponse) => void,
  ): ClientUnaryCall;
  fetchUserDataReport(
    request: FetchUserDataReportRequest,
    callback: (error: ServiceError | null, response: FetchUserDataReportResponse) => void,
  ): ClientUnaryCall;
  fetchUserDataReport(
    request: FetchUserDataReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FetchUserDataReportResponse) => void,
  ): ClientUnaryCall;
  fetchUserDataReport(
    request: FetchUserDataReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FetchUserDataReportResponse) => void,
  ): ClientUnaryCall;
  getDataPrivacyRequest(
    request: GetDataPrivacyRequestRequest,
    callback: (error: ServiceError | null, response: GetDataPrivacyRequestResponse) => void,
  ): ClientUnaryCall;
  getDataPrivacyRequest(
    request: GetDataPrivacyRequestRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetDataPrivacyRequestResponse) => void,
  ): ClientUnaryCall;
  getDataPrivacyRequest(
    request: GetDataPrivacyRequestRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetDataPrivacyRequestResponse) => void,
  ): ClientUnaryCall;
  listDataPrivacyRequests(
    request: ListDataPrivacyRequestsRequest,
    callback: (error: ServiceError | null, response: ListDataPrivacyRequestsResponse) => void,
  ): ClientUnaryCall;
  listDataPrivacyRequests(
    request: ListDataPrivacyRequestsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListDataPrivacyRequestsResponse) => void,
  ): ClientUnaryCall;
  listDataPrivacyRequests(
    request: ListDataPrivacyRequestsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListDataPrivacyRequestsResponse) => void,
  ): ClientUnaryCall;
}

export const DataPrivacyServiceClient = makeGenericClientConstructor(
  DataPrivacyServiceService,
  'dataprivacy.DataPrivacyService',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): DataPrivacyServiceClient;
  service: typeof DataPrivacyServiceService;
  serviceName: string;
};
