// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: dataprivacy/dataprivacy_messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from '../google/protobuf/timestamp';

export const protobufPackage = 'dataprivacy';

/**
 * DataPrivacyRequest is one GDPR/CCPA export or erasure and everything known about how it went.
 *
 * It replaces UserDataDisclosure, and the twelve-field UserDataCollection message that used to
 * sit beside it. That message named every domain in the application, so adding a domain meant
 * editing it, regenerating three client languages, and shipping all of it together. An export's
 * contents are now opaque JSON delivered by FetchUserDataReport, and this message describes the
 * request rather than its payload — which is the part a client actually renders.
 */
export interface DataPrivacyRequest {
  id: string;
  /** subject_id is the user the request is about. */
  subjectId: string;
  /** request_type is "export" or "erasure". */
  requestType: string;
  /**
   * status is one of: awaiting_confirmation, pending, processing, completed, failed, expired,
   * cancelled. Only completed exports have a retrievable artifact, and only until expires_at.
   */
  status: string;
  /**
   * requested_at is when the statutory clock started. It is never rewritten, not by a
   * confirmation and not by a retry.
   */
  requestedAt: Date | undefined;
  /**
   * due_at is when the response is legally owed, stamped at submission from the configured
   * response window for the request type.
   */
  dueAt: Date | undefined;
  /** expires_at is when a completed export's artifact is deleted. Absent for an erasure. */
  expiresAt?: Date | undefined;
  completedAt?: Date | undefined;
  /**
   * failures names the sections that could not be collected, against the reason. A completed
   * export with entries here is a partial export: the artifact was still delivered, and its
   * manifest names these same sections as missing. A client showing "completed" over three
   * missing sections is misleading somebody who has thirty days to complain about it.
   */
  failures: { [key: string]: string };
  /** retained records, per eraser, what an erasure kept and the basis for keeping it. */
  retained: { [key: string]: string };
  /** deleted and anonymized are the erasure totals across every domain. */
  deleted: number;
  anonymized: number;
  /** artifact_bytes is the stored size of an export artifact, after compression and encryption. */
  artifactBytes: number;
  /** attempts is how many times a worker has claimed this request. */
  attempts: number;
  /** last_error is why a failed request failed. */
  lastError: string;
}

export interface DataPrivacyRequest_FailuresEntry {
  key: string;
  value: string;
}

export interface DataPrivacyRequest_RetainedEntry {
  key: string;
  value: string;
}

function createBaseDataPrivacyRequest(): DataPrivacyRequest {
  return {
    id: '',
    subjectId: '',
    requestType: '',
    status: '',
    requestedAt: undefined,
    dueAt: undefined,
    expiresAt: undefined,
    completedAt: undefined,
    failures: {},
    retained: {},
    deleted: 0,
    anonymized: 0,
    artifactBytes: 0,
    attempts: 0,
    lastError: '',
  };
}

export const DataPrivacyRequest: MessageFns<DataPrivacyRequest> = {
  encode(message: DataPrivacyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.subjectId !== '') {
      writer.uint32(18).string(message.subjectId);
    }
    if (message.requestType !== '') {
      writer.uint32(26).string(message.requestType);
    }
    if (message.status !== '') {
      writer.uint32(34).string(message.status);
    }
    if (message.requestedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.requestedAt), writer.uint32(42).fork()).join();
    }
    if (message.dueAt !== undefined) {
      Timestamp.encode(toTimestamp(message.dueAt), writer.uint32(50).fork()).join();
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(58).fork()).join();
    }
    if (message.completedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.completedAt), writer.uint32(66).fork()).join();
    }
    globalThis.Object.entries(message.failures).forEach(([key, value]: [string, string]) => {
      DataPrivacyRequest_FailuresEntry.encode({ key: key as any, value }, writer.uint32(74).fork()).join();
    });
    globalThis.Object.entries(message.retained).forEach(([key, value]: [string, string]) => {
      DataPrivacyRequest_RetainedEntry.encode({ key: key as any, value }, writer.uint32(82).fork()).join();
    });
    if (message.deleted !== 0) {
      writer.uint32(88).int64(message.deleted);
    }
    if (message.anonymized !== 0) {
      writer.uint32(96).int64(message.anonymized);
    }
    if (message.artifactBytes !== 0) {
      writer.uint32(104).int64(message.artifactBytes);
    }
    if (message.attempts !== 0) {
      writer.uint32(112).int32(message.attempts);
    }
    if (message.lastError !== '') {
      writer.uint32(122).string(message.lastError);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataPrivacyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataPrivacyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subjectId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.dueAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.completedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          const entry9 = DataPrivacyRequest_FailuresEntry.decode(reader, reader.uint32());
          if (entry9.value !== undefined) {
            message.failures[entry9.key] = entry9.value;
          }
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          const entry10 = DataPrivacyRequest_RetainedEntry.decode(reader, reader.uint32());
          if (entry10.value !== undefined) {
            message.retained[entry10.key] = entry10.value;
          }
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.deleted = longToNumber(reader.int64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.anonymized = longToNumber(reader.int64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.artifactBytes = longToNumber(reader.int64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.attempts = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataPrivacyRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      subjectId: isSet(object.subjectId)
        ? globalThis.String(object.subjectId)
        : isSet(object.subject_id)
          ? globalThis.String(object.subject_id)
          : '',
      requestType: isSet(object.requestType)
        ? globalThis.String(object.requestType)
        : isSet(object.request_type)
          ? globalThis.String(object.request_type)
          : '',
      status: isSet(object.status) ? globalThis.String(object.status) : '',
      requestedAt: isSet(object.requestedAt)
        ? fromJsonTimestamp(object.requestedAt)
        : isSet(object.requested_at)
          ? fromJsonTimestamp(object.requested_at)
          : undefined,
      dueAt: isSet(object.dueAt)
        ? fromJsonTimestamp(object.dueAt)
        : isSet(object.due_at)
          ? fromJsonTimestamp(object.due_at)
          : undefined,
      expiresAt: isSet(object.expiresAt)
        ? fromJsonTimestamp(object.expiresAt)
        : isSet(object.expires_at)
          ? fromJsonTimestamp(object.expires_at)
          : undefined,
      completedAt: isSet(object.completedAt)
        ? fromJsonTimestamp(object.completedAt)
        : isSet(object.completed_at)
          ? fromJsonTimestamp(object.completed_at)
          : undefined,
      failures: isObject(object.failures)
        ? (globalThis.Object.entries(object.failures) as [string, any][]).reduce(
            (acc: { [key: string]: string }, [key, value]: [string, any]) => {
              acc[key] = globalThis.String(value);
              return acc;
            },
            {},
          )
        : {},
      retained: isObject(object.retained)
        ? (globalThis.Object.entries(object.retained) as [string, any][]).reduce(
            (acc: { [key: string]: string }, [key, value]: [string, any]) => {
              acc[key] = globalThis.String(value);
              return acc;
            },
            {},
          )
        : {},
      deleted: isSet(object.deleted) ? globalThis.Number(object.deleted) : 0,
      anonymized: isSet(object.anonymized) ? globalThis.Number(object.anonymized) : 0,
      artifactBytes: isSet(object.artifactBytes)
        ? globalThis.Number(object.artifactBytes)
        : isSet(object.artifact_bytes)
          ? globalThis.Number(object.artifact_bytes)
          : 0,
      attempts: isSet(object.attempts) ? globalThis.Number(object.attempts) : 0,
      lastError: isSet(object.lastError)
        ? globalThis.String(object.lastError)
        : isSet(object.last_error)
          ? globalThis.String(object.last_error)
          : '',
    };
  },

  toJSON(message: DataPrivacyRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.subjectId !== '') {
      obj.subjectId = message.subjectId;
    }
    if (message.requestType !== '') {
      obj.requestType = message.requestType;
    }
    if (message.status !== '') {
      obj.status = message.status;
    }
    if (message.requestedAt !== undefined) {
      obj.requestedAt = message.requestedAt.toISOString();
    }
    if (message.dueAt !== undefined) {
      obj.dueAt = message.dueAt.toISOString();
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.completedAt !== undefined) {
      obj.completedAt = message.completedAt.toISOString();
    }
    if (message.failures) {
      const entries = globalThis.Object.entries(message.failures) as [string, string][];
      if (entries.length > 0) {
        obj.failures = {};
        entries.forEach(([k, v]) => {
          obj.failures[k] = v;
        });
      }
    }
    if (message.retained) {
      const entries = globalThis.Object.entries(message.retained) as [string, string][];
      if (entries.length > 0) {
        obj.retained = {};
        entries.forEach(([k, v]) => {
          obj.retained[k] = v;
        });
      }
    }
    if (message.deleted !== 0) {
      obj.deleted = Math.round(message.deleted);
    }
    if (message.anonymized !== 0) {
      obj.anonymized = Math.round(message.anonymized);
    }
    if (message.artifactBytes !== 0) {
      obj.artifactBytes = Math.round(message.artifactBytes);
    }
    if (message.attempts !== 0) {
      obj.attempts = Math.round(message.attempts);
    }
    if (message.lastError !== '') {
      obj.lastError = message.lastError;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataPrivacyRequest>, I>>(base?: I): DataPrivacyRequest {
    return DataPrivacyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataPrivacyRequest>, I>>(object: I): DataPrivacyRequest {
    const message = createBaseDataPrivacyRequest();
    message.id = object.id ?? '';
    message.subjectId = object.subjectId ?? '';
    message.requestType = object.requestType ?? '';
    message.status = object.status ?? '';
    message.requestedAt = object.requestedAt ?? undefined;
    message.dueAt = object.dueAt ?? undefined;
    message.expiresAt = object.expiresAt ?? undefined;
    message.completedAt = object.completedAt ?? undefined;
    message.failures = (globalThis.Object.entries(object.failures ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.retained = (globalThis.Object.entries(object.retained ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.deleted = object.deleted ?? 0;
    message.anonymized = object.anonymized ?? 0;
    message.artifactBytes = object.artifactBytes ?? 0;
    message.attempts = object.attempts ?? 0;
    message.lastError = object.lastError ?? '';
    return message;
  },
};

function createBaseDataPrivacyRequest_FailuresEntry(): DataPrivacyRequest_FailuresEntry {
  return { key: '', value: '' };
}

export const DataPrivacyRequest_FailuresEntry: MessageFns<DataPrivacyRequest_FailuresEntry> = {
  encode(message: DataPrivacyRequest_FailuresEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== '') {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== '') {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataPrivacyRequest_FailuresEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataPrivacyRequest_FailuresEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataPrivacyRequest_FailuresEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? globalThis.String(object.value) : '',
    };
  },

  toJSON(message: DataPrivacyRequest_FailuresEntry): unknown {
    const obj: any = {};
    if (message.key !== '') {
      obj.key = message.key;
    }
    if (message.value !== '') {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataPrivacyRequest_FailuresEntry>, I>>(
    base?: I,
  ): DataPrivacyRequest_FailuresEntry {
    return DataPrivacyRequest_FailuresEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataPrivacyRequest_FailuresEntry>, I>>(
    object: I,
  ): DataPrivacyRequest_FailuresEntry {
    const message = createBaseDataPrivacyRequest_FailuresEntry();
    message.key = object.key ?? '';
    message.value = object.value ?? '';
    return message;
  },
};

function createBaseDataPrivacyRequest_RetainedEntry(): DataPrivacyRequest_RetainedEntry {
  return { key: '', value: '' };
}

export const DataPrivacyRequest_RetainedEntry: MessageFns<DataPrivacyRequest_RetainedEntry> = {
  encode(message: DataPrivacyRequest_RetainedEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== '') {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== '') {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataPrivacyRequest_RetainedEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataPrivacyRequest_RetainedEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataPrivacyRequest_RetainedEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? globalThis.String(object.value) : '',
    };
  },

  toJSON(message: DataPrivacyRequest_RetainedEntry): unknown {
    const obj: any = {};
    if (message.key !== '') {
      obj.key = message.key;
    }
    if (message.value !== '') {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataPrivacyRequest_RetainedEntry>, I>>(
    base?: I,
  ): DataPrivacyRequest_RetainedEntry {
    return DataPrivacyRequest_RetainedEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataPrivacyRequest_RetainedEntry>, I>>(
    object: I,
  ): DataPrivacyRequest_RetainedEntry {
    const message = createBaseDataPrivacyRequest_RetainedEntry();
    message.key = object.key ?? '';
    message.value = object.value ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === 'object' && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
