package main

// Conversions declared for the oauth domain.
//
// A conversion with no Fields is a whole-struct copy: every field of the destination is
// filled from the field of the same name, and the generator fails rather than leave one
// empty. Fields carries a rule per destination field where that is not what happens, and
// the reason it carries is rendered into the generated source. See declaration.go for the
// rules, and converters_manual.go in the domain for the conversions this cannot express.

func init() {
	register("oauth", []*Conversion{
		{Name: "ConvertOAuth2ClientCreationRequestInputToOAuth2ClientDatabaseCreationInput", From: Param{Name: "x", Type: "OAuth2ClientCreationRequestInput"}, To: "OAuth2ClientDatabaseCreationInput",
			Fields: map[string]Rule{
				"ClientID":     Skip("Generated by the manager from the secret generator, never taken from the request: a client that could choose its own ID could choose another client's."),
				"ClientSecret": Skip("Generated by the manager and stored only as its SHA-256 digest; the plaintext is returned to the caller exactly once."),
				"ID":           NewID(),
			},
		},
		{Name: "ConvertOAuth2ClientToOAuth2ClientDatabaseCreationInput", From: Param{Name: "client", Type: "OAuth2Client"}, To: "OAuth2ClientDatabaseCreationInput"},
		{Name: "ConvertOAuth2ClientToOAuth2ClientCreationInput", From: Param{Name: "client", Type: "OAuth2Client"}, To: "OAuth2ClientCreationRequestInput"},
		{Name: "ConvertOAuth2ClientToOAuth2ClientCreationResponse", From: Param{Name: "client", Type: "OAuth2Client"}, To: "OAuth2ClientCreationResponse"},
		{Name: "ConvertOAuth2ClientTokenToOAuth2ClientTokenDatabaseCreationInput", From: Param{Name: "x", Type: "OAuth2ClientToken"}, To: "OAuth2ClientTokenDatabaseCreationInput",
			Fields: map[string]Rule{
				"AccessExpiresIn":  Rename("AccessExpiresAt"),
				"CodeExpiresIn":    Rename("CodeExpiresAt"),
				"RefreshExpiresIn": Rename("RefreshExpiresAt"),
			},
		},
	})
}
