package main

// Conversions declared for the mealplanning domain.
//
// A conversion with no Fields is a whole-struct copy: every field of the destination is
// filled from the field of the same name, and the generator fails rather than leave one
// empty. Fields carries a rule per destination field where that is not what happens, and
// the reason it carries is rendered into the generated source. See declaration.go for the
// rules, and converters_manual.go in the domain for the conversions this cannot express.

func init() {
	register("mealplanning", []*Conversion{
		{Name: "ConvertAccountInstrumentOwnershipToAccountInstrumentOwnershipUpdateRequestInput", From: Param{Name: "x", Type: "AccountInstrumentOwnership"}, To: "AccountInstrumentOwnershipUpdateRequestInput",
			Fields: map[string]Rule{
				"ValidInstrumentID": NestedID("Instrument"),
			},
		},
		{Name: "ConvertAccountInstrumentOwnershipCreationRequestInputToAccountInstrumentOwnershipDatabaseCreationInput", From: Param{Name: "x", Type: "AccountInstrumentOwnershipCreationRequestInput"}, To: "AccountInstrumentOwnershipDatabaseCreationInput",
			Fields: map[string]Rule{
				"BelongsToAccount": Skip("Comes from the session rather than the request body, so the manager stamps it after this."),
				"ID":               NewID(),
			},
		},
		{Name: "ConvertAccountInstrumentOwnershipToAccountInstrumentOwnershipCreationRequestInput", From: Param{Name: "x", Type: "AccountInstrumentOwnership"}, To: "AccountInstrumentOwnershipCreationRequestInput",
			Fields: map[string]Rule{
				"ValidInstrumentID": NestedID("Instrument"),
			},
		},
		{Name: "ConvertAccountInstrumentOwnershipToAccountInstrumentOwnershipDatabaseCreationInput", From: Param{Name: "x", Type: "AccountInstrumentOwnership"}, To: "AccountInstrumentOwnershipDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidInstrumentID": NestedID("Instrument"),
			},
		},
		{Name: "ConvertMealPlanEventToMealPlanEventUpdateRequestInput", From: Param{Name: "input", Type: "MealPlanEvent"}, To: "MealPlanEventUpdateRequestInput"},
		{Name: "ConvertMealPlanEventCreationRequestInputToMealPlanEventDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanEventCreationRequestInput"}, To: "MealPlanEventDatabaseCreationInput",
			Fields: map[string]Rule{
				"BelongsToMealPlan": Skip("The parent does not exist yet when a request is parsed; whoever mints its ID stamps this."),
				"ID":                NewID(),
				"Options":           MapSlice("ConvertMealPlanOptionCreationRequestInputToMealPlanOptionDatabaseCreationInput", FromField("Options")),
			},
		},
		{Name: "ConvertMealPlanEventToMealPlanEventDatabaseCreationInput", From: Param{Name: "mealPlanEvent", Type: "MealPlanEvent"}, To: "MealPlanEventDatabaseCreationInput",
			Fields: map[string]Rule{
				"Options": MapSlice("ConvertMealPlanOptionToMealPlanOptionDatabaseCreationInput", FromField("Options")),
			},
		},
		{Name: "ConvertMealPlanGroceryListItemToMealPlanGroceryListItemDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanGroceryListItem"}, To: "MealPlanGroceryListItemDatabaseCreationInput",
			Fields: map[string]Rule{
				"PurchasedMeasurementUnitID": OptionalNestedID("PurchasedMeasurementUnit"),
				"ValidIngredientID":          NestedID("Ingredient"),
				"ValidMeasurementUnitID":     NestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertMealPlanGroceryListItemToMealPlanGroceryListItemCreationRequestInput", From: Param{Name: "input", Type: "MealPlanGroceryListItem"}, To: "MealPlanGroceryListItemCreationRequestInput",
			Fields: map[string]Rule{
				"PurchasedMeasurementUnitID": OptionalNestedID("PurchasedMeasurementUnit"),
				"ValidIngredientID":          NestedID("Ingredient"),
				"ValidMeasurementUnitID":     NestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertMealPlanGroceryListItemCreationRequestInputToMealPlanGroceryListItemDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanGroceryListItemCreationRequestInput"}, To: "MealPlanGroceryListItemDatabaseCreationInput",
			Fields: map[string]Rule{
				"BelongsToMealPlanOption": Skip("Provenance the grocery list generator records — which option, which recipe, which step an item came from. An item created by hand has none of it, and the request input carries no such field."),
				"ID":                      NewID(),
				"IngredientIndex":         Skip("Generator provenance; see BelongsToMealPlanOption."),
				"OptionIndex":             Skip("Generator provenance; see BelongsToMealPlanOption."),
				"RecipeID":                Skip("Generator provenance; see BelongsToMealPlanOption."),
				"RecipeStepID":            Skip("Generator provenance; see BelongsToMealPlanOption."),
			},
		},
		{Name: "ConvertMealPlanGroceryListItemToMealPlanGroceryListItemUpdateRequestInput", From: Param{Name: "input", Type: "MealPlanGroceryListItem"}, To: "MealPlanGroceryListItemUpdateRequestInput",
			Fields: map[string]Rule{
				"PurchasedMeasurementUnitID": OptionalNestedID("PurchasedMeasurementUnit"),
				"ValidIngredientID":          NestedID("Ingredient"),
				"ValidMeasurementUnitID":     NestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertMealPlanOptionVoteToMealPlanOptionVoteUpdateRequestInput", From: Param{Name: "input", Type: "MealPlanOptionVote"}, To: "MealPlanOptionVoteUpdateRequestInput"},
		{Name: "ConvertMealPlanOptionVoteCreationRequestInputToMealPlanOptionVotesDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanOptionVoteCreationRequestInput"}, To: "MealPlanOptionVotesDatabaseCreationInput",
			Fields: map[string]Rule{
				"Votes": MapSlice("ConvertMealPlanOptionVoteCreationRequestInputToMealPlanOptionVoteDatabaseCreationInput", FromField("Votes"), NilWhenEmpty()),
			},
		},
		{Name: "ConvertMealPlanOptionVoteCreationRequestInputToMealPlanOptionVoteDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanOptionVoteCreationInput"}, To: "MealPlanOptionVoteDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertMealPlanOptionToMealPlanOptionUpdateRequestInput", From: Param{Name: "input", Type: "MealPlanOption"}, To: "MealPlanOptionUpdateRequestInput",
			Fields: map[string]Rule{
				"MealID": NestedID("Meal"),
			},
		},
		{Name: "ConvertMealPlanOptionCreationRequestInputToMealPlanOptionDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanOptionCreationRequestInput"}, To: "MealPlanOptionDatabaseCreationInput",
			Fields: map[string]Rule{
				"BelongsToMealPlanEvent": Skip("The parent does not exist yet when a request is parsed; whoever mints its ID stamps this."),
				"ID":                     NewID(),
			},
		},
		{Name: "ConvertMealPlanOptionToMealPlanOptionCreationRequestInput", From: Param{Name: "mealPlanOption", Type: "MealPlanOption"}, To: "MealPlanOptionCreationRequestInput",
			Fields: map[string]Rule{
				"MealID":     NestedID("Meal"),
				"Selections": Skip("A stored MealPlanOption does not carry the recipe selections made against it; they are read from the meal plan."),
			},
		},
		{Name: "ConvertMealPlanOptionToMealPlanOptionDatabaseCreationInput", From: Param{Name: "mealPlanOption", Type: "MealPlanOption"}, To: "MealPlanOptionDatabaseCreationInput",
			Fields: map[string]Rule{
				"MealID": NestedID("Meal"),
			},
		},
		{Name: "ConvertMealPlanRecipeOptionSelectionToMealPlanRecipeOptionSelectionDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanRecipeOptionSelection"}, To: "MealPlanRecipeOptionSelectionDatabaseCreationInput"},
		{Name: "ConvertMealPlanRecipeOptionSelectionDatabaseCreationInputToMealPlanRecipeOptionSelectionDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanRecipeOptionSelectionCreationRequestInput"}, Extra: []Param{{Name: "mealPlanOptionID", Type: "string"}}, To: "MealPlanRecipeOptionSelectionDatabaseCreationInput",
			Fields: map[string]Rule{
				"BelongsToMealPlanOption": Expr("mealPlanOptionID", "The option a selection belongs to is the caller's to name: the same request input is applied to whichever option is being voted on."),
				"ID":                      NewID(),
			},
		},
		{Name: "ConvertMealPlanTaskCreationRequestInputToMealPlanTaskDatabaseCreationInput", From: Param{Name: "input", Type: "MealPlanTaskCreationRequestInput"}, To: "MealPlanTaskDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertMealPlanTaskToMealPlanTaskCreationRequestInput", From: Param{Name: "x", Type: "MealPlanTask"}, To: "MealPlanTaskCreationRequestInput",
			Fields: map[string]Rule{
				"MealPlanOptionID": NestedID("MealPlanOption"),
				"RecipePrepTaskID": NestedID("RecipePrepTask"),
			},
		},
		{Name: "ConvertMealPlanTaskToMealPlanTaskDatabaseCreationInput", From: Param{Name: "x", Type: "MealPlanTask"}, To: "MealPlanTaskDatabaseCreationInput",
			Fields: map[string]Rule{
				"MealPlanOptionID": NestedID("MealPlanOption"),
				"RecipePrepTaskID": NestedID("RecipePrepTask"),
			},
		},
		{Name: "ConvertMealPlanToMealPlanUpdateRequestInput", From: Param{Name: "input", Type: "MealPlan"}, To: "MealPlanUpdateRequestInput"},
		{Name: "ConvertMealPlanToMealPlanCreationRequestInput", From: Param{Name: "mealPlan", Type: "MealPlan"}, To: "MealPlanCreationRequestInput",
			Fields: map[string]Rule{
				"Events":     MapSlice("ConvertMealPlanEventToMealPlanEventCreationRequestInput", FromField("Events")),
				"Selections": Skip("MealPlan carries selections in their stored shape and the converter this replaced did not map them back to request inputs. Preserved rather than corrected, so that generating these converters is not also a behavior change."),
			},
		},
		{Name: "ConvertMealPlanToMealPlanDatabaseCreationInput", From: Param{Name: "mealPlan", Type: "MealPlan"}, To: "MealPlanDatabaseCreationInput",
			Fields: map[string]Rule{
				"Events":     MapSlice("ConvertMealPlanEventToMealPlanEventDatabaseCreationInput", FromField("Events")),
				"Selections": MapSlice("ConvertMealPlanRecipeOptionSelectionToMealPlanRecipeOptionSelectionDatabaseCreationInput", FromField("Selections")),
			},
		},
		{Name: "ConvertRecipeRatingToRecipeRatingUpdateRequestInput", From: Param{Name: "x", Type: "RecipeRating"}, To: "RecipeRatingUpdateRequestInput"},
		{Name: "ConvertRecipeRatingCreationRequestInputToRecipeRatingDatabaseCreationInput", From: Param{Name: "x", Type: "RecipeRatingCreationRequestInput"}, To: "RecipeRatingDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertRecipeRatingToRecipeRatingCreationRequestInput", From: Param{Name: "x", Type: "RecipeRating"}, To: "RecipeRatingCreationRequestInput"},
		{Name: "ConvertRecipeRatingToRecipeRatingDatabaseCreationInput", From: Param{Name: "x", Type: "RecipeRating"}, To: "RecipeRatingDatabaseCreationInput"},
		{Name: "ConvertMealCreationRequestInputToMealDatabaseCreationInput", From: Param{Name: "input", Type: "MealCreationRequestInput"}, To: "MealDatabaseCreationInput",
			Fields: map[string]Rule{
				"Components":    MapSlice("ConvertMealComponentCreationRequestInputToMealComponentDatabaseCreationInput", FromField("Components")),
				"CreatedByUser": Skip("Comes from the session rather than the request body, so the manager stamps it after this."),
				"ID":            NewID(),
			},
		},
		{Name: "ConvertMealComponentCreationRequestInputToMealComponentDatabaseCreationInput", From: Param{Name: "input", Type: "MealComponentCreationRequestInput"}, To: "MealComponentDatabaseCreationInput"},
		{Name: "ConvertMealToMealCreationRequestInput", From: Param{Name: "meal", Type: "Meal"}, To: "MealCreationRequestInput",
			Fields: map[string]Rule{
				"Components": MapSlice("ConvertMealComponentToMealComponentCreationRequestInput", FromField("Components")),
			},
		},
		{Name: "ConvertMealComponentToMealComponentCreationRequestInput", From: Param{Name: "input", Type: "MealComponent"}, To: "MealComponentCreationRequestInput",
			Fields: map[string]Rule{
				"RecipeID": NestedID("Recipe"),
			},
		},
		{Name: "ConvertMealToMealDatabaseCreationInput", From: Param{Name: "meal", Type: "Meal"}, To: "MealDatabaseCreationInput",
			Fields: map[string]Rule{
				"Components": MapSlice("ConvertMealComponentToMealComponentDatabaseCreationInput", FromField("Components")),
			},
		},
		{Name: "ConvertMealComponentToMealComponentDatabaseCreationInput", From: Param{Name: "input", Type: "MealComponent"}, To: "MealComponentDatabaseCreationInput",
			Fields: map[string]Rule{
				"RecipeID": NestedID("Recipe"),
			},
		},
		{Name: "ConvertRecipeListItemCreationRequestInputToRecipeListItemDatabaseCreationInput", From: Param{Name: "x", Type: "RecipeListItemCreationRequestInput"}, Extra: []Param{{Name: "recipeListID", Type: "string"}}, To: "RecipeListItemDatabaseCreationInput",
			Fields: map[string]Rule{
				"BelongsToRecipeList": Expr("recipeListID", "The list an item joins is the caller's to name; the request body carries only the item."),
				"ID":                  NewID(),
			},
		},
		{Name: "ConvertRecipeMediaToRecipeMediaUpdateRequestInput", From: Param{Name: "input", Type: "RecipeMedia"}, To: "RecipeMediaUpdateRequestInput"},
		{Name: "ConvertRecipeMediaCreationRequestInputToRecipeMediaDatabaseCreationInput", From: Param{Name: "input", Type: "RecipeMediaCreationRequestInput"}, To: "RecipeMediaDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertRecipeMediaToRecipeMediaCreationRequestInput", From: Param{Name: "recipeMedia", Type: "RecipeMedia"}, To: "RecipeMediaCreationRequestInput"},
		{Name: "ConvertRecipeMediaToRecipeMediaDatabaseCreationInput", From: Param{Name: "recipeMedia", Type: "RecipeMedia"}, To: "RecipeMediaDatabaseCreationInput"},
		{Name: "ConvertRecipePrepTaskToRecipePrepTaskDatabaseCreationInput", From: Param{Name: "input", Type: "RecipePrepTask"}, To: "RecipePrepTaskDatabaseCreationInput",
			Fields: map[string]Rule{
				"TaskSteps": MapSlice("ConvertRecipePrepTaskStepToRecipePrepTaskStepDatabaseCreationInput", FromField("TaskSteps")),
			},
		},
		{Name: "ConvertRecipePrepTaskStepToRecipePrepTaskStepCreationRequestInput", From: Param{Name: "input", Type: "RecipePrepTaskStep"}, To: "RecipePrepTaskStepCreationRequestInput"},
		{Name: "ConvertRecipePrepTaskToRecipePrepTaskCreationRequestInput", From: Param{Name: "input", Type: "RecipePrepTask"}, To: "RecipePrepTaskCreationRequestInput",
			Fields: map[string]Rule{
				"RecipeSteps": MapSlice("ConvertRecipePrepTaskStepToRecipePrepTaskStepCreationRequestInput", FromField("TaskSteps")),
			},
		},
		{Name: "ConvertRecipePrepTaskStepToRecipePrepTaskStepUpdateRequestInput", From: Param{Name: "input", Type: "RecipePrepTaskStep"}, To: "RecipePrepTaskStepUpdateRequestInput",
			Fields: map[string]Rule{
				"BelongsToRecipePrepTask": Expr("new(input.BelongsToRecipePrepTask)", "An update input holds pointers, and this one points at a copy rather than at the entity's own field."),
				"BelongsToRecipeStep":     Expr("new(input.BelongsToRecipeStep)", "An update input holds pointers, and this one points at a copy rather than at the entity's own field."),
				"SatisfiesRecipeStep":     Expr("new(input.SatisfiesRecipeStep)", "An update input holds pointers, and this one points at a copy rather than at the entity's own field."),
			},
		},
		{Name: "ConvertRecipePrepTaskStepToRecipePrepTaskStepDatabaseCreationInput", From: Param{Name: "input", Type: "RecipePrepTaskStep"}, To: "RecipePrepTaskStepDatabaseCreationInput"},
		{Name: "ConvertRecipeStepCompletionConditionForExistingRecipeCreationRequestInputToRecipeStepCompletionConditionDatabaseCreationInput", From: Param{Name: "input", Type: "RecipeStepCompletionConditionForExistingRecipeCreationRequestInput"}, To: "RecipeStepCompletionConditionDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID":          NewID(),
				"Ingredients": MapSlice("ConvertRecipeStepCompletionConditionIngredientForExistingRecipeCreationRequestInputToRecipeStepCompletionConditionIngredientDatabaseCreationInput", FromField("Ingredients"), BelongsTo("BelongsToRecipeStepCompletionCondition"), NilWhenEmpty()),
			},
		},
		{Name: "ConvertRecipeStepCompletionConditionIngredientForExistingRecipeCreationRequestInputToRecipeStepCompletionConditionIngredientDatabaseCreationInput", From: Param{Name: "input", Type: "RecipeStepCompletionConditionIngredientForExistingRecipeCreationRequestInput"}, To: "RecipeStepCompletionConditionIngredientDatabaseCreationInput",
			Fields: map[string]Rule{
				"BelongsToRecipeStepCompletionCondition": Skip("The parent does not exist yet when a request is parsed; whoever mints its ID stamps this."),
				"ID":                                     NewID(),
			},
		},
		{Name: "ConvertRecipeStepCompletionConditionToRecipeStepCompletionConditionUpdateRequestInput", From: Param{Name: "input", Type: "RecipeStepCompletionCondition"}, To: "RecipeStepCompletionConditionUpdateRequestInput",
			Fields: map[string]Rule{
				"IngredientStateID": NestedID("IngredientState"),
			},
		},
		{Name: "ConvertRecipeStepCompletionConditionIngredientToRecipeStepCompletionConditionIngredientForExistingRecipeCreationRequestInput", From: Param{Name: "recipeStepCompletionConditionIngredient", Type: "RecipeStepCompletionConditionIngredient"}, To: "RecipeStepCompletionConditionIngredientForExistingRecipeCreationRequestInput"},
		{Name: "ConvertRecipeStepIngredientToRecipeStepIngredientUpdateRequestInput", From: Param{Name: "input", Type: "RecipeStepIngredient"}, To: "RecipeStepIngredientUpdateRequestInput",
			Fields: map[string]Rule{
				"IngredientID":              NestedID("Ingredient"),
				"MeasurementUnitID":         NestedID("MeasurementUnit"),
				"RecipeStepProductRecipeID": Skip("RecipeStepIngredient carries this and the converter this replaced did not copy it. Preserved rather than corrected, so that generating these converters is not also a behavior change."),
			},
		},
		{Name: "ConvertRecipeStepIngredientToRecipeStepIngredientDatabaseCreationInput", From: Param{Name: "input", Type: "RecipeStepIngredient"}, To: "RecipeStepIngredientDatabaseCreationInput",
			Fields: map[string]Rule{
				"IngredientID":                     OptionalNestedID("Ingredient"),
				"MeasurementUnitID":                NestedID("MeasurementUnit"),
				"ProductOfRecipeStepIndex":         Skip("An index into the recipe being created, resolved to an ID once it is. A stored step has the ID and no longer the index."),
				"ProductOfRecipeStepProductIndex":  Skip("An index into the recipe being created; see ProductOfRecipeStepIndex."),
				"ScaleFactor":                      Expr("scaleFactorOrDefault(input.ScaleFactor)", "Zero means unset on the wire and one in the database, and scaleFactorOrDefault is where that is decided."),
				"ValidIngredientMeasurementUnitID": Skip("The bridge-table row this step was built from. A stored step keeps the entity it resolved to, not the row that justified it."),
				"ValidIngredientPreparationID":     Skip("The bridge-table row this step was built from. A stored step keeps the entity it resolved to, not the row that justified it."),
			},
		},
		{Name: "ConvertRecipeStepInstrumentToRecipeStepInstrumentUpdateRequestInput", From: Param{Name: "input", Type: "RecipeStepInstrument"}, To: "RecipeStepInstrumentUpdateRequestInput",
			Fields: map[string]Rule{
				"InstrumentID": NestedID("Instrument"),
			},
		},
		{Name: "ConvertRecipeStepInstrumentToRecipeStepInstrumentDatabaseCreationInput", From: Param{Name: "input", Type: "RecipeStepInstrument"}, To: "RecipeStepInstrumentDatabaseCreationInput",
			Fields: map[string]Rule{
				"InstrumentID":                    OptionalNestedID("Instrument"),
				"ProductOfRecipeStepIndex":        Skip("An index into the recipe being created, resolved to an ID once it is. A stored step has the ID and no longer the index."),
				"ProductOfRecipeStepProductIndex": Skip("An index into the recipe being created; see ProductOfRecipeStepIndex."),
				"ScaleFactor":                     Expr("scaleFactorOrDefault(input.ScaleFactor)", "Zero means unset on the wire and one in the database, and scaleFactorOrDefault is where that is decided."),
				"ValidPreparationInstrumentID":    Skip("The bridge-table row this step was built from. A stored step keeps the entity it resolved to, not the row that justified it."),
			},
		},
		{Name: "ConvertRecipeStepProductToRecipeStepProductCreationRequestInput", From: Param{Name: "recipeStepProduct", Type: "RecipeStepProduct"}, To: "RecipeStepProductCreationRequestInput",
			Fields: map[string]Rule{
				"MeasurementUnitID": NestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertRecipeStepProductToRecipeStepProductDatabaseCreationInput", From: Param{Name: "recipeStepProduct", Type: "RecipeStepProduct"}, To: "RecipeStepProductDatabaseCreationInput",
			Fields: map[string]Rule{
				"MeasurementUnitID": OptionalNestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertRecipeStepVesselToRecipeStepVesselUpdateRequestInput", From: Param{Name: "input", Type: "RecipeStepVessel"}, To: "RecipeStepVesselUpdateRequestInput",
			Fields: map[string]Rule{
				"VesselID": NestedID("Vessel"),
			},
		},
		{Name: "ConvertRecipeStepVesselToRecipeStepVesselDatabaseCreationInput", From: Param{Name: "input", Type: "RecipeStepVessel"}, To: "RecipeStepVesselDatabaseCreationInput",
			Fields: map[string]Rule{
				"ProductOfRecipeStepIndex":        Skip("An index into the recipe being created, resolved to an ID once it is. A stored step has the ID and no longer the index."),
				"ProductOfRecipeStepProductIndex": Skip("An index into the recipe being created; see ProductOfRecipeStepIndex."),
				"ScaleFactor":                     Expr("scaleFactorOrDefault(input.ScaleFactor)", "Zero means unset on the wire and one in the database, and scaleFactorOrDefault is where that is decided."),
				"ValidPreparationVesselID":        Skip("The bridge-table row this step was built from. A stored step keeps the entity it resolved to, not the row that justified it."),
				"VesselID":                        OptionalNestedID("Vessel"),
			},
		},
		{Name: "ConvertRecipeStepToRecipeStepUpdateRequestInput", From: Param{Name: "input", Type: "RecipeStep"}, To: "RecipeStepUpdateRequestInput"},
		{Name: "ConvertRecipeStepToRecipeStepCreationRequestInput", From: Param{Name: "recipeStep", Type: "RecipeStep"}, To: "RecipeStepCreationRequestInput",
			Fields: map[string]Rule{
				"CompletionConditions": MapSlice("ConvertRecipeStepCompletionConditionToRecipeStepCompletionConditionCreationRequestInput", FromField("CompletionConditions"), WithArgs("recipeStep", "item")),
				"Ingredients":          MapSlice("ConvertRecipeStepIngredientToRecipeStepIngredientCreationRequestInput", FromField("Ingredients")),
				"Instruments":          MapSlice("ConvertRecipeStepInstrumentToRecipeStepInstrumentCreationRequestInput", FromField("Instruments")),
				"PreparationID":        NestedID("Preparation"),
				"Products":             MapSlice("ConvertRecipeStepProductToRecipeStepProductCreationRequestInput", FromField("Products")),
				"Vessels":              MapSlice("ConvertRecipeStepVesselToRecipeStepVesselCreationRequestInput", FromField("Vessels")),
			},
		},
		{Name: "ConvertRecipeStepToRecipeStepDatabaseCreationInput", From: Param{Name: "recipeStep", Type: "RecipeStep"}, To: "RecipeStepDatabaseCreationInput",
			Fields: map[string]Rule{
				"CompletionConditions": MapSlice("ConvertRecipeStepCompletionConditionToRecipeStepCompletionConditionDatabaseCreationInput", FromField("CompletionConditions")),
				"Ingredients":          MapSlice("ConvertRecipeStepIngredientToRecipeStepIngredientDatabaseCreationInput", FromField("Ingredients")),
				"Instruments":          MapSlice("ConvertRecipeStepInstrumentToRecipeStepInstrumentDatabaseCreationInput", FromField("Instruments")),
				"PreparationID":        NestedID("Preparation"),
				"Products":             MapSlice("ConvertRecipeStepProductToRecipeStepProductDatabaseCreationInput", FromField("Products")),
				"Vessels":              MapSlice("ConvertRecipeStepVesselToRecipeStepVesselDatabaseCreationInput", FromField("Vessels")),
			},
		},
		{Name: "ConvertRecipeToRecipeUpdateRequestInput", From: Param{Name: "input", Type: "Recipe"}, To: "RecipeUpdateRequestInput"},
		{Name: "ConvertRecipeToRecipeCreationRequestInput", From: Param{Name: "input", Type: "Recipe"}, To: "RecipeCreationRequestInput",
			Fields: map[string]Rule{
				"AlsoCreateMeal": Skip("A request-time instruction to create a meal alongside the recipe, not a property of the recipe that resulted."),
				"PrepTasks":      MapSlice("ConvertRecipePrepTaskToRecipePrepTaskWithinRecipeCreationRequestInput", FromField("PrepTasks"), WithArgs("input", "item")),
				"Steps":          MapSlice("ConvertRecipeStepToRecipeStepCreationRequestInput", FromField("Steps")),
			},
		},
		{Name: "ConvertRecipeToRecipeDatabaseCreationInput", From: Param{Name: "input", Type: "Recipe"}, To: "RecipeDatabaseCreationInput",
			Fields: map[string]Rule{
				"AlsoCreateMeal":     Skip("A request-time instruction, not a property of the recipe; see the request-input converter."),
				"ClonedFromRecipeID": Skip("Set by the clone path, which is the only caller that knows what was cloned. A recipe read back does not record it."),
				"PrepTasks":          MapSlice("ConvertRecipePrepTaskToRecipePrepTaskDatabaseCreationInput", FromField("PrepTasks")),
				"Steps":              MapSlice("ConvertRecipeStepToRecipeStepDatabaseCreationInput", FromField("Steps")),
			},
		},
		{Name: "ConvertUserIngredientPreferenceToUserIngredientPreferenceUpdateRequestInput", From: Param{Name: "input", Type: "UserIngredientPreference"}, To: "UserIngredientPreferenceUpdateRequestInput",
			Fields: map[string]Rule{
				"IngredientID": NestedID("Ingredient"),
			},
		},
		{Name: "ConvertUserIngredientPreferenceCreationRequestInputToUserIngredientPreferenceDatabaseCreationInput", From: Param{Name: "input", Type: "UserIngredientPreferenceCreationRequestInput"}, To: "UserIngredientPreferenceDatabaseCreationInput",
			Fields: map[string]Rule{
				"CreatedByUser": Skip("Comes from the session rather than the request body, so the manager stamps it after this."),
			},
		},
		{Name: "ConvertUserIngredientPreferenceToUserIngredientPreferenceCreationRequestInput", From: Param{Name: "x", Type: "UserIngredientPreference"}, To: "UserIngredientPreferenceCreationRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientGroupID": Skip("A preference is stored against one ingredient, whether it was expressed against a group or not, so the group it came from is not recoverable from it."),
				"ValidIngredientID":      NestedID("Ingredient"),
			},
		},
		{Name: "ConvertUserIngredientPreferenceToUserIngredientPreferenceDatabaseCreationInput", From: Param{Name: "x", Type: "UserIngredientPreference"}, To: "UserIngredientPreferenceDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidIngredientGroupID": Skip("Not recoverable from a stored preference; see the request-input converter."),
				"ValidIngredientID":      NestedID("Ingredient"),
			},
		},
		{Name: "ConvertValidIngredientGroupToValidIngredientGroupUpdateRequestInput", From: Param{Name: "input", Type: "ValidIngredientGroup"}, To: "ValidIngredientGroupUpdateRequestInput"},
		{Name: "ConvertValidIngredientGroupToValidIngredientGroupCreationRequestInput", From: Param{Name: "validIngredient", Type: "ValidIngredientGroup"}, To: "ValidIngredientGroupCreationRequestInput",
			Fields: map[string]Rule{
				"Members": Skip("ValidIngredientGroup carries its members in their stored shape and the converter this replaced did not map them back to request inputs. Preserved rather than corrected, so that generating these converters is not also a behavior change."),
			},
		},
		{Name: "ConvertValidIngredientMeasurementUnitToValidIngredientMeasurementUnitUpdateRequestInput", From: Param{Name: "input", Type: "ValidIngredientMeasurementUnit"}, To: "ValidIngredientMeasurementUnitUpdateRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":      NestedID("Ingredient"),
				"ValidMeasurementUnitID": NestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertValidIngredientMeasurementUnitCreationRequestInputToValidIngredientMeasurementUnitDatabaseCreationInput", From: Param{Name: "input", Type: "ValidIngredientMeasurementUnitCreationRequestInput"}, To: "ValidIngredientMeasurementUnitDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidIngredientMeasurementUnitToValidIngredientMeasurementUnitCreationRequestInput", From: Param{Name: "validIngredientMeasurementUnit", Type: "ValidIngredientMeasurementUnit"}, To: "ValidIngredientMeasurementUnitCreationRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":      NestedID("Ingredient"),
				"ValidMeasurementUnitID": NestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertValidIngredientMeasurementUnitToValidIngredientMeasurementUnitDatabaseCreationInput", From: Param{Name: "validIngredientMeasurementUnit", Type: "ValidIngredientMeasurementUnit"}, To: "ValidIngredientMeasurementUnitDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidIngredientID":      NestedID("Ingredient"),
				"ValidMeasurementUnitID": NestedID("MeasurementUnit"),
			},
		},
		{Name: "ConvertValidIngredientPreparationCreationRequestInputToValidIngredientPreparationDatabaseCreationInput", From: Param{Name: "input", Type: "ValidIngredientPreparationCreationRequestInput"}, To: "ValidIngredientPreparationDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidIngredientPreparationToValidIngredientPreparationUpdateRequestInput", From: Param{Name: "validIngredientPreparation", Type: "ValidIngredientPreparation"}, To: "ValidIngredientPreparationUpdateRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":  NestedID("Ingredient"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidIngredientPreparationToValidIngredientPreparationCreationRequestInput", From: Param{Name: "validIngredientPreparation", Type: "ValidIngredientPreparation"}, To: "ValidIngredientPreparationCreationRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":  NestedID("Ingredient"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidIngredientPreparationToValidIngredientPreparationDatabaseCreationInput", From: Param{Name: "validIngredientPreparation", Type: "ValidIngredientPreparation"}, To: "ValidIngredientPreparationDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidIngredientID":  NestedID("Ingredient"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidIngredientStateIngredientCreationRequestInputToValidIngredientStateIngredientDatabaseCreationInput", From: Param{Name: "input", Type: "ValidIngredientStateIngredientCreationRequestInput"}, To: "ValidIngredientStateIngredientDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidIngredientStateIngredientToValidIngredientStateIngredientUpdateRequestInput", From: Param{Name: "validIngredientStateIngredient", Type: "ValidIngredientStateIngredient"}, To: "ValidIngredientStateIngredientUpdateRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":      NestedID("Ingredient"),
				"ValidIngredientStateID": NestedID("IngredientState"),
			},
		},
		{Name: "ConvertValidIngredientStateIngredientToValidIngredientStateIngredientCreationRequestInput", From: Param{Name: "validIngredientStateIngredient", Type: "ValidIngredientStateIngredient"}, To: "ValidIngredientStateIngredientCreationRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":      NestedID("Ingredient"),
				"ValidIngredientStateID": NestedID("IngredientState"),
			},
		},
		{Name: "ConvertValidIngredientStateIngredientToValidIngredientStateIngredientDatabaseCreationInput", From: Param{Name: "validIngredientStateIngredient", Type: "ValidIngredientStateIngredient"}, To: "ValidIngredientStateIngredientDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidIngredientID":      NestedID("Ingredient"),
				"ValidIngredientStateID": NestedID("IngredientState"),
			},
		},
		{Name: "ConvertValidIngredientStateToValidIngredientStateUpdateRequestInput", From: Param{Name: "input", Type: "ValidIngredientState"}, To: "ValidIngredientStateUpdateRequestInput"},
		{Name: "ConvertValidIngredientStateCreationRequestInputToValidIngredientStateDatabaseCreationInput", From: Param{Name: "input", Type: "ValidIngredientStateCreationRequestInput"}, To: "ValidIngredientStateDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidIngredientStateToValidIngredientStateCreationRequestInput", From: Param{Name: "validIngredientState", Type: "ValidIngredientState"}, To: "ValidIngredientStateCreationRequestInput"},
		{Name: "ConvertValidIngredientStateToValidIngredientStateDatabaseCreationInput", From: Param{Name: "validIngredientState", Type: "ValidIngredientState"}, To: "ValidIngredientStateDatabaseCreationInput"},
		{Name: "ConvertValidIngredientToValidIngredientUpdateRequestInput", From: Param{Name: "x", Type: "ValidIngredient"}, To: "ValidIngredientUpdateRequestInput"},
		{Name: "ConvertValidIngredientCreationRequestInputToValidIngredientDatabaseCreationInput", From: Param{Name: "x", Type: "ValidIngredientCreationRequestInput"}, To: "ValidIngredientDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidIngredientToValidIngredientCreationRequestInput", From: Param{Name: "x", Type: "ValidIngredient"}, To: "ValidIngredientCreationRequestInput"},
		{Name: "ConvertValidIngredientToValidIngredientDatabaseCreationInput", From: Param{Name: "x", Type: "ValidIngredient"}, To: "ValidIngredientDatabaseCreationInput"},
		{Name: "ConvertValidInstrumentToValidInstrumentUpdateRequestInput", From: Param{Name: "input", Type: "ValidInstrument"}, To: "ValidInstrumentUpdateRequestInput"},
		{Name: "ConvertValidInstrumentCreationRequestInputToValidInstrumentDatabaseCreationInput", From: Param{Name: "input", Type: "ValidInstrumentCreationRequestInput"}, To: "ValidInstrumentDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertNullableValidInstrumentToValidInstrument", From: Param{Name: "x", Type: "NullableValidInstrument"}, To: "ValidInstrument",
			Fields: map[string]Rule{
				"CreatedAt":                      Deref("Reads through without a guard, which asserts the join matched."),
				"Description":                    Deref("Reads through without a guard, which asserts the join matched."),
				"DisplayInSummaryLists":          Deref("Reads through without a guard, which asserts the join matched."),
				"ID":                             Deref("Reads through without a guard, which asserts the join matched."),
				"IconPath":                       Deref("Reads through without a guard, which asserts the join matched."),
				"IncludeInGeneratedInstructions": Deref("Reads through without a guard, which asserts the join matched."),
				"Name":                           Deref("Reads through without a guard, which asserts the join matched."),
				"PluralName":                     Deref("Reads through without a guard, which asserts the join matched."),
				"Slug":                           Deref("Reads through without a guard, which asserts the join matched."),
				"UsableForStorage":               Deref("Reads through without a guard, which asserts the join matched."),
			},
		},
		{Name: "ConvertValidInstrumentToValidInstrumentCreationRequestInput", From: Param{Name: "validInstrument", Type: "ValidInstrument"}, To: "ValidInstrumentCreationRequestInput"},
		{Name: "ConvertValidInstrumentToValidInstrumentDatabaseCreationInput", From: Param{Name: "validInstrument", Type: "ValidInstrument"}, To: "ValidInstrumentDatabaseCreationInput"},
		{Name: "ConvertValidMeasurementUnitConversionToValidMeasurementUnitConversionUpdateRequestInput", From: Param{Name: "input", Type: "ValidMeasurementUnitConversion"}, To: "ValidMeasurementUnitConversionUpdateRequestInput",
			Fields: map[string]Rule{
				"From":              NestedID("From"),
				"OnlyForIngredient": OptionalNestedID("OnlyForIngredient"),
				"To":                NestedID("To"),
			},
		},
		{Name: "ConvertValidMeasurementUnitConversionCreationRequestInputToValidMeasurementUnitConversionDatabaseCreationInput", From: Param{Name: "input", Type: "ValidMeasurementUnitConversionCreationRequestInput"}, To: "ValidMeasurementUnitConversionDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidMeasurementUnitConversionToValidMeasurementUnitConversionCreationRequestInput", From: Param{Name: "validMeasurementUnitConversion", Type: "ValidMeasurementUnitConversion"}, To: "ValidMeasurementUnitConversionCreationRequestInput",
			Fields: map[string]Rule{
				"From":              NestedID("From"),
				"OnlyForIngredient": OptionalNestedID("OnlyForIngredient"),
				"To":                NestedID("To"),
			},
		},
		{Name: "ConvertValidMeasurementUnitConversionToValidMeasurementUnitConversionDatabaseCreationInput", From: Param{Name: "validMeasurementUnitConversion", Type: "ValidMeasurementUnitConversion"}, To: "ValidMeasurementUnitConversionDatabaseCreationInput",
			Fields: map[string]Rule{
				"From":              NestedID("From"),
				"OnlyForIngredient": OptionalNestedID("OnlyForIngredient"),
				"To":                NestedID("To"),
			},
		},
		{Name: "ConvertValidMeasurementUnitToValidMeasurementUnitUpdateRequestInput", From: Param{Name: "input", Type: "ValidMeasurementUnit"}, To: "ValidMeasurementUnitUpdateRequestInput"},
		{Name: "ConvertValidMeasurementUnitCreationRequestInputToValidMeasurementUnitDatabaseCreationInput", From: Param{Name: "input", Type: "ValidMeasurementUnitCreationRequestInput"}, To: "ValidMeasurementUnitDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidMeasurementUnitToValidMeasurementUnitCreationRequestInput", From: Param{Name: "validMeasurementUnit", Type: "ValidMeasurementUnit"}, To: "ValidMeasurementUnitCreationRequestInput"},
		{Name: "ConvertValidMeasurementUnitToValidMeasurementUnitDatabaseCreationInput", From: Param{Name: "validMeasurementUnit", Type: "ValidMeasurementUnit"}, To: "ValidMeasurementUnitDatabaseCreationInput"},
		{Name: "ConvertValidMeasurementUnitToNullableValidMeasurementUnit", From: Param{Name: "input", Type: "ValidMeasurementUnit"}, To: "NullableValidMeasurementUnit"},
		{Name: "ConvertValidPrepTaskConfigCreationRequestInputToValidPrepTaskConfigDatabaseCreationInput", From: Param{Name: "input", Type: "ValidPrepTaskConfigCreationRequestInput"}, To: "ValidPrepTaskConfigDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidPrepTaskConfigToValidPrepTaskConfigUpdateRequestInput", From: Param{Name: "validPrepTaskConfig", Type: "ValidPrepTaskConfig"}, To: "ValidPrepTaskConfigUpdateRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":  NestedID("Ingredient"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidPrepTaskConfigToValidPrepTaskConfigCreationRequestInput", From: Param{Name: "validPrepTaskConfig", Type: "ValidPrepTaskConfig"}, To: "ValidPrepTaskConfigCreationRequestInput",
			Fields: map[string]Rule{
				"ValidIngredientID":  NestedID("Ingredient"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidPrepTaskConfigToValidPrepTaskConfigDatabaseCreationInput", From: Param{Name: "validPrepTaskConfig", Type: "ValidPrepTaskConfig"}, To: "ValidPrepTaskConfigDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidIngredientID":  NestedID("Ingredient"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidPreparationInstrumentCreationRequestInputToValidPreparationInstrumentDatabaseCreationInput", From: Param{Name: "input", Type: "ValidPreparationInstrumentCreationRequestInput"}, To: "ValidPreparationInstrumentDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidPreparationInstrumentToValidPreparationInstrumentUpdateRequestInput", From: Param{Name: "validPreparationInstrument", Type: "ValidPreparationInstrument"}, To: "ValidPreparationInstrumentUpdateRequestInput",
			Fields: map[string]Rule{
				"ValidInstrumentID":  NestedID("Instrument"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidPreparationInstrumentToValidPreparationInstrumentCreationRequestInput", From: Param{Name: "validPreparationInstrument", Type: "ValidPreparationInstrument"}, To: "ValidPreparationInstrumentCreationRequestInput",
			Fields: map[string]Rule{
				"ValidInstrumentID":  NestedID("Instrument"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidPreparationInstrumentToValidPreparationInstrumentDatabaseCreationInput", From: Param{Name: "validPreparationInstrument", Type: "ValidPreparationInstrument"}, To: "ValidPreparationInstrumentDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidInstrumentID":  NestedID("Instrument"),
				"ValidPreparationID": NestedID("Preparation"),
			},
		},
		{Name: "ConvertValidPreparationVesselCreationRequestInputToValidPreparationVesselDatabaseCreationInput", From: Param{Name: "x", Type: "ValidPreparationVesselCreationRequestInput"}, To: "ValidPreparationVesselDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidPreparationVesselToValidPreparationVesselUpdateRequestInput", From: Param{Name: "x", Type: "ValidPreparationVessel"}, To: "ValidPreparationVesselUpdateRequestInput",
			Fields: map[string]Rule{
				"ValidPreparationID": NestedID("Preparation"),
				"ValidVesselID":      NestedID("Vessel"),
			},
		},
		{Name: "ConvertValidPreparationVesselToValidPreparationVesselCreationRequestInput", From: Param{Name: "x", Type: "ValidPreparationVessel"}, To: "ValidPreparationVesselCreationRequestInput",
			Fields: map[string]Rule{
				"ValidPreparationID": NestedID("Preparation"),
				"ValidVesselID":      NestedID("Vessel"),
			},
		},
		{Name: "ConvertValidPreparationVesselToValidPreparationVesselDatabaseCreationInput", From: Param{Name: "x", Type: "ValidPreparationVessel"}, To: "ValidPreparationVesselDatabaseCreationInput",
			Fields: map[string]Rule{
				"ValidPreparationID": NestedID("Preparation"),
				"ValidVesselID":      NestedID("Vessel"),
			},
		},
		{Name: "ConvertValidPreparationToValidPreparationUpdateRequestInput", From: Param{Name: "input", Type: "ValidPreparation"}, To: "ValidPreparationUpdateRequestInput"},
		{Name: "ConvertValidPreparationCreationRequestInputToValidPreparationDatabaseCreationInput", From: Param{Name: "input", Type: "ValidPreparationCreationRequestInput"}, To: "ValidPreparationDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidPreparationToValidPreparationCreationRequestInput", From: Param{Name: "validPreparation", Type: "ValidPreparation"}, To: "ValidPreparationCreationRequestInput"},
		{Name: "ConvertValidPreparationToValidPreparationDatabaseCreationInput", From: Param{Name: "validPreparation", Type: "ValidPreparation"}, To: "ValidPreparationDatabaseCreationInput"},
		{Name: "ConvertValidVesselToValidVesselUpdateRequestInput", From: Param{Name: "x", Type: "ValidVessel"}, To: "ValidVesselUpdateRequestInput",
			Fields: map[string]Rule{
				"CapacityUnitID": NestedID("CapacityUnit"),
			},
		},
		{Name: "ConvertValidVesselCreationRequestInputToValidVesselDatabaseCreationInput", From: Param{Name: "x", Type: "ValidVesselCreationRequestInput"}, To: "ValidVesselDatabaseCreationInput",
			Fields: map[string]Rule{
				"ID": NewID(),
			},
		},
		{Name: "ConvertValidVesselToValidVesselCreationRequestInput", From: Param{Name: "x", Type: "ValidVessel"}, To: "ValidVesselCreationRequestInput",
			Fields: map[string]Rule{
				"CapacityUnitID": OptionalNestedID("CapacityUnit"),
			},
		},
		{Name: "ConvertValidVesselToValidVesselDatabaseCreationInput", From: Param{Name: "x", Type: "ValidVessel"}, To: "ValidVesselDatabaseCreationInput",
			Fields: map[string]Rule{
				"CapacityUnitID": OptionalNestedID("CapacityUnit"),
			},
		},
	})
}
