package main

// fieldExceptions are the destination fields no convention answers, keyed by conversion and then
// by field.
//
// Every entry is a fact about the domain rather than about Go: which fields a caller fills in
// after the conversion, which are not recoverable from the source at all. The reason is required
// and is rendered into the generated source, so a reader of the output meets it where the field
// would have been.
var fieldExceptions = map[string]map[string]Rule{
	"ConvertAccountCreationRequestInputToAccountDatabaseCreationInput": {
		"WebhookEncryptionKey": Skip("The HMAC key an account signs its webhook deliveries with. It is generated for the account rather than requested, and the repository writes it as webhook_hmac_secret."),
	},
	"ConvertAccountInstrumentOwnershipCreationRequestInputToAccountInstrumentOwnershipDatabaseCreationInput": {
		"BelongsToAccount": Skip(ownerFromSession),
	},
	"ConvertIssueReportCreationRequestInputToIssueReportDatabaseCreationInput": {
		"CreatedByUser":    Skip(ownerFromSession),
		"BelongsToAccount": Skip(ownerFromSession),
	},
	"ConvertOAuth2ClientCreationRequestInputToOAuth2ClientDatabaseCreationInput": {
		"ClientID":     Skip("Generated by the manager from the secret generator, never taken from the request: a client that could choose its own ID could choose another client's."),
		"ClientSecret": Skip("Generated by the manager and stored only as its SHA-256 digest; the plaintext is returned to the caller exactly once."),
	},
	"ConvertPasswordResetTokenToPasswordResetTokenCreationRequestInput": {
		"EmailAddress": Skip("A reset is requested by email address and a token is issued against a user ID. The token does not record which address asked for it."),
	},
	"ConvertServiceSettingConfigurationCreationRequestInputToServiceSettingConfigurationDatabaseCreationInput": {
		"BelongsToUser":    Skip(ownerFromSession),
		"BelongsToAccount": Skip(ownerFromSession),
	},
	"ConvertUploadedMediaCreationRequestInputToUploadedMediaDatabaseCreationInput": {
		"CreatedByUser": Skip(ownerFromSession),
	},
	"ConvertAccountUserMembershipToAccountUserMembershipDatabaseCreationInput": {
		"UserID":    Expr("x.BelongsToUser", "The membership names its user as BelongsToUser; the row that creates one calls the same thing UserID."),
		"AccountID": Expr("x.BelongsToAccount", "The membership names its account as BelongsToAccount; the row that creates one calls the same thing AccountID."),
		"Reason":    Skip("The reason a membership was granted is supplied by whoever grants it. A membership read back does not carry one."),
		"ID":        NewID("A membership row created from an existing membership is a new grant, not the same one moved, so it gets its own identifier."),
	},
	"ConvertMealCreationRequestInputToMealDatabaseCreationInput": {
		"CreatedByUser": Skip(ownerFromSession),
	},
	"ConvertMealListCreationRequestInputToMealListDatabaseCreationInput": {
		"BelongsToUser": Skip(ownerFromSession),
	},
	"ConvertMealListItemCreationRequestInputToMealListItemDatabaseCreationInput": {
		"BelongsToMealList": Skip(parentStampedByCaller),
	},
	"ConvertMealPlanEventCreationRequestInputToMealPlanEventDatabaseCreationInput": {
		"BelongsToMealPlan": Skip(parentStampedByCaller),
	},
	"ConvertMealPlanGroceryListItemCreationRequestInputToMealPlanGroceryListItemDatabaseCreationInput": {
		"BelongsToMealPlanOption": Skip(groceryProvenance),
		"OptionIndex":             Skip(groceryProvenance),
		"IngredientIndex":         Skip(groceryProvenance),
		"RecipeStepID":            Skip(groceryProvenance),
		"RecipeID":                Skip(groceryProvenance),
	},
	"ConvertMealPlanGroceryListItemToMealPlanGroceryListItemCreationRequestInput": {
		"ValidMeasurementUnitID": Expr("x.MeasurementUnit.ID", ambiguousMeasurementUnit),
	},
	"ConvertMealPlanGroceryListItemToMealPlanGroceryListItemDatabaseCreationInput": {
		"ValidMeasurementUnitID": Expr("x.MeasurementUnit.ID", ambiguousMeasurementUnit),
	},
	"ConvertMealPlanGroceryListItemToMealPlanGroceryListItemUpdateRequestInput": {
		"ValidMeasurementUnitID": Expr("&x.MeasurementUnit.ID", ambiguousMeasurementUnit),
	},
	"ConvertMealPlanOptionCreationRequestInputToMealPlanOptionDatabaseCreationInput": {
		"BelongsToMealPlanEvent": Skip(parentStampedByCaller),
	},
	"ConvertMealPlanOptionToMealPlanOptionCreationRequestInput": {
		"Selections": Skip("A stored MealPlanOption does not carry the recipe selections made against it; they are read from the meal plan."),
	},
	"ConvertMealPlanRecipeOptionSelectionCreationRequestInputToMealPlanRecipeOptionSelectionDatabaseCreationInput": {
		"BelongsToMealPlanOption": Skip(parentStampedByCaller),
	},
	"ConvertOAuth2ClientTokenToOAuth2ClientTokenDatabaseCreationInput": {
		"CodeExpiresIn":    Expr("x.CodeExpiresAt", tokenExpiryRenamed),
		"AccessExpiresIn":  Expr("x.AccessExpiresAt", tokenExpiryRenamed),
		"RefreshExpiresIn": Expr("x.RefreshExpiresAt", tokenExpiryRenamed),
	},
	"ConvertRecipePrepTaskStepToRecipePrepTaskStepUpdateRequestInput": {
		"BelongsToRecipeStep":     Expr("new(x.BelongsToRecipeStep)", pointsAtACopy),
		"BelongsToRecipePrepTask": Expr("new(x.BelongsToRecipePrepTask)", pointsAtACopy),
		"SatisfiesRecipeStep":     Expr("new(x.SatisfiesRecipeStep)", pointsAtACopy),
	},
	"ConvertPasswordResetTokenCreationRequestInputToPasswordResetTokenDatabaseCreationInput": {
		"Token":         Skip("The token is generated by the manager. A request that could name its own would be a request that could name somebody else's."),
		"BelongsToUser": Skip("The user is resolved from the email address the request carries, which is a lookup rather than a copy."),
		"ExpiresAt":     Skip("The lifetime is the manager's policy, not the requester's."),
	},
	"ConvertRecipeListCreationRequestInputToRecipeListDatabaseCreationInput": {
		"BelongsToUser": Skip(ownerFromSession),
	},
	"ConvertRecipeListItemCreationRequestInputToRecipeListItemDatabaseCreationInput": {
		"BelongsToRecipeList": Skip(parentStampedByCaller),
	},
	"ConvertRecipePrepTaskStepCreationRequestInputToRecipePrepTaskStepDatabaseCreationInput": {
		"BelongsToRecipePrepTask": Skip(parentStampedByCaller),
	},
	"ConvertRecipePrepTaskToRecipePrepTaskCreationRequestInput": {
		"RecipeSteps": MapSlice("TaskSteps", "ConvertRecipePrepTaskStepToRecipePrepTaskStepCreationRequestInput",
			"The prep task calls its steps TaskSteps and the request input calls them RecipeSteps."),
	},
	"ConvertRecipeStepIngredientToRecipeStepIngredientDatabaseCreationInput": {
		"ProductOfRecipeStepIndex":         Skip(recipeCreationIndex),
		"ProductOfRecipeStepProductIndex":  Skip(recipeCreationIndex),
		"ValidIngredientPreparationID":     Skip(bridgeRowID),
		"ValidIngredientMeasurementUnitID": Skip(bridgeRowID),
		"ScaleFactor":                      Expr("scaleFactorOrDefault(x.ScaleFactor)", scaleFactorDefaulted),
	},
	"ConvertRecipeStepInstrumentToRecipeStepInstrumentDatabaseCreationInput": {
		"ProductOfRecipeStepIndex":        Skip(recipeCreationIndex),
		"ProductOfRecipeStepProductIndex": Skip(recipeCreationIndex),
		"ValidPreparationInstrumentID":    Skip(bridgeRowID),
		"ScaleFactor":                     Expr("scaleFactorOrDefault(x.ScaleFactor)", scaleFactorDefaulted),
	},
	"ConvertRecipeStepVesselToRecipeStepVesselDatabaseCreationInput": {
		"ProductOfRecipeStepIndex":        Skip(recipeCreationIndex),
		"ProductOfRecipeStepProductIndex": Skip(recipeCreationIndex),
		"ValidPreparationVesselID":        Skip(bridgeRowID),
		"ScaleFactor":                     Expr("scaleFactorOrDefault(x.ScaleFactor)", scaleFactorDefaulted),
	},
	"ConvertRecipeToRecipeDatabaseCreationInput": {
		"ClonedFromRecipeID": Skip("Set by the clone path, which is the only caller that knows what was cloned. A recipe read back does not record it."),
		"AlsoCreateMeal":     Skip(alsoCreateMeal),
	},
	"ConvertUserIngredientPreferenceCreationRequestInputToUserIngredientPreferenceDatabaseCreationInput": {
		"CreatedByUser": Skip(ownerFromSession),
	},
	"ConvertUserIngredientPreferenceToUserIngredientPreferenceCreationRequestInput": {
		"ValidIngredientGroupID": Skip(preferenceGroup),
	},
	"ConvertUserIngredientPreferenceToUserIngredientPreferenceDatabaseCreationInput": {
		"ValidIngredientGroupID": Skip(preferenceGroup),
	},
	"ConvertValidIngredientGroupToValidIngredientGroupCreationRequestInput": {
		"Members": Skip("A stored group carries its members as rows that already name the ingredients they point at. Mapping them back into a creation request would make the request name ingredients the caller never asked to group, so the converter this replaced left them out and this one does too."),
	},
	"ConvertUserToUserDatabaseCreationInput": {
		"AcceptedTOS":           Skip("Registration input. A stored User records neither the acceptance nor when it happened."),
		"AcceptedPrivacyPolicy": Skip("Registration input; see AcceptedTOS."),
		"AccountName":           Skip("Names the household account created alongside the user. It belongs to the registration request, not to the user it created."),
		"DestinationAccountID":  Skip("Set only when the registration is redeeming an invitation; a stored User does not record which one."),
		"InvitationToken":       Skip("The invitation being redeemed, consumed during registration and not kept on the user."),
	},
	"ConvertWebhookToWebhookCreationRequestInput": {
		"Events": Expr("x.EventTypes()", "A request lists event types; a webhook stores one trigger config per subscription. EventTypes flattens the configs back to the strings they subscribe to."),
	},
}

// ownerFromSession is the same fact about half a dozen entities: who owns a row is established by
// the authenticated session, and a request body that could name it would be a request body that
// could name somebody else.
const (
	ownerFromSession         = "Comes from the authenticated session rather than the request body, so the manager stamps it after this."
	parentStampedByCaller    = "The parent does not exist yet when a request is parsed, so whoever mints its ID stamps this."
	groceryProvenance        = "Provenance the grocery list generator records — which option, which recipe, which step an item came from. An item created by hand has none of it."
	recipeCreationIndex      = "An index into the recipe being created, resolved to an ID once it is. A stored step has the ID and no longer the index."
	bridgeRowID              = "The bridge-table row this step was built from. A stored step keeps the entity it resolved to, not the row that justified it."
	alsoCreateMeal           = "A request-time instruction to create a meal alongside the recipe, not a property of the recipe that resulted."
	preferenceGroup          = "A preference is stored against one ingredient, whether it was expressed against a group or not, so the group it came from is not recoverable."
	tokenExpiryRenamed       = "The token records when it expires and the row that creates one records the same instant under an In name."
	pointsAtACopy            = "Points at a copy rather than at the entity's own field, so amending the update input cannot write back through to what it was built from."
	scaleFactorDefaulted     = "Zero means unset on the wire and one in the database, and scaleFactorOrDefault is where that is decided."
	ambiguousMeasurementUnit = "MealPlanGroceryListItem holds two measurement units — the one called for and the one purchased — so which of them an unqualified ValidMeasurementUnitID means has to be said."
)

// handWritten are the conversions this tool does not generate, and why.
//
// Each stays in its domain's converters_manual.go. The bar is that the body is not a set of field
// assignments — it fails, it fans one value out into many, it defaults something, it returns nil
// for nil. A conversion that is a field copy with a handful of exceptions does not belong here;
// it belongs above, where the generator still guarantees no field is silently dropped.
var handWritten = map[string]string{
	"ConvertAccountInvitationCreationRequestInputToAccountInvitationDatabaseCreationInput":                         "An invitation with no expiry given is given one in the year 9999, and the inviter, the destination account and the token all come from the caller.",
	"ConvertMealPlanCreationRequestInputToMealPlanDatabaseCreationInput":                                           "It builds each recipe option selection inline, minting an ID per row and leaving the owning option for a later pass.",
	"ConvertMealPlanEventToMealPlanEventCreationRequestInput":                                                      "It stamps the event's ID onto each option of the entity it was handed before converting it, which mutates its own argument.",
	"ConvertMealPlanOptionVoteToMealPlanOptionVoteCreationRequestInput":                                            "It wraps one vote in the one-element slice the batch input expects, building the element inline.",
	"ConvertMealPlanOptionVoteCreationRequestInputToMealPlanOptionVoteDatabaseCreationInput":                       "The request input is a batch of votes and the database input is one, so this is a fan-in rather than a conversion between two shapes of the same thing.",
	"ConvertRecipeStepToRecipeStepCreationRequestInput":                                                            "Its completion conditions are converted against the step as well as themselves, so their ingredients can be named by position.",
	"ConvertRecipeToRecipeCreationRequestInput":                                                                    "Each prep task is converted against the recipe as well as itself, so its steps can be named by position rather than by an ID the request has no way to know.",
	"ConvertRecipeStepCompletionConditionCreationRequestInputToRecipeStepCompletionConditionDatabaseCreationInput": "Its ingredients are positions within the step being created, so it needs that step as well as the condition.",
	"ConvertRecipeCreationRequestInputToRecipeDatabaseCreationInput":                                               "Converting a prep task can fail, so this returns an error rather than a value.",
	"ConvertRecipePrepTaskCreationRequestInputToRecipePrepTaskDatabaseCreationInput":                               "It builds each task step inline, minting an ID for each.",
	"ConvertRecipePrepTaskToRecipePrepTaskUpdateRequestInput":                                                      "It builds each task step's update input from the address of a per-iteration copy rather than of the entity's own field.",
	"ConvertRecipeStepCompletionConditionToRecipeStepCompletionConditionCreationRequestInput":                      "It turns ingredient IDs back into positions by searching the step's ingredients, which needs the step as well as the condition.",
	"ConvertRecipeStepCompletionConditionToRecipeStepCompletionConditionDatabaseCreationInput":                     "It builds each condition ingredient inline rather than through a converter.",
	"ConvertRecipeStepCreationRequestInputToRecipeStepDatabaseCreationInput":                                       "It mints the step's ID and converts five child collections against it, re-minting each child's ID and stamping the step's own.",
	"ConvertRecipeStepIngredientCreationRequestInputToRecipeStepIngredientDatabaseCreationInput":                   indexDefaulted,
	"ConvertRecipeStepInstrumentCreationRequestInputToRecipeStepInstrumentDatabaseCreationInput":                   indexDefaulted,
	"ConvertRecipeStepVesselCreationRequestInputToRecipeStepVesselDatabaseCreationInput":                           indexDefaulted,
	"ConvertRecipeStepIngredientToRecipeStepIngredientCreationRequestInput":                                        indexNilledWhenZero,
	"ConvertRecipeStepInstrumentToRecipeStepInstrumentCreationRequestInput":                                        indexNilledWhenZero,
	"ConvertRecipeStepVesselToRecipeStepVesselCreationRequestInput":                                                indexNilledWhenZero,
	"ConvertRecipeStepProductCreationRequestInputToRecipeStepProductDatabaseCreationInput":                         returnsNilForNil,
	"ConvertRecipeStepProductToRecipeStepProductUpdateRequestInput":                                                returnsNilForNil,
	"ConvertValidIngredientGroupCreationRequestInputToValidIngredientGroupDatabaseCreationInput":                   inlineGroupMembers,
	"ConvertValidIngredientGroupToValidIngredientGroupDatabaseCreationInput":                                       inlineGroupMembers,
	"ConvertWebhookCreationRequestInputToWebhookDatabaseCreationInput":                                             "It fans a flat list of event types out into one trigger config apiece, minting an ID for each and stamping the webhook's own.",
}

const (
	indexDefaulted      = "The array index it is handed is a fallback for an index the request may omit, which is a defaulting rule rather than a copy."
	indexNilledWhenZero = "An index of zero becomes nil, so that recipe creation fills it from the element's position instead."
	returnsNilForNil    = "It returns nil for a nil input rather than dereferencing one."
	inlineGroupMembers  = "It builds each member row inline, minting an ID and stamping the group's own."
)
