package main

import (
	goerrors "errors"
	"fmt"
	"go/format"
	"regexp"
	"slices"
	"strings"

	"github.com/primandproper/primitives-go/v2/errors"
)

// grpcImports are the packages a generated gRPC converter can name, by the qualifier it names them
// with. One spelling per package: the corpus this replaced imported the message package as both
// mealplanningsvc and mealplanninggrpc, and the shared helpers as both grpcconverters and
// converters, depending on which file a converter happened to live in.
var grpcImports = map[string]string{
	grpcDomain:            fmt.Sprintf(domainImportPath, grpcDomain),
	grpcMessagesQualifier: "github.com/primandproper/dinnerdonebetter/backend/internal/grpc/generated/services/mealplanning",
	"converters":          "github.com/primandproper/dinnerdonebetter/backend/internal/grpc/converters",
	"mediaregistrygrpc":   "github.com/primandproper/platform-go/v15/mediaregistry/grpc",
	"mediaregistrypb":     "github.com/primandproper/platform-go/v15/mediaregistry/mediaregistrypb",
	"pointer":             "github.com/primandproper/primitives-go/v2/pointer",
}

// grpcImportAliases are the qualifiers that are not their package's declared name, and so have to
// be written as an alias.
var grpcImportAliases = map[string]struct{}{
	grpcMessagesQualifier: {},
	"converters":          {},
	"mediaregistrygrpc":   {},
}

// generateGRPC enumerates, plans and renders the gRPC converters.
func generateGRPC(root string, domainIndex *structIndex) ([]byte, error) {
	index, err := buildGRPCIndex(root, domainIndex)
	if err != nil {
		return nil, err
	}

	declarations := grpcConversionList()
	resolver := newGRPCPlanner(index, declarations)

	var (
		plans     []*plan
		docs      = map[string]string{}
		unplanned []error
	)

	for _, declared := range declarations {
		if _, manual := grpcHandWritten[declared.Name()]; manual {
			continue
		}

		resolved, planErr := resolver.Plan(declared, grpcFieldExceptions[declared.Name()])
		if planErr != nil {
			unplanned = append(unplanned, planErr)

			continue
		}

		docs[declared.Name()] = declared.Doc
		plans = append(plans, resolved)
	}

	if len(unplanned) > 0 {
		return nil, goerrors.Join(unplanned...)
	}

	return renderGRPC(plans, docs)
}

// renderGRPC emits the gRPC converters, gofmt'd, importing exactly the packages the bodies name.
func renderGRPC(plans []*plan, docs map[string]string) ([]byte, error) {
	var body strings.Builder

	for _, resolved := range plans {
		body.WriteString(renderGRPCConversion(resolved, docs[resolved.Conversion.Name]))
		body.WriteString("\n")
	}

	// The imports are read off the code rather than the rendered file, whose comments are
	// prose and can mention a package without using it.
	var code strings.Builder

	for _, resolved := range plans {
		fmt.Fprintf(&code, "%s %s\n", resolved.Conversion.From, resolved.Conversion.To)

		for _, statement := range resolved.Prelude {
			code.WriteString(statement + "\n")
		}

		for _, assigned := range resolved.Assignments {
			code.WriteString(assigned.Expr + "\n")
		}
	}

	var used []string

	for qualifier := range grpcImports {
		if regexp.MustCompile(`\b` + qualifier + `\.`).MatchString(code.String()) {
			used = append(used, qualifier)
		}
	}

	slices.SortFunc(used, func(a, b string) int { return strings.Compare(grpcImports[a], grpcImports[b]) })

	var file strings.Builder

	file.WriteString("// Code generated by cmd/tools/codegen/converters. DO NOT EDIT.\n\npackage grpcconverters\n\nimport (\n")

	// This repository's packages first and everything else after, the way gci groups them,
	// and an alias only where the qualifier is not already the package's name.
	ownPrefix := "github.com/primandproper/dinnerdonebetter/"
	for _, own := range []bool{true, false} {
		if !own {
			file.WriteString("\n")
		}

		for _, qualifier := range used {
			importPath := grpcImports[qualifier]
			if strings.HasPrefix(importPath, ownPrefix) != own {
				continue
			}

			if _, aliased := grpcImportAliases[qualifier]; !aliased {
				fmt.Fprintf(&file, "\t%q\n", importPath)
			} else {
				fmt.Fprintf(&file, "\t%s %q\n", qualifier, importPath)
			}
		}
	}

	file.WriteString(")\n\n")
	file.WriteString(body.String())

	formatted, err := format.Source([]byte(file.String()))
	if err != nil {
		return nil, errors.Wrap(err, "formatting generated gRPC converters")
	}

	return formatted, nil
}

// renderGRPCConversion emits one function.
func renderGRPCConversion(resolved *plan, doc string) string {
	conversion := resolved.Conversion

	var out strings.Builder

	// The two types usually share a name, so the doc says which side each is on.
	if strings.HasPrefix(conversion.To, grpcMessagesQualifier+".") {
		fmt.Fprintf(&out, "// %s builds the %s message from a domain %s.\n",
			conversion.Name, unqualified(conversion.To), unqualified(conversion.From))
	} else {
		fmt.Fprintf(&out, "// %s builds a domain %s from the %s message.\n",
			conversion.Name, unqualified(conversion.To), unqualified(conversion.From))
	}

	if doc != "" {
		out.WriteString("//\n")

		for _, line := range wrap(doc, commentWidth+16) {
			fmt.Fprintf(&out, "// %s\n", line)
		}
	}

	fmt.Fprintf(&out, "func %s(%s *%s) *%s {\n", conversion.Name, sourceParam, conversion.From, conversion.To)

	for _, statement := range resolved.Prelude {
		out.WriteString(statement)
		out.WriteString("\n\n")
	}

	fmt.Fprintf(&out, "return &%s{\n", conversion.To)
	renderAssignments(&out, resolved.Assignments)
	out.WriteString("}\n}\n")

	return out.String()
}
