package main

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/primandproper/platform-go/v11/errors"
)

// domainImportPath is where a domain package lives, given its directory name.
const domainImportPath = "github.com/primandproper/dinnerdonebetter/backend/internal/domain/%s"

// identifiersImportPath is the only other import a generated converter can need.
const identifiersImportPath = "github.com/primandproper/platform-go/v11/identifiers"

// render emits one domain's generated converters, gofmt'd.
//
// Formatting here rather than in a follow-up shell step is what lets the staleness test compare
// this output to the file on disk byte for byte: a separately formatted file would differ from
// unformatted output on every run, and the test could then only check something weaker than
// equality.
func render(domain string, plans []*plan) ([]byte, error) {
	var body strings.Builder

	usesIdentifiers := false
	for _, resolved := range plans {
		if resolved.UsesIdentifiers {
			usesIdentifiers = true
		}

		body.WriteString(renderConversion(domain, resolved))
		body.WriteString("\n")
	}

	var file strings.Builder

	fmt.Fprintf(&file, `// Code generated by cmd/tools/codegen/converters. DO NOT EDIT.

package converters

import (
	%q
`, fmt.Sprintf(domainImportPath, domain))

	if usesIdentifiers {
		fmt.Fprintf(&file, "\n\t%q\n", identifiersImportPath)
	}

	file.WriteString(")\n\n")
	file.WriteString(body.String())

	formatted, err := format.Source([]byte(file.String()))
	if err != nil {
		return nil, errors.Wrapf(err, "formatting generated converters for %s", domain)
	}

	return formatted, nil
}

// renderConversion emits one function.
func renderConversion(domain string, resolved *plan) string {
	conversion := resolved.Conversion

	doc := fmt.Sprintf("builds %s from %s.", article(conversion.To), article(conversion.From))

	var out strings.Builder

	// The doc comment is stored without its leading function name, the way a declaration
	// reads best, and put back here, the way Go wants it.
	for i, line := range strings.Split(doc, "\n") {
		if i == 0 {
			fmt.Fprintf(&out, "// %s %s\n", conversion.Name, line)

			continue
		}

		if line == "" {
			out.WriteString("//\n")

			continue
		}

		fmt.Fprintf(&out, "// %s\n", line)
	}

	fmt.Fprintf(&out, "func %s(%s *%s.%s) *%s.%s {\n",
		conversion.Name, sourceParam, domain, conversion.From, domain, conversion.To)

	for _, statement := range resolved.Prelude {
		out.WriteString(statement)
		out.WriteString("\n\n")
	}

	fmt.Fprintf(&out, "return &%s.%s{\n", domain, conversion.To)

	for i, assigned := range resolved.Assignments {
		// A run of omissions reads as one paragraph without a break between them, and the
		// field each reason belongs to stops being obvious.
		if assigned.Skipped && i > 0 {
			out.WriteString("\n")
		}

		if assigned.Skipped {
			for _, line := range wrap(assigned.Field+" is left unset. "+assigned.Why, commentWidth) {
				fmt.Fprintf(&out, "// %s\n", line)
			}

			continue
		}

		for paragraph := range strings.SplitSeq(assigned.Why, "\n") {
			for _, line := range wrap(paragraph, commentWidth) {
				fmt.Fprintf(&out, "// %s\n", line)
			}
		}

		fmt.Fprintf(&out, "%s: %s,\n", assigned.Field, assigned.Expr)
	}

	out.WriteString("}\n}\n")

	return out.String()
}

// commentWidth is how wide a comment inside a struct literal gets before it wraps. The literal
// sits two tabs in, so this is the repo's hundred-column line less that indentation and the
// comment marker.
const commentWidth = 80

// wrap breaks text into lines of at most width characters, on word boundaries. An empty text
// yields no lines at all, which is what lets a field with no reason render without a blank comment
// above it.
func wrap(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}

	lines := []string{words[0]}
	for _, word := range words[1:] {
		last := len(lines) - 1
		if len(lines[last])+1+len(word) <= width {
			lines[last] += " " + word

			continue
		}

		lines = append(lines, word)
	}

	return lines
}

// article prefixes a type name with the indefinite article its spelling calls for.
func article(name string) string {
	if name == "" {
		return name
	}

	if strings.ContainsRune("AEIOU", rune(name[0])) {
		return "an " + name
	}

	return "a " + name
}
