// Code generated by cmd/tools/codegen/fakes. DO NOT EDIT.

package fakes

import (
	"time"

	types "github.com/primandproper/dinnerdonebetter/backend/internal/domain/waitlists"
	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/waitlists/converters"

	"github.com/primandproper/platform-go/v10/filtering"
	"github.com/primandproper/platform-go/v10/identifiers"
	"github.com/primandproper/platform-go/v10/pointer"

	fake "github.com/brianvoe/gofakeit/v7"
)

func init() {
	if err := fake.Seed(time.Now().UnixNano()); err != nil {
		panic(err)
	}
}

// exampleQuantity is how many elements a faked list has.
const exampleQuantity = 3

// BuildFakeID builds a fake ID.
func BuildFakeID() string {
	return identifiers.New()
}

// BuildFakeTime builds a fake time.
func BuildFakeTime() time.Time {
	return fake.Date().Add(0).Truncate(time.Second).UTC()
}

// buildUniqueString builds a fake string.
func buildUniqueString() string {
	return fake.LoremIpsumSentence(7)
}

// BuildFakeWaitlist builds a faked Waitlist.
func BuildFakeWaitlist() *types.Waitlist {
	return &types.Waitlist{
		CreatedAt:     BuildFakeTime(),
		ValidUntil:    time.Now().Add(24 * time.Hour).UTC().Truncate(time.Second),
		LastUpdatedAt: pointer.To(BuildFakeTime()),
		ArchivedAt:    nil,
		ID:            BuildFakeID(),
		Name:          buildUniqueString(),
		Description:   buildUniqueString(),
	}
}

// BuildFakeWaitlistsList builds a faked Waitlist list.
func BuildFakeWaitlistsList() *filtering.QueryFilteredResult[types.Waitlist] {
	var examples []*types.Waitlist
	for range exampleQuantity {
		examples = append(examples, BuildFakeWaitlist())
	}

	return &filtering.QueryFilteredResult[types.Waitlist]{
		Pagination: filtering.Pagination{
			Cursor:          BuildFakeID(),
			MaxResponseSize: 50,
			FilteredCount:   exampleQuantity / 2,
			TotalCount:      exampleQuantity,
		},
		Data: examples,
	}
}

// BuildFakeWaitlistCreationRequestInput builds a faked WaitlistCreationRequestInput.
func BuildFakeWaitlistCreationRequestInput() *types.WaitlistCreationRequestInput {
	return converters.ConvertWaitlistToWaitlistCreationRequestInput(BuildFakeWaitlist())
}

// BuildFakeWaitlistUpdateRequestInput builds a faked WaitlistUpdateRequestInput.
func BuildFakeWaitlistUpdateRequestInput() *types.WaitlistUpdateRequestInput {
	return converters.ConvertWaitlistToWaitlistUpdateRequestInput(BuildFakeWaitlist())
}

// BuildFakeWaitlistSignup builds a faked WaitlistSignup.
func BuildFakeWaitlistSignup() *types.WaitlistSignup {
	return &types.WaitlistSignup{
		CreatedAt:         BuildFakeTime(),
		LastUpdatedAt:     pointer.To(BuildFakeTime()),
		ArchivedAt:        nil,
		ID:                BuildFakeID(),
		Notes:             buildUniqueString(),
		BelongsToWaitlist: BuildFakeID(),
		BelongsToUser:     BuildFakeID(),
		BelongsToAccount:  BuildFakeID(),
	}
}

// BuildFakeWaitlistSignupsList builds a faked WaitlistSignup list.
func BuildFakeWaitlistSignupsList() *filtering.QueryFilteredResult[types.WaitlistSignup] {
	var examples []*types.WaitlistSignup
	for range exampleQuantity {
		examples = append(examples, BuildFakeWaitlistSignup())
	}

	return &filtering.QueryFilteredResult[types.WaitlistSignup]{
		Pagination: filtering.Pagination{
			Cursor:          BuildFakeID(),
			MaxResponseSize: 50,
			FilteredCount:   exampleQuantity / 2,
			TotalCount:      exampleQuantity,
		},
		Data: examples,
	}
}

// BuildFakeWaitlistSignupCreationRequestInput builds a faked WaitlistSignupCreationRequestInput.
func BuildFakeWaitlistSignupCreationRequestInput() *types.WaitlistSignupCreationRequestInput {
	return converters.ConvertWaitlistSignupToWaitlistSignupCreationRequestInput(BuildFakeWaitlistSignup())
}

// BuildFakeWaitlistSignupUpdateRequestInput builds a faked WaitlistSignupUpdateRequestInput.
func BuildFakeWaitlistSignupUpdateRequestInput() *types.WaitlistSignupUpdateRequestInput {
	return converters.ConvertWaitlistSignupToWaitlistSignupUpdateRequestInput(BuildFakeWaitlistSignup())
}
