// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/domain/notifications"

	"github.com/primandproper/platform-go/v8/filtering"
)

// Ensure, that RepositoryMock does implement notifications.Repository.
// If this is not the case, regenerate this file with moq.
var _ notifications.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of notifications.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked notifications.Repository
//		mockedRepository := &RepositoryMock{
//			ArchiveUserDeviceTokenFunc: func(ctx context.Context, userID string, tokenID string) error {
//				panic("mock out the ArchiveUserDeviceToken method")
//			},
//			CreateUserDeviceTokenFunc: func(ctx context.Context, input *notifications.UserDeviceTokenDatabaseCreationInput) (*notifications.UserDeviceToken, error) {
//				panic("mock out the CreateUserDeviceToken method")
//			},
//			CreateUserNotificationFunc: func(ctx context.Context, input *notifications.UserNotificationDatabaseCreationInput) (*notifications.UserNotification, error) {
//				panic("mock out the CreateUserNotification method")
//			},
//			GetUserDeviceTokenFunc: func(ctx context.Context, userID string, tokenID string) (*notifications.UserDeviceToken, error) {
//				panic("mock out the GetUserDeviceToken method")
//			},
//			GetUserDeviceTokensFunc: func(ctx context.Context, userID string, filter *filtering.QueryFilter, platformFilter *string) (*filtering.QueryFilteredResult[notifications.UserDeviceToken], error) {
//				panic("mock out the GetUserDeviceTokens method")
//			},
//			GetUserNotificationFunc: func(ctx context.Context, userID string, userNotificationID string) (*notifications.UserNotification, error) {
//				panic("mock out the GetUserNotification method")
//			},
//			GetUserNotificationsFunc: func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[notifications.UserNotification], error) {
//				panic("mock out the GetUserNotifications method")
//			},
//			UpdateUserDeviceTokenFunc: func(ctx context.Context, updated *notifications.UserDeviceToken) error {
//				panic("mock out the UpdateUserDeviceToken method")
//			},
//			UpdateUserNotificationFunc: func(ctx context.Context, updated *notifications.UserNotification) error {
//				panic("mock out the UpdateUserNotification method")
//			},
//			UserDeviceTokenExistsFunc: func(ctx context.Context, userID string, tokenID string) (bool, error) {
//				panic("mock out the UserDeviceTokenExists method")
//			},
//			UserNotificationExistsFunc: func(ctx context.Context, userID string, userNotificationID string) (bool, error) {
//				panic("mock out the UserNotificationExists method")
//			},
//		}
//
//		// use mockedRepository in code that requires notifications.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// ArchiveUserDeviceTokenFunc mocks the ArchiveUserDeviceToken method.
	ArchiveUserDeviceTokenFunc func(ctx context.Context, userID string, tokenID string) error

	// CreateUserDeviceTokenFunc mocks the CreateUserDeviceToken method.
	CreateUserDeviceTokenFunc func(ctx context.Context, input *notifications.UserDeviceTokenDatabaseCreationInput) (*notifications.UserDeviceToken, error)

	// CreateUserNotificationFunc mocks the CreateUserNotification method.
	CreateUserNotificationFunc func(ctx context.Context, input *notifications.UserNotificationDatabaseCreationInput) (*notifications.UserNotification, error)

	// GetUserDeviceTokenFunc mocks the GetUserDeviceToken method.
	GetUserDeviceTokenFunc func(ctx context.Context, userID string, tokenID string) (*notifications.UserDeviceToken, error)

	// GetUserDeviceTokensFunc mocks the GetUserDeviceTokens method.
	GetUserDeviceTokensFunc func(ctx context.Context, userID string, filter *filtering.QueryFilter, platformFilter *string) (*filtering.QueryFilteredResult[notifications.UserDeviceToken], error)

	// GetUserNotificationFunc mocks the GetUserNotification method.
	GetUserNotificationFunc func(ctx context.Context, userID string, userNotificationID string) (*notifications.UserNotification, error)

	// GetUserNotificationsFunc mocks the GetUserNotifications method.
	GetUserNotificationsFunc func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[notifications.UserNotification], error)

	// UpdateUserDeviceTokenFunc mocks the UpdateUserDeviceToken method.
	UpdateUserDeviceTokenFunc func(ctx context.Context, updated *notifications.UserDeviceToken) error

	// UpdateUserNotificationFunc mocks the UpdateUserNotification method.
	UpdateUserNotificationFunc func(ctx context.Context, updated *notifications.UserNotification) error

	// UserDeviceTokenExistsFunc mocks the UserDeviceTokenExists method.
	UserDeviceTokenExistsFunc func(ctx context.Context, userID string, tokenID string) (bool, error)

	// UserNotificationExistsFunc mocks the UserNotificationExists method.
	UserNotificationExistsFunc func(ctx context.Context, userID string, userNotificationID string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveUserDeviceToken holds details about calls to the ArchiveUserDeviceToken method.
		ArchiveUserDeviceToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// TokenID is the tokenID argument value.
			TokenID string
		}
		// CreateUserDeviceToken holds details about calls to the CreateUserDeviceToken method.
		CreateUserDeviceToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *notifications.UserDeviceTokenDatabaseCreationInput
		}
		// CreateUserNotification holds details about calls to the CreateUserNotification method.
		CreateUserNotification []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *notifications.UserNotificationDatabaseCreationInput
		}
		// GetUserDeviceToken holds details about calls to the GetUserDeviceToken method.
		GetUserDeviceToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// TokenID is the tokenID argument value.
			TokenID string
		}
		// GetUserDeviceTokens holds details about calls to the GetUserDeviceTokens method.
		GetUserDeviceTokens []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
			// PlatformFilter is the platformFilter argument value.
			PlatformFilter *string
		}
		// GetUserNotification holds details about calls to the GetUserNotification method.
		GetUserNotification []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// UserNotificationID is the userNotificationID argument value.
			UserNotificationID string
		}
		// GetUserNotifications holds details about calls to the GetUserNotifications method.
		GetUserNotifications []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// UpdateUserDeviceToken holds details about calls to the UpdateUserDeviceToken method.
		UpdateUserDeviceToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Updated is the updated argument value.
			Updated *notifications.UserDeviceToken
		}
		// UpdateUserNotification holds details about calls to the UpdateUserNotification method.
		UpdateUserNotification []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Updated is the updated argument value.
			Updated *notifications.UserNotification
		}
		// UserDeviceTokenExists holds details about calls to the UserDeviceTokenExists method.
		UserDeviceTokenExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// TokenID is the tokenID argument value.
			TokenID string
		}
		// UserNotificationExists holds details about calls to the UserNotificationExists method.
		UserNotificationExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// UserNotificationID is the userNotificationID argument value.
			UserNotificationID string
		}
	}
	lockArchiveUserDeviceToken sync.RWMutex
	lockCreateUserDeviceToken  sync.RWMutex
	lockCreateUserNotification sync.RWMutex
	lockGetUserDeviceToken     sync.RWMutex
	lockGetUserDeviceTokens    sync.RWMutex
	lockGetUserNotification    sync.RWMutex
	lockGetUserNotifications   sync.RWMutex
	lockUpdateUserDeviceToken  sync.RWMutex
	lockUpdateUserNotification sync.RWMutex
	lockUserDeviceTokenExists  sync.RWMutex
	lockUserNotificationExists sync.RWMutex
}

// ArchiveUserDeviceToken calls ArchiveUserDeviceTokenFunc.
func (mock *RepositoryMock) ArchiveUserDeviceToken(ctx context.Context, userID string, tokenID string) error {
	if mock.ArchiveUserDeviceTokenFunc == nil {
		panic("RepositoryMock.ArchiveUserDeviceTokenFunc: method is nil but Repository.ArchiveUserDeviceToken was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		UserID  string
		TokenID string
	}{
		Ctx:     ctx,
		UserID:  userID,
		TokenID: tokenID,
	}
	mock.lockArchiveUserDeviceToken.Lock()
	mock.calls.ArchiveUserDeviceToken = append(mock.calls.ArchiveUserDeviceToken, callInfo)
	mock.lockArchiveUserDeviceToken.Unlock()
	return mock.ArchiveUserDeviceTokenFunc(ctx, userID, tokenID)
}

// ArchiveUserDeviceTokenCalls gets all the calls that were made to ArchiveUserDeviceToken.
// Check the length with:
//
//	len(mockedRepository.ArchiveUserDeviceTokenCalls())
func (mock *RepositoryMock) ArchiveUserDeviceTokenCalls() []struct {
	Ctx     context.Context
	UserID  string
	TokenID string
} {
	var calls []struct {
		Ctx     context.Context
		UserID  string
		TokenID string
	}
	mock.lockArchiveUserDeviceToken.RLock()
	calls = mock.calls.ArchiveUserDeviceToken
	mock.lockArchiveUserDeviceToken.RUnlock()
	return calls
}

// CreateUserDeviceToken calls CreateUserDeviceTokenFunc.
func (mock *RepositoryMock) CreateUserDeviceToken(ctx context.Context, input *notifications.UserDeviceTokenDatabaseCreationInput) (*notifications.UserDeviceToken, error) {
	if mock.CreateUserDeviceTokenFunc == nil {
		panic("RepositoryMock.CreateUserDeviceTokenFunc: method is nil but Repository.CreateUserDeviceToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *notifications.UserDeviceTokenDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateUserDeviceToken.Lock()
	mock.calls.CreateUserDeviceToken = append(mock.calls.CreateUserDeviceToken, callInfo)
	mock.lockCreateUserDeviceToken.Unlock()
	return mock.CreateUserDeviceTokenFunc(ctx, input)
}

// CreateUserDeviceTokenCalls gets all the calls that were made to CreateUserDeviceToken.
// Check the length with:
//
//	len(mockedRepository.CreateUserDeviceTokenCalls())
func (mock *RepositoryMock) CreateUserDeviceTokenCalls() []struct {
	Ctx   context.Context
	Input *notifications.UserDeviceTokenDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *notifications.UserDeviceTokenDatabaseCreationInput
	}
	mock.lockCreateUserDeviceToken.RLock()
	calls = mock.calls.CreateUserDeviceToken
	mock.lockCreateUserDeviceToken.RUnlock()
	return calls
}

// CreateUserNotification calls CreateUserNotificationFunc.
func (mock *RepositoryMock) CreateUserNotification(ctx context.Context, input *notifications.UserNotificationDatabaseCreationInput) (*notifications.UserNotification, error) {
	if mock.CreateUserNotificationFunc == nil {
		panic("RepositoryMock.CreateUserNotificationFunc: method is nil but Repository.CreateUserNotification was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *notifications.UserNotificationDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateUserNotification.Lock()
	mock.calls.CreateUserNotification = append(mock.calls.CreateUserNotification, callInfo)
	mock.lockCreateUserNotification.Unlock()
	return mock.CreateUserNotificationFunc(ctx, input)
}

// CreateUserNotificationCalls gets all the calls that were made to CreateUserNotification.
// Check the length with:
//
//	len(mockedRepository.CreateUserNotificationCalls())
func (mock *RepositoryMock) CreateUserNotificationCalls() []struct {
	Ctx   context.Context
	Input *notifications.UserNotificationDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *notifications.UserNotificationDatabaseCreationInput
	}
	mock.lockCreateUserNotification.RLock()
	calls = mock.calls.CreateUserNotification
	mock.lockCreateUserNotification.RUnlock()
	return calls
}

// GetUserDeviceToken calls GetUserDeviceTokenFunc.
func (mock *RepositoryMock) GetUserDeviceToken(ctx context.Context, userID string, tokenID string) (*notifications.UserDeviceToken, error) {
	if mock.GetUserDeviceTokenFunc == nil {
		panic("RepositoryMock.GetUserDeviceTokenFunc: method is nil but Repository.GetUserDeviceToken was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		UserID  string
		TokenID string
	}{
		Ctx:     ctx,
		UserID:  userID,
		TokenID: tokenID,
	}
	mock.lockGetUserDeviceToken.Lock()
	mock.calls.GetUserDeviceToken = append(mock.calls.GetUserDeviceToken, callInfo)
	mock.lockGetUserDeviceToken.Unlock()
	return mock.GetUserDeviceTokenFunc(ctx, userID, tokenID)
}

// GetUserDeviceTokenCalls gets all the calls that were made to GetUserDeviceToken.
// Check the length with:
//
//	len(mockedRepository.GetUserDeviceTokenCalls())
func (mock *RepositoryMock) GetUserDeviceTokenCalls() []struct {
	Ctx     context.Context
	UserID  string
	TokenID string
} {
	var calls []struct {
		Ctx     context.Context
		UserID  string
		TokenID string
	}
	mock.lockGetUserDeviceToken.RLock()
	calls = mock.calls.GetUserDeviceToken
	mock.lockGetUserDeviceToken.RUnlock()
	return calls
}

// GetUserDeviceTokens calls GetUserDeviceTokensFunc.
func (mock *RepositoryMock) GetUserDeviceTokens(ctx context.Context, userID string, filter *filtering.QueryFilter, platformFilter *string) (*filtering.QueryFilteredResult[notifications.UserDeviceToken], error) {
	if mock.GetUserDeviceTokensFunc == nil {
		panic("RepositoryMock.GetUserDeviceTokensFunc: method is nil but Repository.GetUserDeviceTokens was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		UserID         string
		Filter         *filtering.QueryFilter
		PlatformFilter *string
	}{
		Ctx:            ctx,
		UserID:         userID,
		Filter:         filter,
		PlatformFilter: platformFilter,
	}
	mock.lockGetUserDeviceTokens.Lock()
	mock.calls.GetUserDeviceTokens = append(mock.calls.GetUserDeviceTokens, callInfo)
	mock.lockGetUserDeviceTokens.Unlock()
	return mock.GetUserDeviceTokensFunc(ctx, userID, filter, platformFilter)
}

// GetUserDeviceTokensCalls gets all the calls that were made to GetUserDeviceTokens.
// Check the length with:
//
//	len(mockedRepository.GetUserDeviceTokensCalls())
func (mock *RepositoryMock) GetUserDeviceTokensCalls() []struct {
	Ctx            context.Context
	UserID         string
	Filter         *filtering.QueryFilter
	PlatformFilter *string
} {
	var calls []struct {
		Ctx            context.Context
		UserID         string
		Filter         *filtering.QueryFilter
		PlatformFilter *string
	}
	mock.lockGetUserDeviceTokens.RLock()
	calls = mock.calls.GetUserDeviceTokens
	mock.lockGetUserDeviceTokens.RUnlock()
	return calls
}

// GetUserNotification calls GetUserNotificationFunc.
func (mock *RepositoryMock) GetUserNotification(ctx context.Context, userID string, userNotificationID string) (*notifications.UserNotification, error) {
	if mock.GetUserNotificationFunc == nil {
		panic("RepositoryMock.GetUserNotificationFunc: method is nil but Repository.GetUserNotification was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		UserID             string
		UserNotificationID string
	}{
		Ctx:                ctx,
		UserID:             userID,
		UserNotificationID: userNotificationID,
	}
	mock.lockGetUserNotification.Lock()
	mock.calls.GetUserNotification = append(mock.calls.GetUserNotification, callInfo)
	mock.lockGetUserNotification.Unlock()
	return mock.GetUserNotificationFunc(ctx, userID, userNotificationID)
}

// GetUserNotificationCalls gets all the calls that were made to GetUserNotification.
// Check the length with:
//
//	len(mockedRepository.GetUserNotificationCalls())
func (mock *RepositoryMock) GetUserNotificationCalls() []struct {
	Ctx                context.Context
	UserID             string
	UserNotificationID string
} {
	var calls []struct {
		Ctx                context.Context
		UserID             string
		UserNotificationID string
	}
	mock.lockGetUserNotification.RLock()
	calls = mock.calls.GetUserNotification
	mock.lockGetUserNotification.RUnlock()
	return calls
}

// GetUserNotifications calls GetUserNotificationsFunc.
func (mock *RepositoryMock) GetUserNotifications(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[notifications.UserNotification], error) {
	if mock.GetUserNotificationsFunc == nil {
		panic("RepositoryMock.GetUserNotificationsFunc: method is nil but Repository.GetUserNotifications was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		UserID: userID,
		Filter: filter,
	}
	mock.lockGetUserNotifications.Lock()
	mock.calls.GetUserNotifications = append(mock.calls.GetUserNotifications, callInfo)
	mock.lockGetUserNotifications.Unlock()
	return mock.GetUserNotificationsFunc(ctx, userID, filter)
}

// GetUserNotificationsCalls gets all the calls that were made to GetUserNotifications.
// Check the length with:
//
//	len(mockedRepository.GetUserNotificationsCalls())
func (mock *RepositoryMock) GetUserNotificationsCalls() []struct {
	Ctx    context.Context
	UserID string
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}
	mock.lockGetUserNotifications.RLock()
	calls = mock.calls.GetUserNotifications
	mock.lockGetUserNotifications.RUnlock()
	return calls
}

// UpdateUserDeviceToken calls UpdateUserDeviceTokenFunc.
func (mock *RepositoryMock) UpdateUserDeviceToken(ctx context.Context, updated *notifications.UserDeviceToken) error {
	if mock.UpdateUserDeviceTokenFunc == nil {
		panic("RepositoryMock.UpdateUserDeviceTokenFunc: method is nil but Repository.UpdateUserDeviceToken was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Updated *notifications.UserDeviceToken
	}{
		Ctx:     ctx,
		Updated: updated,
	}
	mock.lockUpdateUserDeviceToken.Lock()
	mock.calls.UpdateUserDeviceToken = append(mock.calls.UpdateUserDeviceToken, callInfo)
	mock.lockUpdateUserDeviceToken.Unlock()
	return mock.UpdateUserDeviceTokenFunc(ctx, updated)
}

// UpdateUserDeviceTokenCalls gets all the calls that were made to UpdateUserDeviceToken.
// Check the length with:
//
//	len(mockedRepository.UpdateUserDeviceTokenCalls())
func (mock *RepositoryMock) UpdateUserDeviceTokenCalls() []struct {
	Ctx     context.Context
	Updated *notifications.UserDeviceToken
} {
	var calls []struct {
		Ctx     context.Context
		Updated *notifications.UserDeviceToken
	}
	mock.lockUpdateUserDeviceToken.RLock()
	calls = mock.calls.UpdateUserDeviceToken
	mock.lockUpdateUserDeviceToken.RUnlock()
	return calls
}

// UpdateUserNotification calls UpdateUserNotificationFunc.
func (mock *RepositoryMock) UpdateUserNotification(ctx context.Context, updated *notifications.UserNotification) error {
	if mock.UpdateUserNotificationFunc == nil {
		panic("RepositoryMock.UpdateUserNotificationFunc: method is nil but Repository.UpdateUserNotification was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Updated *notifications.UserNotification
	}{
		Ctx:     ctx,
		Updated: updated,
	}
	mock.lockUpdateUserNotification.Lock()
	mock.calls.UpdateUserNotification = append(mock.calls.UpdateUserNotification, callInfo)
	mock.lockUpdateUserNotification.Unlock()
	return mock.UpdateUserNotificationFunc(ctx, updated)
}

// UpdateUserNotificationCalls gets all the calls that were made to UpdateUserNotification.
// Check the length with:
//
//	len(mockedRepository.UpdateUserNotificationCalls())
func (mock *RepositoryMock) UpdateUserNotificationCalls() []struct {
	Ctx     context.Context
	Updated *notifications.UserNotification
} {
	var calls []struct {
		Ctx     context.Context
		Updated *notifications.UserNotification
	}
	mock.lockUpdateUserNotification.RLock()
	calls = mock.calls.UpdateUserNotification
	mock.lockUpdateUserNotification.RUnlock()
	return calls
}

// UserDeviceTokenExists calls UserDeviceTokenExistsFunc.
func (mock *RepositoryMock) UserDeviceTokenExists(ctx context.Context, userID string, tokenID string) (bool, error) {
	if mock.UserDeviceTokenExistsFunc == nil {
		panic("RepositoryMock.UserDeviceTokenExistsFunc: method is nil but Repository.UserDeviceTokenExists was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		UserID  string
		TokenID string
	}{
		Ctx:     ctx,
		UserID:  userID,
		TokenID: tokenID,
	}
	mock.lockUserDeviceTokenExists.Lock()
	mock.calls.UserDeviceTokenExists = append(mock.calls.UserDeviceTokenExists, callInfo)
	mock.lockUserDeviceTokenExists.Unlock()
	return mock.UserDeviceTokenExistsFunc(ctx, userID, tokenID)
}

// UserDeviceTokenExistsCalls gets all the calls that were made to UserDeviceTokenExists.
// Check the length with:
//
//	len(mockedRepository.UserDeviceTokenExistsCalls())
func (mock *RepositoryMock) UserDeviceTokenExistsCalls() []struct {
	Ctx     context.Context
	UserID  string
	TokenID string
} {
	var calls []struct {
		Ctx     context.Context
		UserID  string
		TokenID string
	}
	mock.lockUserDeviceTokenExists.RLock()
	calls = mock.calls.UserDeviceTokenExists
	mock.lockUserDeviceTokenExists.RUnlock()
	return calls
}

// UserNotificationExists calls UserNotificationExistsFunc.
func (mock *RepositoryMock) UserNotificationExists(ctx context.Context, userID string, userNotificationID string) (bool, error) {
	if mock.UserNotificationExistsFunc == nil {
		panic("RepositoryMock.UserNotificationExistsFunc: method is nil but Repository.UserNotificationExists was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		UserID             string
		UserNotificationID string
	}{
		Ctx:                ctx,
		UserID:             userID,
		UserNotificationID: userNotificationID,
	}
	mock.lockUserNotificationExists.Lock()
	mock.calls.UserNotificationExists = append(mock.calls.UserNotificationExists, callInfo)
	mock.lockUserNotificationExists.Unlock()
	return mock.UserNotificationExistsFunc(ctx, userID, userNotificationID)
}

// UserNotificationExistsCalls gets all the calls that were made to UserNotificationExists.
// Check the length with:
//
//	len(mockedRepository.UserNotificationExistsCalls())
func (mock *RepositoryMock) UserNotificationExistsCalls() []struct {
	Ctx                context.Context
	UserID             string
	UserNotificationID string
} {
	var calls []struct {
		Ctx                context.Context
		UserID             string
		UserNotificationID string
	}
	mock.lockUserNotificationExists.RLock()
	calls = mock.calls.UserNotificationExists
	mock.lockUserNotificationExists.RUnlock()
	return calls
}
