// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: comments/comments_messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from '../google/protobuf/timestamp';

export const protobufPackage = 'comments';

/**
 * CommentTarget is what a comment is about: a kind of thing, and one of them.
 *
 * It is one message rather than two loose fields because a type without an id is
 * not a target, and every call that takes one takes both — passing them
 * separately is how a call site pairs one comment's type with another's id.
 */
export interface CommentTarget {
  /**
   * type is the kind of thing, as the target catalog spells it. A type the
   * catalog does not hold is refused at the write.
   */
  type: string;
  /** id is which one, as the owning domain spells it. */
  id: string;
}

export interface Comment {
  id: string;
  /** body is what the person actually said. */
  body: string;
  target: CommentTarget | undefined;
  /**
   * parent_id is the comment this one replies to, and the empty string is a
   * comment that replies to nothing. Threads are one level deep: a reply may not
   * itself be replied to.
   */
  parentId: string;
  /** author is the ID of the user who wrote it. */
  author: string;
  createdAt: Date | undefined;
  /**
   * last_updated_at is when the body was last edited, and unset for a comment
   * nobody has revised. It is what a client renders an "edited" marker from.
   */
  lastUpdatedAt: Date | undefined;
}

export interface CommentCreationRequestInput {
  body: string;
  /** parent_id makes this a reply. Empty is a root comment. */
  parentId: string;
  /**
   * target is required for CreateComment and ignored for AddCommentTo*, which
   * name the target in the request itself.
   */
  target: CommentTarget | undefined;
}

export interface CommentUpdateRequestInput {
  /**
   * body is the only editable fact about a comment. The target is what it is
   * about, the parent is which conversation it is in, and the author is who said
   * it; an update that assigned any of the three would silently move somebody
   * else's words.
   */
  body: string;
}

function createBaseCommentTarget(): CommentTarget {
  return { type: '', id: '' };
}

export const CommentTarget: MessageFns<CommentTarget> = {
  encode(message: CommentTarget, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== '') {
      writer.uint32(10).string(message.type);
    }
    if (message.id !== '') {
      writer.uint32(18).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommentTarget {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommentTarget();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommentTarget {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : '',
      id: isSet(object.id) ? globalThis.String(object.id) : '',
    };
  },

  toJSON(message: CommentTarget): unknown {
    const obj: any = {};
    if (message.type !== '') {
      obj.type = message.type;
    }
    if (message.id !== '') {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommentTarget>, I>>(base?: I): CommentTarget {
    return CommentTarget.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommentTarget>, I>>(object: I): CommentTarget {
    const message = createBaseCommentTarget();
    message.type = object.type ?? '';
    message.id = object.id ?? '';
    return message;
  },
};

function createBaseComment(): Comment {
  return {
    id: '',
    body: '',
    target: undefined,
    parentId: '',
    author: '',
    createdAt: undefined,
    lastUpdatedAt: undefined,
  };
}

export const Comment: MessageFns<Comment> = {
  encode(message: Comment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.body !== '') {
      writer.uint32(18).string(message.body);
    }
    if (message.target !== undefined) {
      CommentTarget.encode(message.target, writer.uint32(26).fork()).join();
    }
    if (message.parentId !== '') {
      writer.uint32(34).string(message.parentId);
    }
    if (message.author !== '') {
      writer.uint32(42).string(message.author);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(50).fork()).join();
    }
    if (message.lastUpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.lastUpdatedAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Comment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.target = CommentTarget.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.lastUpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Comment {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      body: isSet(object.body) ? globalThis.String(object.body) : '',
      target: isSet(object.target) ? CommentTarget.fromJSON(object.target) : undefined,
      parentId: isSet(object.parentId)
        ? globalThis.String(object.parentId)
        : isSet(object.parent_id)
          ? globalThis.String(object.parent_id)
          : '',
      author: isSet(object.author) ? globalThis.String(object.author) : '',
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
      lastUpdatedAt: isSet(object.lastUpdatedAt)
        ? fromJsonTimestamp(object.lastUpdatedAt)
        : isSet(object.last_updated_at)
          ? fromJsonTimestamp(object.last_updated_at)
          : undefined,
    };
  },

  toJSON(message: Comment): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.body !== '') {
      obj.body = message.body;
    }
    if (message.target !== undefined) {
      obj.target = CommentTarget.toJSON(message.target);
    }
    if (message.parentId !== '') {
      obj.parentId = message.parentId;
    }
    if (message.author !== '') {
      obj.author = message.author;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.lastUpdatedAt !== undefined) {
      obj.lastUpdatedAt = message.lastUpdatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Comment>, I>>(base?: I): Comment {
    return Comment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Comment>, I>>(object: I): Comment {
    const message = createBaseComment();
    message.id = object.id ?? '';
    message.body = object.body ?? '';
    message.target =
      object.target !== undefined && object.target !== null ? CommentTarget.fromPartial(object.target) : undefined;
    message.parentId = object.parentId ?? '';
    message.author = object.author ?? '';
    message.createdAt = object.createdAt ?? undefined;
    message.lastUpdatedAt = object.lastUpdatedAt ?? undefined;
    return message;
  },
};

function createBaseCommentCreationRequestInput(): CommentCreationRequestInput {
  return { body: '', parentId: '', target: undefined };
}

export const CommentCreationRequestInput: MessageFns<CommentCreationRequestInput> = {
  encode(message: CommentCreationRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.body !== '') {
      writer.uint32(10).string(message.body);
    }
    if (message.parentId !== '') {
      writer.uint32(18).string(message.parentId);
    }
    if (message.target !== undefined) {
      CommentTarget.encode(message.target, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommentCreationRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommentCreationRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.target = CommentTarget.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommentCreationRequestInput {
    return {
      body: isSet(object.body) ? globalThis.String(object.body) : '',
      parentId: isSet(object.parentId)
        ? globalThis.String(object.parentId)
        : isSet(object.parent_id)
          ? globalThis.String(object.parent_id)
          : '',
      target: isSet(object.target) ? CommentTarget.fromJSON(object.target) : undefined,
    };
  },

  toJSON(message: CommentCreationRequestInput): unknown {
    const obj: any = {};
    if (message.body !== '') {
      obj.body = message.body;
    }
    if (message.parentId !== '') {
      obj.parentId = message.parentId;
    }
    if (message.target !== undefined) {
      obj.target = CommentTarget.toJSON(message.target);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommentCreationRequestInput>, I>>(base?: I): CommentCreationRequestInput {
    return CommentCreationRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommentCreationRequestInput>, I>>(object: I): CommentCreationRequestInput {
    const message = createBaseCommentCreationRequestInput();
    message.body = object.body ?? '';
    message.parentId = object.parentId ?? '';
    message.target =
      object.target !== undefined && object.target !== null ? CommentTarget.fromPartial(object.target) : undefined;
    return message;
  },
};

function createBaseCommentUpdateRequestInput(): CommentUpdateRequestInput {
  return { body: '' };
}

export const CommentUpdateRequestInput: MessageFns<CommentUpdateRequestInput> = {
  encode(message: CommentUpdateRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.body !== '') {
      writer.uint32(10).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommentUpdateRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommentUpdateRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommentUpdateRequestInput {
    return { body: isSet(object.body) ? globalThis.String(object.body) : '' };
  },

  toJSON(message: CommentUpdateRequestInput): unknown {
    const obj: any = {};
    if (message.body !== '') {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommentUpdateRequestInput>, I>>(base?: I): CommentUpdateRequestInput {
    return CommentUpdateRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommentUpdateRequestInput>, I>>(object: I): CommentUpdateRequestInput {
    const message = createBaseCommentUpdateRequestInput();
    message.body = object.body ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
