// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: auth/auth_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import {
  ExchangeTokenRequest,
  ExchangeTokenResponse,
  RegisterUserRequest,
  RegisterUserResponse,
} from './auth_service_types';

export const protobufPackage = 'auth';

/**
 * AuthService is what is left of this application's own sign-in surface: the two doors
 * platform's SignInService does not have yet. Everything else a client signs in, proves a
 * credential or manages a login through is platform's — SignInService, PasswordResetService
 * and PasskeysService.
 */
export type AuthServiceService = typeof AuthServiceService;
export const AuthServiceService = {
  /**
   * RegisterUser is a sign-up, until platform's SignInService has an open sign-up door
   * (platform-go#1068).
   */
  registerUser: {
    path: '/auth.AuthService/RegisterUser' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RegisterUserRequest): Buffer => Buffer.from(RegisterUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RegisterUserRequest => RegisterUserRequest.decode(value),
    responseSerialize: (value: RegisterUserResponse): Buffer =>
      Buffer.from(RegisterUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RegisterUserResponse => RegisterUserResponse.decode(value),
  },
  /**
   * ExchangeToken moves a login into another of its user's accounts, until platform's
   * SignInService can (platform-go#1069).
   */
  exchangeToken: {
    path: '/auth.AuthService/ExchangeToken' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ExchangeTokenRequest): Buffer => Buffer.from(ExchangeTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ExchangeTokenRequest => ExchangeTokenRequest.decode(value),
    responseSerialize: (value: ExchangeTokenResponse): Buffer =>
      Buffer.from(ExchangeTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ExchangeTokenResponse => ExchangeTokenResponse.decode(value),
  },
} as const;

export interface AuthServiceServer extends UntypedServiceImplementation {
  /**
   * RegisterUser is a sign-up, until platform's SignInService has an open sign-up door
   * (platform-go#1068).
   */
  registerUser: handleUnaryCall<RegisterUserRequest, RegisterUserResponse>;
  /**
   * ExchangeToken moves a login into another of its user's accounts, until platform's
   * SignInService can (platform-go#1069).
   */
  exchangeToken: handleUnaryCall<ExchangeTokenRequest, ExchangeTokenResponse>;
}

export interface AuthServiceClient extends Client {
  /**
   * RegisterUser is a sign-up, until platform's SignInService has an open sign-up door
   * (platform-go#1068).
   */
  registerUser(
    request: RegisterUserRequest,
    callback: (error: ServiceError | null, response: RegisterUserResponse) => void,
  ): ClientUnaryCall;
  registerUser(
    request: RegisterUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RegisterUserResponse) => void,
  ): ClientUnaryCall;
  registerUser(
    request: RegisterUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RegisterUserResponse) => void,
  ): ClientUnaryCall;
  /**
   * ExchangeToken moves a login into another of its user's accounts, until platform's
   * SignInService can (platform-go#1069).
   */
  exchangeToken(
    request: ExchangeTokenRequest,
    callback: (error: ServiceError | null, response: ExchangeTokenResponse) => void,
  ): ClientUnaryCall;
  exchangeToken(
    request: ExchangeTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExchangeTokenResponse) => void,
  ): ClientUnaryCall;
  exchangeToken(
    request: ExchangeTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExchangeTokenResponse) => void,
  ): ClientUnaryCall;
}

export const AuthServiceClient = makeGenericClientConstructor(AuthServiceService, 'auth.AuthService') as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AuthServiceClient;
  service: typeof AuthServiceService;
  serviceName: string;
};
