// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/payments"

	"github.com/primandproper/platform-go/v10/filtering"
)

// Ensure, that RepositoryMock does implement payments.Repository.
// If this is not the case, regenerate this file with moq.
var _ payments.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of payments.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked payments.Repository
//		mockedRepository := &RepositoryMock{
//			ArchiveProductFunc: func(ctx context.Context, id string) error {
//				panic("mock out the ArchiveProduct method")
//			},
//			ArchiveSubscriptionFunc: func(ctx context.Context, id string) error {
//				panic("mock out the ArchiveSubscription method")
//			},
//			CreatePaymentTransactionFunc: func(ctx context.Context, input *payments.PaymentTransactionDatabaseCreationInput) (*payments.PaymentTransaction, error) {
//				panic("mock out the CreatePaymentTransaction method")
//			},
//			CreateProductFunc: func(ctx context.Context, input *payments.ProductDatabaseCreationInput) (*payments.Product, error) {
//				panic("mock out the CreateProduct method")
//			},
//			CreatePurchaseFunc: func(ctx context.Context, input *payments.PurchaseDatabaseCreationInput) (*payments.Purchase, error) {
//				panic("mock out the CreatePurchase method")
//			},
//			CreateSubscriptionFunc: func(ctx context.Context, input *payments.SubscriptionDatabaseCreationInput) (*payments.Subscription, error) {
//				panic("mock out the CreateSubscription method")
//			},
//			GetPaymentTransactionsForAccountFunc: func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.PaymentTransaction], error) {
//				panic("mock out the GetPaymentTransactionsForAccount method")
//			},
//			GetProductFunc: func(ctx context.Context, id string) (*payments.Product, error) {
//				panic("mock out the GetProduct method")
//			},
//			GetProductByExternalIDFunc: func(ctx context.Context, externalProductID string) (*payments.Product, error) {
//				panic("mock out the GetProductByExternalID method")
//			},
//			GetProductsFunc: func(ctx context.Context, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Product], error) {
//				panic("mock out the GetProducts method")
//			},
//			GetPurchaseFunc: func(ctx context.Context, id string) (*payments.Purchase, error) {
//				panic("mock out the GetPurchase method")
//			},
//			GetPurchasesForAccountFunc: func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Purchase], error) {
//				panic("mock out the GetPurchasesForAccount method")
//			},
//			GetSubscriptionFunc: func(ctx context.Context, id string) (*payments.Subscription, error) {
//				panic("mock out the GetSubscription method")
//			},
//			GetSubscriptionByExternalIDFunc: func(ctx context.Context, externalID string) (*payments.Subscription, error) {
//				panic("mock out the GetSubscriptionByExternalID method")
//			},
//			GetSubscriptionsForAccountFunc: func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Subscription], error) {
//				panic("mock out the GetSubscriptionsForAccount method")
//			},
//			ProductExistsFunc: func(ctx context.Context, id string) (bool, error) {
//				panic("mock out the ProductExists method")
//			},
//			UpdateProductFunc: func(ctx context.Context, product *payments.Product) error {
//				panic("mock out the UpdateProduct method")
//			},
//			UpdateSubscriptionFunc: func(ctx context.Context, sub *payments.Subscription) error {
//				panic("mock out the UpdateSubscription method")
//			},
//			UpdateSubscriptionStatusFunc: func(ctx context.Context, id string, status string) error {
//				panic("mock out the UpdateSubscriptionStatus method")
//			},
//		}
//
//		// use mockedRepository in code that requires payments.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// ArchiveProductFunc mocks the ArchiveProduct method.
	ArchiveProductFunc func(ctx context.Context, id string) error

	// ArchiveSubscriptionFunc mocks the ArchiveSubscription method.
	ArchiveSubscriptionFunc func(ctx context.Context, id string) error

	// CreatePaymentTransactionFunc mocks the CreatePaymentTransaction method.
	CreatePaymentTransactionFunc func(ctx context.Context, input *payments.PaymentTransactionDatabaseCreationInput) (*payments.PaymentTransaction, error)

	// CreateProductFunc mocks the CreateProduct method.
	CreateProductFunc func(ctx context.Context, input *payments.ProductDatabaseCreationInput) (*payments.Product, error)

	// CreatePurchaseFunc mocks the CreatePurchase method.
	CreatePurchaseFunc func(ctx context.Context, input *payments.PurchaseDatabaseCreationInput) (*payments.Purchase, error)

	// CreateSubscriptionFunc mocks the CreateSubscription method.
	CreateSubscriptionFunc func(ctx context.Context, input *payments.SubscriptionDatabaseCreationInput) (*payments.Subscription, error)

	// GetPaymentTransactionsForAccountFunc mocks the GetPaymentTransactionsForAccount method.
	GetPaymentTransactionsForAccountFunc func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.PaymentTransaction], error)

	// GetProductFunc mocks the GetProduct method.
	GetProductFunc func(ctx context.Context, id string) (*payments.Product, error)

	// GetProductByExternalIDFunc mocks the GetProductByExternalID method.
	GetProductByExternalIDFunc func(ctx context.Context, externalProductID string) (*payments.Product, error)

	// GetProductsFunc mocks the GetProducts method.
	GetProductsFunc func(ctx context.Context, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Product], error)

	// GetPurchaseFunc mocks the GetPurchase method.
	GetPurchaseFunc func(ctx context.Context, id string) (*payments.Purchase, error)

	// GetPurchasesForAccountFunc mocks the GetPurchasesForAccount method.
	GetPurchasesForAccountFunc func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Purchase], error)

	// GetSubscriptionFunc mocks the GetSubscription method.
	GetSubscriptionFunc func(ctx context.Context, id string) (*payments.Subscription, error)

	// GetSubscriptionByExternalIDFunc mocks the GetSubscriptionByExternalID method.
	GetSubscriptionByExternalIDFunc func(ctx context.Context, externalID string) (*payments.Subscription, error)

	// GetSubscriptionsForAccountFunc mocks the GetSubscriptionsForAccount method.
	GetSubscriptionsForAccountFunc func(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Subscription], error)

	// ProductExistsFunc mocks the ProductExists method.
	ProductExistsFunc func(ctx context.Context, id string) (bool, error)

	// UpdateProductFunc mocks the UpdateProduct method.
	UpdateProductFunc func(ctx context.Context, product *payments.Product) error

	// UpdateSubscriptionFunc mocks the UpdateSubscription method.
	UpdateSubscriptionFunc func(ctx context.Context, sub *payments.Subscription) error

	// UpdateSubscriptionStatusFunc mocks the UpdateSubscriptionStatus method.
	UpdateSubscriptionStatusFunc func(ctx context.Context, id string, status string) error

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveProduct holds details about calls to the ArchiveProduct method.
		ArchiveProduct []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// ArchiveSubscription holds details about calls to the ArchiveSubscription method.
		ArchiveSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// CreatePaymentTransaction holds details about calls to the CreatePaymentTransaction method.
		CreatePaymentTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *payments.PaymentTransactionDatabaseCreationInput
		}
		// CreateProduct holds details about calls to the CreateProduct method.
		CreateProduct []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *payments.ProductDatabaseCreationInput
		}
		// CreatePurchase holds details about calls to the CreatePurchase method.
		CreatePurchase []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *payments.PurchaseDatabaseCreationInput
		}
		// CreateSubscription holds details about calls to the CreateSubscription method.
		CreateSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *payments.SubscriptionDatabaseCreationInput
		}
		// GetPaymentTransactionsForAccount holds details about calls to the GetPaymentTransactionsForAccount method.
		GetPaymentTransactionsForAccount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// GetProduct holds details about calls to the GetProduct method.
		GetProduct []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetProductByExternalID holds details about calls to the GetProductByExternalID method.
		GetProductByExternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExternalProductID is the externalProductID argument value.
			ExternalProductID string
		}
		// GetProducts holds details about calls to the GetProducts method.
		GetProducts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// GetPurchase holds details about calls to the GetPurchase method.
		GetPurchase []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetPurchasesForAccount holds details about calls to the GetPurchasesForAccount method.
		GetPurchasesForAccount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// GetSubscription holds details about calls to the GetSubscription method.
		GetSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetSubscriptionByExternalID holds details about calls to the GetSubscriptionByExternalID method.
		GetSubscriptionByExternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExternalID is the externalID argument value.
			ExternalID string
		}
		// GetSubscriptionsForAccount holds details about calls to the GetSubscriptionsForAccount method.
		GetSubscriptionsForAccount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ProductExists holds details about calls to the ProductExists method.
		ProductExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// UpdateProduct holds details about calls to the UpdateProduct method.
		UpdateProduct []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Product is the product argument value.
			Product *payments.Product
		}
		// UpdateSubscription holds details about calls to the UpdateSubscription method.
		UpdateSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sub is the sub argument value.
			Sub *payments.Subscription
		}
		// UpdateSubscriptionStatus holds details about calls to the UpdateSubscriptionStatus method.
		UpdateSubscriptionStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Status is the status argument value.
			Status string
		}
	}
	lockArchiveProduct                   sync.RWMutex
	lockArchiveSubscription              sync.RWMutex
	lockCreatePaymentTransaction         sync.RWMutex
	lockCreateProduct                    sync.RWMutex
	lockCreatePurchase                   sync.RWMutex
	lockCreateSubscription               sync.RWMutex
	lockGetPaymentTransactionsForAccount sync.RWMutex
	lockGetProduct                       sync.RWMutex
	lockGetProductByExternalID           sync.RWMutex
	lockGetProducts                      sync.RWMutex
	lockGetPurchase                      sync.RWMutex
	lockGetPurchasesForAccount           sync.RWMutex
	lockGetSubscription                  sync.RWMutex
	lockGetSubscriptionByExternalID      sync.RWMutex
	lockGetSubscriptionsForAccount       sync.RWMutex
	lockProductExists                    sync.RWMutex
	lockUpdateProduct                    sync.RWMutex
	lockUpdateSubscription               sync.RWMutex
	lockUpdateSubscriptionStatus         sync.RWMutex
}

// ArchiveProduct calls ArchiveProductFunc.
func (mock *RepositoryMock) ArchiveProduct(ctx context.Context, id string) error {
	if mock.ArchiveProductFunc == nil {
		panic("RepositoryMock.ArchiveProductFunc: method is nil but Repository.ArchiveProduct was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockArchiveProduct.Lock()
	mock.calls.ArchiveProduct = append(mock.calls.ArchiveProduct, callInfo)
	mock.lockArchiveProduct.Unlock()
	return mock.ArchiveProductFunc(ctx, id)
}

// ArchiveProductCalls gets all the calls that were made to ArchiveProduct.
// Check the length with:
//
//	len(mockedRepository.ArchiveProductCalls())
func (mock *RepositoryMock) ArchiveProductCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockArchiveProduct.RLock()
	calls = mock.calls.ArchiveProduct
	mock.lockArchiveProduct.RUnlock()
	return calls
}

// ArchiveSubscription calls ArchiveSubscriptionFunc.
func (mock *RepositoryMock) ArchiveSubscription(ctx context.Context, id string) error {
	if mock.ArchiveSubscriptionFunc == nil {
		panic("RepositoryMock.ArchiveSubscriptionFunc: method is nil but Repository.ArchiveSubscription was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockArchiveSubscription.Lock()
	mock.calls.ArchiveSubscription = append(mock.calls.ArchiveSubscription, callInfo)
	mock.lockArchiveSubscription.Unlock()
	return mock.ArchiveSubscriptionFunc(ctx, id)
}

// ArchiveSubscriptionCalls gets all the calls that were made to ArchiveSubscription.
// Check the length with:
//
//	len(mockedRepository.ArchiveSubscriptionCalls())
func (mock *RepositoryMock) ArchiveSubscriptionCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockArchiveSubscription.RLock()
	calls = mock.calls.ArchiveSubscription
	mock.lockArchiveSubscription.RUnlock()
	return calls
}

// CreatePaymentTransaction calls CreatePaymentTransactionFunc.
func (mock *RepositoryMock) CreatePaymentTransaction(ctx context.Context, input *payments.PaymentTransactionDatabaseCreationInput) (*payments.PaymentTransaction, error) {
	if mock.CreatePaymentTransactionFunc == nil {
		panic("RepositoryMock.CreatePaymentTransactionFunc: method is nil but Repository.CreatePaymentTransaction was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *payments.PaymentTransactionDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreatePaymentTransaction.Lock()
	mock.calls.CreatePaymentTransaction = append(mock.calls.CreatePaymentTransaction, callInfo)
	mock.lockCreatePaymentTransaction.Unlock()
	return mock.CreatePaymentTransactionFunc(ctx, input)
}

// CreatePaymentTransactionCalls gets all the calls that were made to CreatePaymentTransaction.
// Check the length with:
//
//	len(mockedRepository.CreatePaymentTransactionCalls())
func (mock *RepositoryMock) CreatePaymentTransactionCalls() []struct {
	Ctx   context.Context
	Input *payments.PaymentTransactionDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *payments.PaymentTransactionDatabaseCreationInput
	}
	mock.lockCreatePaymentTransaction.RLock()
	calls = mock.calls.CreatePaymentTransaction
	mock.lockCreatePaymentTransaction.RUnlock()
	return calls
}

// CreateProduct calls CreateProductFunc.
func (mock *RepositoryMock) CreateProduct(ctx context.Context, input *payments.ProductDatabaseCreationInput) (*payments.Product, error) {
	if mock.CreateProductFunc == nil {
		panic("RepositoryMock.CreateProductFunc: method is nil but Repository.CreateProduct was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *payments.ProductDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateProduct.Lock()
	mock.calls.CreateProduct = append(mock.calls.CreateProduct, callInfo)
	mock.lockCreateProduct.Unlock()
	return mock.CreateProductFunc(ctx, input)
}

// CreateProductCalls gets all the calls that were made to CreateProduct.
// Check the length with:
//
//	len(mockedRepository.CreateProductCalls())
func (mock *RepositoryMock) CreateProductCalls() []struct {
	Ctx   context.Context
	Input *payments.ProductDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *payments.ProductDatabaseCreationInput
	}
	mock.lockCreateProduct.RLock()
	calls = mock.calls.CreateProduct
	mock.lockCreateProduct.RUnlock()
	return calls
}

// CreatePurchase calls CreatePurchaseFunc.
func (mock *RepositoryMock) CreatePurchase(ctx context.Context, input *payments.PurchaseDatabaseCreationInput) (*payments.Purchase, error) {
	if mock.CreatePurchaseFunc == nil {
		panic("RepositoryMock.CreatePurchaseFunc: method is nil but Repository.CreatePurchase was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *payments.PurchaseDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreatePurchase.Lock()
	mock.calls.CreatePurchase = append(mock.calls.CreatePurchase, callInfo)
	mock.lockCreatePurchase.Unlock()
	return mock.CreatePurchaseFunc(ctx, input)
}

// CreatePurchaseCalls gets all the calls that were made to CreatePurchase.
// Check the length with:
//
//	len(mockedRepository.CreatePurchaseCalls())
func (mock *RepositoryMock) CreatePurchaseCalls() []struct {
	Ctx   context.Context
	Input *payments.PurchaseDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *payments.PurchaseDatabaseCreationInput
	}
	mock.lockCreatePurchase.RLock()
	calls = mock.calls.CreatePurchase
	mock.lockCreatePurchase.RUnlock()
	return calls
}

// CreateSubscription calls CreateSubscriptionFunc.
func (mock *RepositoryMock) CreateSubscription(ctx context.Context, input *payments.SubscriptionDatabaseCreationInput) (*payments.Subscription, error) {
	if mock.CreateSubscriptionFunc == nil {
		panic("RepositoryMock.CreateSubscriptionFunc: method is nil but Repository.CreateSubscription was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *payments.SubscriptionDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateSubscription.Lock()
	mock.calls.CreateSubscription = append(mock.calls.CreateSubscription, callInfo)
	mock.lockCreateSubscription.Unlock()
	return mock.CreateSubscriptionFunc(ctx, input)
}

// CreateSubscriptionCalls gets all the calls that were made to CreateSubscription.
// Check the length with:
//
//	len(mockedRepository.CreateSubscriptionCalls())
func (mock *RepositoryMock) CreateSubscriptionCalls() []struct {
	Ctx   context.Context
	Input *payments.SubscriptionDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *payments.SubscriptionDatabaseCreationInput
	}
	mock.lockCreateSubscription.RLock()
	calls = mock.calls.CreateSubscription
	mock.lockCreateSubscription.RUnlock()
	return calls
}

// GetPaymentTransactionsForAccount calls GetPaymentTransactionsForAccountFunc.
func (mock *RepositoryMock) GetPaymentTransactionsForAccount(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.PaymentTransaction], error) {
	if mock.GetPaymentTransactionsForAccountFunc == nil {
		panic("RepositoryMock.GetPaymentTransactionsForAccountFunc: method is nil but Repository.GetPaymentTransactionsForAccount was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}{
		Ctx:       ctx,
		AccountID: accountID,
		Filter:    filter,
	}
	mock.lockGetPaymentTransactionsForAccount.Lock()
	mock.calls.GetPaymentTransactionsForAccount = append(mock.calls.GetPaymentTransactionsForAccount, callInfo)
	mock.lockGetPaymentTransactionsForAccount.Unlock()
	return mock.GetPaymentTransactionsForAccountFunc(ctx, accountID, filter)
}

// GetPaymentTransactionsForAccountCalls gets all the calls that were made to GetPaymentTransactionsForAccount.
// Check the length with:
//
//	len(mockedRepository.GetPaymentTransactionsForAccountCalls())
func (mock *RepositoryMock) GetPaymentTransactionsForAccountCalls() []struct {
	Ctx       context.Context
	AccountID string
	Filter    *filtering.QueryFilter
} {
	var calls []struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}
	mock.lockGetPaymentTransactionsForAccount.RLock()
	calls = mock.calls.GetPaymentTransactionsForAccount
	mock.lockGetPaymentTransactionsForAccount.RUnlock()
	return calls
}

// GetProduct calls GetProductFunc.
func (mock *RepositoryMock) GetProduct(ctx context.Context, id string) (*payments.Product, error) {
	if mock.GetProductFunc == nil {
		panic("RepositoryMock.GetProductFunc: method is nil but Repository.GetProduct was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetProduct.Lock()
	mock.calls.GetProduct = append(mock.calls.GetProduct, callInfo)
	mock.lockGetProduct.Unlock()
	return mock.GetProductFunc(ctx, id)
}

// GetProductCalls gets all the calls that were made to GetProduct.
// Check the length with:
//
//	len(mockedRepository.GetProductCalls())
func (mock *RepositoryMock) GetProductCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetProduct.RLock()
	calls = mock.calls.GetProduct
	mock.lockGetProduct.RUnlock()
	return calls
}

// GetProductByExternalID calls GetProductByExternalIDFunc.
func (mock *RepositoryMock) GetProductByExternalID(ctx context.Context, externalProductID string) (*payments.Product, error) {
	if mock.GetProductByExternalIDFunc == nil {
		panic("RepositoryMock.GetProductByExternalIDFunc: method is nil but Repository.GetProductByExternalID was just called")
	}
	callInfo := struct {
		Ctx               context.Context
		ExternalProductID string
	}{
		Ctx:               ctx,
		ExternalProductID: externalProductID,
	}
	mock.lockGetProductByExternalID.Lock()
	mock.calls.GetProductByExternalID = append(mock.calls.GetProductByExternalID, callInfo)
	mock.lockGetProductByExternalID.Unlock()
	return mock.GetProductByExternalIDFunc(ctx, externalProductID)
}

// GetProductByExternalIDCalls gets all the calls that were made to GetProductByExternalID.
// Check the length with:
//
//	len(mockedRepository.GetProductByExternalIDCalls())
func (mock *RepositoryMock) GetProductByExternalIDCalls() []struct {
	Ctx               context.Context
	ExternalProductID string
} {
	var calls []struct {
		Ctx               context.Context
		ExternalProductID string
	}
	mock.lockGetProductByExternalID.RLock()
	calls = mock.calls.GetProductByExternalID
	mock.lockGetProductByExternalID.RUnlock()
	return calls
}

// GetProducts calls GetProductsFunc.
func (mock *RepositoryMock) GetProducts(ctx context.Context, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Product], error) {
	if mock.GetProductsFunc == nil {
		panic("RepositoryMock.GetProductsFunc: method is nil but Repository.GetProducts was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetProducts.Lock()
	mock.calls.GetProducts = append(mock.calls.GetProducts, callInfo)
	mock.lockGetProducts.Unlock()
	return mock.GetProductsFunc(ctx, filter)
}

// GetProductsCalls gets all the calls that were made to GetProducts.
// Check the length with:
//
//	len(mockedRepository.GetProductsCalls())
func (mock *RepositoryMock) GetProductsCalls() []struct {
	Ctx    context.Context
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter *filtering.QueryFilter
	}
	mock.lockGetProducts.RLock()
	calls = mock.calls.GetProducts
	mock.lockGetProducts.RUnlock()
	return calls
}

// GetPurchase calls GetPurchaseFunc.
func (mock *RepositoryMock) GetPurchase(ctx context.Context, id string) (*payments.Purchase, error) {
	if mock.GetPurchaseFunc == nil {
		panic("RepositoryMock.GetPurchaseFunc: method is nil but Repository.GetPurchase was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetPurchase.Lock()
	mock.calls.GetPurchase = append(mock.calls.GetPurchase, callInfo)
	mock.lockGetPurchase.Unlock()
	return mock.GetPurchaseFunc(ctx, id)
}

// GetPurchaseCalls gets all the calls that were made to GetPurchase.
// Check the length with:
//
//	len(mockedRepository.GetPurchaseCalls())
func (mock *RepositoryMock) GetPurchaseCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetPurchase.RLock()
	calls = mock.calls.GetPurchase
	mock.lockGetPurchase.RUnlock()
	return calls
}

// GetPurchasesForAccount calls GetPurchasesForAccountFunc.
func (mock *RepositoryMock) GetPurchasesForAccount(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Purchase], error) {
	if mock.GetPurchasesForAccountFunc == nil {
		panic("RepositoryMock.GetPurchasesForAccountFunc: method is nil but Repository.GetPurchasesForAccount was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}{
		Ctx:       ctx,
		AccountID: accountID,
		Filter:    filter,
	}
	mock.lockGetPurchasesForAccount.Lock()
	mock.calls.GetPurchasesForAccount = append(mock.calls.GetPurchasesForAccount, callInfo)
	mock.lockGetPurchasesForAccount.Unlock()
	return mock.GetPurchasesForAccountFunc(ctx, accountID, filter)
}

// GetPurchasesForAccountCalls gets all the calls that were made to GetPurchasesForAccount.
// Check the length with:
//
//	len(mockedRepository.GetPurchasesForAccountCalls())
func (mock *RepositoryMock) GetPurchasesForAccountCalls() []struct {
	Ctx       context.Context
	AccountID string
	Filter    *filtering.QueryFilter
} {
	var calls []struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}
	mock.lockGetPurchasesForAccount.RLock()
	calls = mock.calls.GetPurchasesForAccount
	mock.lockGetPurchasesForAccount.RUnlock()
	return calls
}

// GetSubscription calls GetSubscriptionFunc.
func (mock *RepositoryMock) GetSubscription(ctx context.Context, id string) (*payments.Subscription, error) {
	if mock.GetSubscriptionFunc == nil {
		panic("RepositoryMock.GetSubscriptionFunc: method is nil but Repository.GetSubscription was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetSubscription.Lock()
	mock.calls.GetSubscription = append(mock.calls.GetSubscription, callInfo)
	mock.lockGetSubscription.Unlock()
	return mock.GetSubscriptionFunc(ctx, id)
}

// GetSubscriptionCalls gets all the calls that were made to GetSubscription.
// Check the length with:
//
//	len(mockedRepository.GetSubscriptionCalls())
func (mock *RepositoryMock) GetSubscriptionCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetSubscription.RLock()
	calls = mock.calls.GetSubscription
	mock.lockGetSubscription.RUnlock()
	return calls
}

// GetSubscriptionByExternalID calls GetSubscriptionByExternalIDFunc.
func (mock *RepositoryMock) GetSubscriptionByExternalID(ctx context.Context, externalID string) (*payments.Subscription, error) {
	if mock.GetSubscriptionByExternalIDFunc == nil {
		panic("RepositoryMock.GetSubscriptionByExternalIDFunc: method is nil but Repository.GetSubscriptionByExternalID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ExternalID string
	}{
		Ctx:        ctx,
		ExternalID: externalID,
	}
	mock.lockGetSubscriptionByExternalID.Lock()
	mock.calls.GetSubscriptionByExternalID = append(mock.calls.GetSubscriptionByExternalID, callInfo)
	mock.lockGetSubscriptionByExternalID.Unlock()
	return mock.GetSubscriptionByExternalIDFunc(ctx, externalID)
}

// GetSubscriptionByExternalIDCalls gets all the calls that were made to GetSubscriptionByExternalID.
// Check the length with:
//
//	len(mockedRepository.GetSubscriptionByExternalIDCalls())
func (mock *RepositoryMock) GetSubscriptionByExternalIDCalls() []struct {
	Ctx        context.Context
	ExternalID string
} {
	var calls []struct {
		Ctx        context.Context
		ExternalID string
	}
	mock.lockGetSubscriptionByExternalID.RLock()
	calls = mock.calls.GetSubscriptionByExternalID
	mock.lockGetSubscriptionByExternalID.RUnlock()
	return calls
}

// GetSubscriptionsForAccount calls GetSubscriptionsForAccountFunc.
func (mock *RepositoryMock) GetSubscriptionsForAccount(ctx context.Context, accountID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[payments.Subscription], error) {
	if mock.GetSubscriptionsForAccountFunc == nil {
		panic("RepositoryMock.GetSubscriptionsForAccountFunc: method is nil but Repository.GetSubscriptionsForAccount was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}{
		Ctx:       ctx,
		AccountID: accountID,
		Filter:    filter,
	}
	mock.lockGetSubscriptionsForAccount.Lock()
	mock.calls.GetSubscriptionsForAccount = append(mock.calls.GetSubscriptionsForAccount, callInfo)
	mock.lockGetSubscriptionsForAccount.Unlock()
	return mock.GetSubscriptionsForAccountFunc(ctx, accountID, filter)
}

// GetSubscriptionsForAccountCalls gets all the calls that were made to GetSubscriptionsForAccount.
// Check the length with:
//
//	len(mockedRepository.GetSubscriptionsForAccountCalls())
func (mock *RepositoryMock) GetSubscriptionsForAccountCalls() []struct {
	Ctx       context.Context
	AccountID string
	Filter    *filtering.QueryFilter
} {
	var calls []struct {
		Ctx       context.Context
		AccountID string
		Filter    *filtering.QueryFilter
	}
	mock.lockGetSubscriptionsForAccount.RLock()
	calls = mock.calls.GetSubscriptionsForAccount
	mock.lockGetSubscriptionsForAccount.RUnlock()
	return calls
}

// ProductExists calls ProductExistsFunc.
func (mock *RepositoryMock) ProductExists(ctx context.Context, id string) (bool, error) {
	if mock.ProductExistsFunc == nil {
		panic("RepositoryMock.ProductExistsFunc: method is nil but Repository.ProductExists was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockProductExists.Lock()
	mock.calls.ProductExists = append(mock.calls.ProductExists, callInfo)
	mock.lockProductExists.Unlock()
	return mock.ProductExistsFunc(ctx, id)
}

// ProductExistsCalls gets all the calls that were made to ProductExists.
// Check the length with:
//
//	len(mockedRepository.ProductExistsCalls())
func (mock *RepositoryMock) ProductExistsCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockProductExists.RLock()
	calls = mock.calls.ProductExists
	mock.lockProductExists.RUnlock()
	return calls
}

// UpdateProduct calls UpdateProductFunc.
func (mock *RepositoryMock) UpdateProduct(ctx context.Context, product *payments.Product) error {
	if mock.UpdateProductFunc == nil {
		panic("RepositoryMock.UpdateProductFunc: method is nil but Repository.UpdateProduct was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Product *payments.Product
	}{
		Ctx:     ctx,
		Product: product,
	}
	mock.lockUpdateProduct.Lock()
	mock.calls.UpdateProduct = append(mock.calls.UpdateProduct, callInfo)
	mock.lockUpdateProduct.Unlock()
	return mock.UpdateProductFunc(ctx, product)
}

// UpdateProductCalls gets all the calls that were made to UpdateProduct.
// Check the length with:
//
//	len(mockedRepository.UpdateProductCalls())
func (mock *RepositoryMock) UpdateProductCalls() []struct {
	Ctx     context.Context
	Product *payments.Product
} {
	var calls []struct {
		Ctx     context.Context
		Product *payments.Product
	}
	mock.lockUpdateProduct.RLock()
	calls = mock.calls.UpdateProduct
	mock.lockUpdateProduct.RUnlock()
	return calls
}

// UpdateSubscription calls UpdateSubscriptionFunc.
func (mock *RepositoryMock) UpdateSubscription(ctx context.Context, sub *payments.Subscription) error {
	if mock.UpdateSubscriptionFunc == nil {
		panic("RepositoryMock.UpdateSubscriptionFunc: method is nil but Repository.UpdateSubscription was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Sub *payments.Subscription
	}{
		Ctx: ctx,
		Sub: sub,
	}
	mock.lockUpdateSubscription.Lock()
	mock.calls.UpdateSubscription = append(mock.calls.UpdateSubscription, callInfo)
	mock.lockUpdateSubscription.Unlock()
	return mock.UpdateSubscriptionFunc(ctx, sub)
}

// UpdateSubscriptionCalls gets all the calls that were made to UpdateSubscription.
// Check the length with:
//
//	len(mockedRepository.UpdateSubscriptionCalls())
func (mock *RepositoryMock) UpdateSubscriptionCalls() []struct {
	Ctx context.Context
	Sub *payments.Subscription
} {
	var calls []struct {
		Ctx context.Context
		Sub *payments.Subscription
	}
	mock.lockUpdateSubscription.RLock()
	calls = mock.calls.UpdateSubscription
	mock.lockUpdateSubscription.RUnlock()
	return calls
}

// UpdateSubscriptionStatus calls UpdateSubscriptionStatusFunc.
func (mock *RepositoryMock) UpdateSubscriptionStatus(ctx context.Context, id string, status string) error {
	if mock.UpdateSubscriptionStatusFunc == nil {
		panic("RepositoryMock.UpdateSubscriptionStatusFunc: method is nil but Repository.UpdateSubscriptionStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		Status string
	}{
		Ctx:    ctx,
		ID:     id,
		Status: status,
	}
	mock.lockUpdateSubscriptionStatus.Lock()
	mock.calls.UpdateSubscriptionStatus = append(mock.calls.UpdateSubscriptionStatus, callInfo)
	mock.lockUpdateSubscriptionStatus.Unlock()
	return mock.UpdateSubscriptionStatusFunc(ctx, id, status)
}

// UpdateSubscriptionStatusCalls gets all the calls that were made to UpdateSubscriptionStatus.
// Check the length with:
//
//	len(mockedRepository.UpdateSubscriptionStatusCalls())
func (mock *RepositoryMock) UpdateSubscriptionStatusCalls() []struct {
	Ctx    context.Context
	ID     string
	Status string
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		Status string
	}
	mock.lockUpdateSubscriptionStatus.RLock()
	calls = mock.calls.UpdateSubscriptionStatus
	mock.lockUpdateSubscriptionStatus.RUnlock()
	return calls
}
