package grpc

import (
	"context"
	"database/sql"
	"errors"
	"testing"

	"github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/domain/notifications"
	notificationsfakes "github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/domain/notifications/fakes"
	notificationsmock "github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/domain/notifications/mock"
	grpcfiltering "github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/grpc/generated/filtering"
	notificationssvc "github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/grpc/generated/services/notifications"

	"github.com/primandproper/platform-go/v7/filtering"

	"github.com/stretchr/testify/assert"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func TestServiceImpl_RegisterDeviceToken(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()

		fakeToken := notificationsfakes.BuildFakeUserDeviceToken()

		mockRepo := &notificationsmock.RepositoryMock{
			CreateUserDeviceTokenFunc: func(_ context.Context, input *notifications.UserDeviceTokenDatabaseCreationInput) (*notifications.UserDeviceToken, error) {
				assert.NotNil(t, input)

				return fakeToken, nil
			},
		}
		service := buildTestService(t, mockRepo)

		request := &notificationssvc.RegisterDeviceTokenRequest{
			Input: &notificationssvc.UserDeviceTokenCreationRequestInput{
				DeviceToken: fakeToken.DeviceToken,
				Platform:    fakeToken.Platform,
			},
		}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)
		assert.NotNil(t, response.Created)
		assert.Equal(t, fakeToken.DeviceToken, response.Created.DeviceToken)
		assert.Equal(t, fakeToken.Platform, response.Created.Platform)
		// ID is generated by handler, so we just check it's set
		assert.NotEmpty(t, response.Created.Id)

		assert.Len(t, mockRepo.CreateUserDeviceTokenCalls(), 1)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		request := &notificationssvc.RegisterDeviceTokenRequest{
			Input: &notificationssvc.UserDeviceTokenCreationRequestInput{
				DeviceToken: "token",
				Platform:    notifications.UserDeviceTokenPlatformIOS,
			},
		}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})

	t.Run("nil input", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		mockRepo := &notificationsmock.RepositoryMock{}
		service := buildTestService(t, mockRepo)

		request := &notificationssvc.RegisterDeviceTokenRequest{}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.InvalidArgument, status.Code(err))
		assert.Empty(t, mockRepo.CreateUserDeviceTokenCalls())
	})

	t.Run("repository error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()

		mockRepo := &notificationsmock.RepositoryMock{
			CreateUserDeviceTokenFunc: func(_ context.Context, _ *notifications.UserDeviceTokenDatabaseCreationInput) (*notifications.UserDeviceToken, error) {
				return nil, errors.New("repository error")
			},
		}
		service := buildTestService(t, mockRepo)

		request := &notificationssvc.RegisterDeviceTokenRequest{
			Input: &notificationssvc.UserDeviceTokenCreationRequestInput{
				DeviceToken: "token",
				Platform:    notifications.UserDeviceTokenPlatformIOS,
			},
		}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Internal, status.Code(err))

		assert.Len(t, mockRepo.CreateUserDeviceTokenCalls(), 1)
	})
}

func TestServiceImpl_GetUserDeviceToken(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()

		fakeToken := notificationsfakes.BuildFakeUserDeviceToken()
		tokenID := fakeToken.ID

		mockRepo := &notificationsmock.RepositoryMock{
			GetUserDeviceTokenFunc: func(_ context.Context, userID, actualTokenID string) (*notifications.UserDeviceToken, error) {
				assert.Equal(t, testSessionUserID, userID)
				assert.Equal(t, tokenID, actualTokenID)

				return fakeToken, nil
			},
		}
		service := buildTestService(t, mockRepo)

		request := &notificationssvc.GetUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.GetUserDeviceToken(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)
		assert.NotNil(t, response.Result)
		assert.Equal(t, fakeToken.ID, response.Result.Id)
		assert.Equal(t, fakeToken.DeviceToken, response.Result.DeviceToken)

		assert.Len(t, mockRepo.GetUserDeviceTokenCalls(), 1)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		request := &notificationssvc.GetUserDeviceTokenRequest{
			UserDeviceTokenId: "test-token-id",
		}

		response, err := service.GetUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})

	t.Run("not found", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()

		tokenID := "nonexistent-token"

		mockRepo := &notificationsmock.RepositoryMock{
			GetUserDeviceTokenFunc: func(_ context.Context, userID, actualTokenID string) (*notifications.UserDeviceToken, error) {
				assert.Equal(t, testSessionUserID, userID)
				assert.Equal(t, tokenID, actualTokenID)

				return nil, sql.ErrNoRows
			},
		}
		service := buildTestService(t, mockRepo)

		request := &notificationssvc.GetUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.GetUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.NotFound, status.Code(err))

		assert.Len(t, mockRepo.GetUserDeviceTokenCalls(), 1)
	})
}

func TestServiceImpl_GetUserDeviceTokens(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()

		fakeTokens := notificationsfakes.BuildFakeUserDeviceTokensList()
		pageSize := uint8(20)
		filter := &filtering.QueryFilter{
			MaxResponseSize: &pageSize,
		}

		mockRepo := &notificationsmock.RepositoryMock{
			GetUserDeviceTokensFunc: func(_ context.Context, userID string, actualFilter *filtering.QueryFilter, platformFilter *string) (*filtering.QueryFilteredResult[notifications.UserDeviceToken], error) {
				assert.Equal(t, testSessionUserID, userID)
				assert.NotNil(t, actualFilter)
				assert.Nil(t, platformFilter)

				return fakeTokens, nil
			},
		}
		service := buildTestService(t, mockRepo)

		grpcPageSize := uint32(*filter.MaxResponseSize)
		request := &notificationssvc.GetUserDeviceTokensRequest{
			Filter: &grpcfiltering.QueryFilter{
				MaxResponseSize: &grpcPageSize,
			},
		}

		response, err := service.GetUserDeviceTokens(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)
		assert.Len(t, response.Results, len(fakeTokens.Data))

		assert.Len(t, mockRepo.GetUserDeviceTokensCalls(), 1)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		grpcPageSize := uint32(20)
		request := &notificationssvc.GetUserDeviceTokensRequest{
			Filter: &grpcfiltering.QueryFilter{
				MaxResponseSize: &grpcPageSize,
			},
		}

		response, err := service.GetUserDeviceTokens(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})
}

func TestServiceImpl_ArchiveUserDeviceToken(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()

		tokenID := notificationsfakes.BuildFakeID()

		mockRepo := &notificationsmock.RepositoryMock{
			ArchiveUserDeviceTokenFunc: func(_ context.Context, userID, actualTokenID string) error {
				assert.Equal(t, testSessionUserID, userID)
				assert.Equal(t, tokenID, actualTokenID)

				return nil
			},
		}
		service := buildTestService(t, mockRepo)

		request := &notificationssvc.ArchiveUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.ArchiveUserDeviceToken(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)

		assert.Len(t, mockRepo.ArchiveUserDeviceTokenCalls(), 1)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		request := &notificationssvc.ArchiveUserDeviceTokenRequest{
			UserDeviceTokenId: "test-token-id",
		}

		response, err := service.ArchiveUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})

	t.Run("not found", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()

		tokenID := "nonexistent-token"

		mockRepo := &notificationsmock.RepositoryMock{
			ArchiveUserDeviceTokenFunc: func(_ context.Context, userID, actualTokenID string) error {
				assert.Equal(t, testSessionUserID, userID)
				assert.Equal(t, tokenID, actualTokenID)

				return sql.ErrNoRows
			},
		}
		service := buildTestService(t, mockRepo)

		request := &notificationssvc.ArchiveUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.ArchiveUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.NotFound, status.Code(err))

		assert.Len(t, mockRepo.ArchiveUserDeviceTokenCalls(), 1)
	})
}
