// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/dataprivacy"

	"github.com/primandproper/platform-go/v9/filtering"
)

// Ensure, that RepositoryMock does implement dataprivacy.Repository.
// If this is not the case, regenerate this file with moq.
var _ dataprivacy.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of dataprivacy.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked dataprivacy.Repository
//		mockedRepository := &RepositoryMock{
//			ArchiveUserDataDisclosureFunc: func(ctx context.Context, disclosureID string) error {
//				panic("mock out the ArchiveUserDataDisclosure method")
//			},
//			CreateUserDataDisclosureFunc: func(ctx context.Context, input *dataprivacy.UserDataDisclosureCreationInput) (*dataprivacy.UserDataDisclosure, error) {
//				panic("mock out the CreateUserDataDisclosure method")
//			},
//			DeleteUserFunc: func(ctx context.Context, userID string) error {
//				panic("mock out the DeleteUser method")
//			},
//			FetchUserDataCollectionFunc: func(ctx context.Context, userID string) (*dataprivacy.UserDataCollection, error) {
//				panic("mock out the FetchUserDataCollection method")
//			},
//			GetUserDataDisclosureFunc: func(ctx context.Context, disclosureID string) (*dataprivacy.UserDataDisclosure, error) {
//				panic("mock out the GetUserDataDisclosure method")
//			},
//			GetUserDataDisclosuresForUserFunc: func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[dataprivacy.UserDataDisclosure], error) {
//				panic("mock out the GetUserDataDisclosuresForUser method")
//			},
//			MarkUserDataDisclosureCompletedFunc: func(ctx context.Context, disclosureID string, reportID string) error {
//				panic("mock out the MarkUserDataDisclosureCompleted method")
//			},
//			MarkUserDataDisclosureFailedFunc: func(ctx context.Context, disclosureID string) error {
//				panic("mock out the MarkUserDataDisclosureFailed method")
//			},
//		}
//
//		// use mockedRepository in code that requires dataprivacy.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// ArchiveUserDataDisclosureFunc mocks the ArchiveUserDataDisclosure method.
	ArchiveUserDataDisclosureFunc func(ctx context.Context, disclosureID string) error

	// CreateUserDataDisclosureFunc mocks the CreateUserDataDisclosure method.
	CreateUserDataDisclosureFunc func(ctx context.Context, input *dataprivacy.UserDataDisclosureCreationInput) (*dataprivacy.UserDataDisclosure, error)

	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(ctx context.Context, userID string) error

	// FetchUserDataCollectionFunc mocks the FetchUserDataCollection method.
	FetchUserDataCollectionFunc func(ctx context.Context, userID string) (*dataprivacy.UserDataCollection, error)

	// GetUserDataDisclosureFunc mocks the GetUserDataDisclosure method.
	GetUserDataDisclosureFunc func(ctx context.Context, disclosureID string) (*dataprivacy.UserDataDisclosure, error)

	// GetUserDataDisclosuresForUserFunc mocks the GetUserDataDisclosuresForUser method.
	GetUserDataDisclosuresForUserFunc func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[dataprivacy.UserDataDisclosure], error)

	// MarkUserDataDisclosureCompletedFunc mocks the MarkUserDataDisclosureCompleted method.
	MarkUserDataDisclosureCompletedFunc func(ctx context.Context, disclosureID string, reportID string) error

	// MarkUserDataDisclosureFailedFunc mocks the MarkUserDataDisclosureFailed method.
	MarkUserDataDisclosureFailedFunc func(ctx context.Context, disclosureID string) error

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveUserDataDisclosure holds details about calls to the ArchiveUserDataDisclosure method.
		ArchiveUserDataDisclosure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DisclosureID is the disclosureID argument value.
			DisclosureID string
		}
		// CreateUserDataDisclosure holds details about calls to the CreateUserDataDisclosure method.
		CreateUserDataDisclosure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *dataprivacy.UserDataDisclosureCreationInput
		}
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// FetchUserDataCollection holds details about calls to the FetchUserDataCollection method.
		FetchUserDataCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// GetUserDataDisclosure holds details about calls to the GetUserDataDisclosure method.
		GetUserDataDisclosure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DisclosureID is the disclosureID argument value.
			DisclosureID string
		}
		// GetUserDataDisclosuresForUser holds details about calls to the GetUserDataDisclosuresForUser method.
		GetUserDataDisclosuresForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// MarkUserDataDisclosureCompleted holds details about calls to the MarkUserDataDisclosureCompleted method.
		MarkUserDataDisclosureCompleted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DisclosureID is the disclosureID argument value.
			DisclosureID string
			// ReportID is the reportID argument value.
			ReportID string
		}
		// MarkUserDataDisclosureFailed holds details about calls to the MarkUserDataDisclosureFailed method.
		MarkUserDataDisclosureFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DisclosureID is the disclosureID argument value.
			DisclosureID string
		}
	}
	lockArchiveUserDataDisclosure       sync.RWMutex
	lockCreateUserDataDisclosure        sync.RWMutex
	lockDeleteUser                      sync.RWMutex
	lockFetchUserDataCollection         sync.RWMutex
	lockGetUserDataDisclosure           sync.RWMutex
	lockGetUserDataDisclosuresForUser   sync.RWMutex
	lockMarkUserDataDisclosureCompleted sync.RWMutex
	lockMarkUserDataDisclosureFailed    sync.RWMutex
}

// ArchiveUserDataDisclosure calls ArchiveUserDataDisclosureFunc.
func (mock *RepositoryMock) ArchiveUserDataDisclosure(ctx context.Context, disclosureID string) error {
	if mock.ArchiveUserDataDisclosureFunc == nil {
		panic("RepositoryMock.ArchiveUserDataDisclosureFunc: method is nil but Repository.ArchiveUserDataDisclosure was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DisclosureID string
	}{
		Ctx:          ctx,
		DisclosureID: disclosureID,
	}
	mock.lockArchiveUserDataDisclosure.Lock()
	mock.calls.ArchiveUserDataDisclosure = append(mock.calls.ArchiveUserDataDisclosure, callInfo)
	mock.lockArchiveUserDataDisclosure.Unlock()
	return mock.ArchiveUserDataDisclosureFunc(ctx, disclosureID)
}

// ArchiveUserDataDisclosureCalls gets all the calls that were made to ArchiveUserDataDisclosure.
// Check the length with:
//
//	len(mockedRepository.ArchiveUserDataDisclosureCalls())
func (mock *RepositoryMock) ArchiveUserDataDisclosureCalls() []struct {
	Ctx          context.Context
	DisclosureID string
} {
	var calls []struct {
		Ctx          context.Context
		DisclosureID string
	}
	mock.lockArchiveUserDataDisclosure.RLock()
	calls = mock.calls.ArchiveUserDataDisclosure
	mock.lockArchiveUserDataDisclosure.RUnlock()
	return calls
}

// CreateUserDataDisclosure calls CreateUserDataDisclosureFunc.
func (mock *RepositoryMock) CreateUserDataDisclosure(ctx context.Context, input *dataprivacy.UserDataDisclosureCreationInput) (*dataprivacy.UserDataDisclosure, error) {
	if mock.CreateUserDataDisclosureFunc == nil {
		panic("RepositoryMock.CreateUserDataDisclosureFunc: method is nil but Repository.CreateUserDataDisclosure was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *dataprivacy.UserDataDisclosureCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateUserDataDisclosure.Lock()
	mock.calls.CreateUserDataDisclosure = append(mock.calls.CreateUserDataDisclosure, callInfo)
	mock.lockCreateUserDataDisclosure.Unlock()
	return mock.CreateUserDataDisclosureFunc(ctx, input)
}

// CreateUserDataDisclosureCalls gets all the calls that were made to CreateUserDataDisclosure.
// Check the length with:
//
//	len(mockedRepository.CreateUserDataDisclosureCalls())
func (mock *RepositoryMock) CreateUserDataDisclosureCalls() []struct {
	Ctx   context.Context
	Input *dataprivacy.UserDataDisclosureCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *dataprivacy.UserDataDisclosureCreationInput
	}
	mock.lockCreateUserDataDisclosure.RLock()
	calls = mock.calls.CreateUserDataDisclosure
	mock.lockCreateUserDataDisclosure.RUnlock()
	return calls
}

// DeleteUser calls DeleteUserFunc.
func (mock *RepositoryMock) DeleteUser(ctx context.Context, userID string) error {
	if mock.DeleteUserFunc == nil {
		panic("RepositoryMock.DeleteUserFunc: method is nil but Repository.DeleteUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(ctx, userID)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedRepository.DeleteUserCalls())
func (mock *RepositoryMock) DeleteUserCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// FetchUserDataCollection calls FetchUserDataCollectionFunc.
func (mock *RepositoryMock) FetchUserDataCollection(ctx context.Context, userID string) (*dataprivacy.UserDataCollection, error) {
	if mock.FetchUserDataCollectionFunc == nil {
		panic("RepositoryMock.FetchUserDataCollectionFunc: method is nil but Repository.FetchUserDataCollection was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockFetchUserDataCollection.Lock()
	mock.calls.FetchUserDataCollection = append(mock.calls.FetchUserDataCollection, callInfo)
	mock.lockFetchUserDataCollection.Unlock()
	return mock.FetchUserDataCollectionFunc(ctx, userID)
}

// FetchUserDataCollectionCalls gets all the calls that were made to FetchUserDataCollection.
// Check the length with:
//
//	len(mockedRepository.FetchUserDataCollectionCalls())
func (mock *RepositoryMock) FetchUserDataCollectionCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockFetchUserDataCollection.RLock()
	calls = mock.calls.FetchUserDataCollection
	mock.lockFetchUserDataCollection.RUnlock()
	return calls
}

// GetUserDataDisclosure calls GetUserDataDisclosureFunc.
func (mock *RepositoryMock) GetUserDataDisclosure(ctx context.Context, disclosureID string) (*dataprivacy.UserDataDisclosure, error) {
	if mock.GetUserDataDisclosureFunc == nil {
		panic("RepositoryMock.GetUserDataDisclosureFunc: method is nil but Repository.GetUserDataDisclosure was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DisclosureID string
	}{
		Ctx:          ctx,
		DisclosureID: disclosureID,
	}
	mock.lockGetUserDataDisclosure.Lock()
	mock.calls.GetUserDataDisclosure = append(mock.calls.GetUserDataDisclosure, callInfo)
	mock.lockGetUserDataDisclosure.Unlock()
	return mock.GetUserDataDisclosureFunc(ctx, disclosureID)
}

// GetUserDataDisclosureCalls gets all the calls that were made to GetUserDataDisclosure.
// Check the length with:
//
//	len(mockedRepository.GetUserDataDisclosureCalls())
func (mock *RepositoryMock) GetUserDataDisclosureCalls() []struct {
	Ctx          context.Context
	DisclosureID string
} {
	var calls []struct {
		Ctx          context.Context
		DisclosureID string
	}
	mock.lockGetUserDataDisclosure.RLock()
	calls = mock.calls.GetUserDataDisclosure
	mock.lockGetUserDataDisclosure.RUnlock()
	return calls
}

// GetUserDataDisclosuresForUser calls GetUserDataDisclosuresForUserFunc.
func (mock *RepositoryMock) GetUserDataDisclosuresForUser(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[dataprivacy.UserDataDisclosure], error) {
	if mock.GetUserDataDisclosuresForUserFunc == nil {
		panic("RepositoryMock.GetUserDataDisclosuresForUserFunc: method is nil but Repository.GetUserDataDisclosuresForUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		UserID: userID,
		Filter: filter,
	}
	mock.lockGetUserDataDisclosuresForUser.Lock()
	mock.calls.GetUserDataDisclosuresForUser = append(mock.calls.GetUserDataDisclosuresForUser, callInfo)
	mock.lockGetUserDataDisclosuresForUser.Unlock()
	return mock.GetUserDataDisclosuresForUserFunc(ctx, userID, filter)
}

// GetUserDataDisclosuresForUserCalls gets all the calls that were made to GetUserDataDisclosuresForUser.
// Check the length with:
//
//	len(mockedRepository.GetUserDataDisclosuresForUserCalls())
func (mock *RepositoryMock) GetUserDataDisclosuresForUserCalls() []struct {
	Ctx    context.Context
	UserID string
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}
	mock.lockGetUserDataDisclosuresForUser.RLock()
	calls = mock.calls.GetUserDataDisclosuresForUser
	mock.lockGetUserDataDisclosuresForUser.RUnlock()
	return calls
}

// MarkUserDataDisclosureCompleted calls MarkUserDataDisclosureCompletedFunc.
func (mock *RepositoryMock) MarkUserDataDisclosureCompleted(ctx context.Context, disclosureID string, reportID string) error {
	if mock.MarkUserDataDisclosureCompletedFunc == nil {
		panic("RepositoryMock.MarkUserDataDisclosureCompletedFunc: method is nil but Repository.MarkUserDataDisclosureCompleted was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DisclosureID string
		ReportID     string
	}{
		Ctx:          ctx,
		DisclosureID: disclosureID,
		ReportID:     reportID,
	}
	mock.lockMarkUserDataDisclosureCompleted.Lock()
	mock.calls.MarkUserDataDisclosureCompleted = append(mock.calls.MarkUserDataDisclosureCompleted, callInfo)
	mock.lockMarkUserDataDisclosureCompleted.Unlock()
	return mock.MarkUserDataDisclosureCompletedFunc(ctx, disclosureID, reportID)
}

// MarkUserDataDisclosureCompletedCalls gets all the calls that were made to MarkUserDataDisclosureCompleted.
// Check the length with:
//
//	len(mockedRepository.MarkUserDataDisclosureCompletedCalls())
func (mock *RepositoryMock) MarkUserDataDisclosureCompletedCalls() []struct {
	Ctx          context.Context
	DisclosureID string
	ReportID     string
} {
	var calls []struct {
		Ctx          context.Context
		DisclosureID string
		ReportID     string
	}
	mock.lockMarkUserDataDisclosureCompleted.RLock()
	calls = mock.calls.MarkUserDataDisclosureCompleted
	mock.lockMarkUserDataDisclosureCompleted.RUnlock()
	return calls
}

// MarkUserDataDisclosureFailed calls MarkUserDataDisclosureFailedFunc.
func (mock *RepositoryMock) MarkUserDataDisclosureFailed(ctx context.Context, disclosureID string) error {
	if mock.MarkUserDataDisclosureFailedFunc == nil {
		panic("RepositoryMock.MarkUserDataDisclosureFailedFunc: method is nil but Repository.MarkUserDataDisclosureFailed was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DisclosureID string
	}{
		Ctx:          ctx,
		DisclosureID: disclosureID,
	}
	mock.lockMarkUserDataDisclosureFailed.Lock()
	mock.calls.MarkUserDataDisclosureFailed = append(mock.calls.MarkUserDataDisclosureFailed, callInfo)
	mock.lockMarkUserDataDisclosureFailed.Unlock()
	return mock.MarkUserDataDisclosureFailedFunc(ctx, disclosureID)
}

// MarkUserDataDisclosureFailedCalls gets all the calls that were made to MarkUserDataDisclosureFailed.
// Check the length with:
//
//	len(mockedRepository.MarkUserDataDisclosureFailedCalls())
func (mock *RepositoryMock) MarkUserDataDisclosureFailedCalls() []struct {
	Ctx          context.Context
	DisclosureID string
} {
	var calls []struct {
		Ctx          context.Context
		DisclosureID string
	}
	mock.lockMarkUserDataDisclosureFailed.RLock()
	calls = mock.calls.MarkUserDataDisclosureFailed
	mock.lockMarkUserDataDisclosureFailed.RUnlock()
	return calls
}
