syntax = "proto3";

package uploaded_media;

import "common.proto";
import "primandproper/platform/filtering/v1/filtering.proto";
import "uploaded_media/uploaded_media_messages.proto";

option go_package = "github.com/primandproper/dinnerdonebetter/backend/internal/grpc/generated/services/uploaded_media";

// CreateUploadedMedia
message CreateUploadedMediaRequest {
  UploadedMediaCreationRequestInput input = 1;
}

message CreateUploadedMediaResponse {
  common.ResponseDetails response_details = 1;
  UploadedMedia created = 2;
}

// GetUploadedMedia
message GetUploadedMediaRequest {
  string uploaded_media_id = 1;
}

message GetUploadedMediaResponse {
  common.ResponseDetails response_details = 1;
  UploadedMedia result = 2;
}

// GetUploadedMediaWithIDs
message GetUploadedMediaWithIDsRequest {
  repeated string ids = 1;
}

message GetUploadedMediaWithIDsResponse {
  common.ResponseDetails response_details = 1;
  repeated UploadedMedia results = 2;
}

// GetUploadedMediaForUser
message GetUploadedMediaForUserRequest {
  string user_id = 1;
  primandproper.platform.filtering.v1.QueryFilter filter = 2;
}

message GetUploadedMediaForUserResponse {
  common.ResponseDetails response_details = 1;
  primandproper.platform.filtering.v1.Pagination pagination = 2;
  repeated UploadedMedia results = 3;
}

// ArchiveUploadedMedia
message ArchiveUploadedMediaRequest {
  string uploaded_media_id = 1;
}

message ArchiveUploadedMediaResponse {
  common.ResponseDetails response_details = 1;
}
