syntax = "proto3";

package issue_reports;

import "issue_reports/issue_reports_service_types.proto";

option go_package = "github.com/primandproper/dinnerdonebetter/backend/internal/grpc/generated/services/issue_reports";

service IssueReportsService {
  rpc AddCommentToIssueReport(AddCommentToIssueReportRequest) returns (AddCommentToIssueReportResponse);
  rpc CreateIssueReport(CreateIssueReportRequest) returns (CreateIssueReportResponse);
  rpc GetIssueReport(GetIssueReportRequest) returns (GetIssueReportResponse);
  rpc GetIssueReports(GetIssueReportsRequest) returns (GetIssueReportsResponse);
  rpc GetIssueReportsByStatus(GetIssueReportsByStatusRequest) returns (GetIssueReportsByStatusResponse);
  rpc GetIssueReportsBySubjectType(GetIssueReportsBySubjectTypeRequest) returns (GetIssueReportsBySubjectTypeResponse);
  rpc GetIssueReportsForSubject(GetIssueReportsForSubjectRequest) returns (GetIssueReportsForSubjectResponse);
  rpc UpdateIssueReport(UpdateIssueReportRequest) returns (UpdateIssueReportResponse);
  rpc TransitionIssueReport(TransitionIssueReportRequest) returns (TransitionIssueReportResponse);
  rpc ArchiveIssueReport(ArchiveIssueReportRequest) returns (ArchiveIssueReportResponse);
}
