// Code generated by cmd/tools/codegen/converters. DO NOT EDIT.

package converters

import (
	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/oauth"

	"github.com/primandproper/platform-go/v11/identifiers"
)

// ConvertOAuth2ClientToOAuth2ClientCreationRequestInput builds an OAuth2ClientCreationRequestInput from an OAuth2Client.
func ConvertOAuth2ClientToOAuth2ClientCreationRequestInput(x *oauth.OAuth2Client) *oauth.OAuth2ClientCreationRequestInput {
	return &oauth.OAuth2ClientCreationRequestInput{
		Name:         x.Name,
		Description:  x.Description,
		RedirectURIs: x.RedirectURIs,
	}
}

// ConvertOAuth2ClientToOAuth2ClientDatabaseCreationInput builds an OAuth2ClientDatabaseCreationInput from an OAuth2Client.
func ConvertOAuth2ClientToOAuth2ClientDatabaseCreationInput(x *oauth.OAuth2Client) *oauth.OAuth2ClientDatabaseCreationInput {
	return &oauth.OAuth2ClientDatabaseCreationInput{
		ID:           x.ID,
		Name:         x.Name,
		Description:  x.Description,
		ClientID:     x.ClientID,
		ClientSecret: x.ClientSecret,
		RedirectURIs: x.RedirectURIs,
	}
}

// ConvertOAuth2ClientCreationRequestInputToOAuth2ClientDatabaseCreationInput builds an OAuth2ClientDatabaseCreationInput from an OAuth2ClientCreationRequestInput.
func ConvertOAuth2ClientCreationRequestInputToOAuth2ClientDatabaseCreationInput(x *oauth.OAuth2ClientCreationRequestInput) *oauth.OAuth2ClientDatabaseCreationInput {
	return &oauth.OAuth2ClientDatabaseCreationInput{
		ID:          identifiers.New(),
		Name:        x.Name,
		Description: x.Description,

		// ClientID is left unset. Generated by the manager from the secret generator,
		// never taken from the request: a client that could choose its own ID could choose
		// another client's.

		// ClientSecret is left unset. Generated by the manager and stored only as its
		// SHA-256 digest; the plaintext is returned to the caller exactly once.
		RedirectURIs: x.RedirectURIs,
	}
}
