// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockauthn

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/authentication"
	"github.com/verygoodsoftwarenotvirus/dinnerdonebetter/backend/internal/domain/auth"
)

// Ensure, that ManagerMock does implement authentication.Manager.
// If this is not the case, regenerate this file with moq.
var _ authentication.Manager = &ManagerMock{}

// ManagerMock is a mock implementation of authentication.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked authentication.Manager
//		mockedManager := &ManagerMock{
//			ExchangeTokenForUserFunc: func(ctx context.Context, refreshToken string, desiredAccountID string) (*auth.TokenResponse, error) {
//				panic("mock out the ExchangeTokenForUser method")
//			},
//			ProcessLoginFunc: func(ctx context.Context, adminOnly bool, loginData *auth.UserLoginInput, meta *authentication.LoginMetadata) (*auth.TokenResponse, error) {
//				panic("mock out the ProcessLogin method")
//			},
//			ProcessPasskeyLoginFunc: func(ctx context.Context, userID string, desiredAccountID string, meta *authentication.LoginMetadata) (*auth.TokenResponse, error) {
//				panic("mock out the ProcessPasskeyLogin method")
//			},
//		}
//
//		// use mockedManager in code that requires authentication.Manager
//		// and then make assertions.
//
//	}
type ManagerMock struct {
	// ExchangeTokenForUserFunc mocks the ExchangeTokenForUser method.
	ExchangeTokenForUserFunc func(ctx context.Context, refreshToken string, desiredAccountID string) (*auth.TokenResponse, error)

	// ProcessLoginFunc mocks the ProcessLogin method.
	ProcessLoginFunc func(ctx context.Context, adminOnly bool, loginData *auth.UserLoginInput, meta *authentication.LoginMetadata) (*auth.TokenResponse, error)

	// ProcessPasskeyLoginFunc mocks the ProcessPasskeyLogin method.
	ProcessPasskeyLoginFunc func(ctx context.Context, userID string, desiredAccountID string, meta *authentication.LoginMetadata) (*auth.TokenResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// ExchangeTokenForUser holds details about calls to the ExchangeTokenForUser method.
		ExchangeTokenForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
			// DesiredAccountID is the desiredAccountID argument value.
			DesiredAccountID string
		}
		// ProcessLogin holds details about calls to the ProcessLogin method.
		ProcessLogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AdminOnly is the adminOnly argument value.
			AdminOnly bool
			// LoginData is the loginData argument value.
			LoginData *auth.UserLoginInput
			// Meta is the meta argument value.
			Meta *authentication.LoginMetadata
		}
		// ProcessPasskeyLogin holds details about calls to the ProcessPasskeyLogin method.
		ProcessPasskeyLogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// DesiredAccountID is the desiredAccountID argument value.
			DesiredAccountID string
			// Meta is the meta argument value.
			Meta *authentication.LoginMetadata
		}
	}
	lockExchangeTokenForUser sync.RWMutex
	lockProcessLogin         sync.RWMutex
	lockProcessPasskeyLogin  sync.RWMutex
}

// ExchangeTokenForUser calls ExchangeTokenForUserFunc.
func (mock *ManagerMock) ExchangeTokenForUser(ctx context.Context, refreshToken string, desiredAccountID string) (*auth.TokenResponse, error) {
	if mock.ExchangeTokenForUserFunc == nil {
		panic("ManagerMock.ExchangeTokenForUserFunc: method is nil but Manager.ExchangeTokenForUser was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		RefreshToken     string
		DesiredAccountID string
	}{
		Ctx:              ctx,
		RefreshToken:     refreshToken,
		DesiredAccountID: desiredAccountID,
	}
	mock.lockExchangeTokenForUser.Lock()
	mock.calls.ExchangeTokenForUser = append(mock.calls.ExchangeTokenForUser, callInfo)
	mock.lockExchangeTokenForUser.Unlock()
	return mock.ExchangeTokenForUserFunc(ctx, refreshToken, desiredAccountID)
}

// ExchangeTokenForUserCalls gets all the calls that were made to ExchangeTokenForUser.
// Check the length with:
//
//	len(mockedManager.ExchangeTokenForUserCalls())
func (mock *ManagerMock) ExchangeTokenForUserCalls() []struct {
	Ctx              context.Context
	RefreshToken     string
	DesiredAccountID string
} {
	var calls []struct {
		Ctx              context.Context
		RefreshToken     string
		DesiredAccountID string
	}
	mock.lockExchangeTokenForUser.RLock()
	calls = mock.calls.ExchangeTokenForUser
	mock.lockExchangeTokenForUser.RUnlock()
	return calls
}

// ProcessLogin calls ProcessLoginFunc.
func (mock *ManagerMock) ProcessLogin(ctx context.Context, adminOnly bool, loginData *auth.UserLoginInput, meta *authentication.LoginMetadata) (*auth.TokenResponse, error) {
	if mock.ProcessLoginFunc == nil {
		panic("ManagerMock.ProcessLoginFunc: method is nil but Manager.ProcessLogin was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AdminOnly bool
		LoginData *auth.UserLoginInput
		Meta      *authentication.LoginMetadata
	}{
		Ctx:       ctx,
		AdminOnly: adminOnly,
		LoginData: loginData,
		Meta:      meta,
	}
	mock.lockProcessLogin.Lock()
	mock.calls.ProcessLogin = append(mock.calls.ProcessLogin, callInfo)
	mock.lockProcessLogin.Unlock()
	return mock.ProcessLoginFunc(ctx, adminOnly, loginData, meta)
}

// ProcessLoginCalls gets all the calls that were made to ProcessLogin.
// Check the length with:
//
//	len(mockedManager.ProcessLoginCalls())
func (mock *ManagerMock) ProcessLoginCalls() []struct {
	Ctx       context.Context
	AdminOnly bool
	LoginData *auth.UserLoginInput
	Meta      *authentication.LoginMetadata
} {
	var calls []struct {
		Ctx       context.Context
		AdminOnly bool
		LoginData *auth.UserLoginInput
		Meta      *authentication.LoginMetadata
	}
	mock.lockProcessLogin.RLock()
	calls = mock.calls.ProcessLogin
	mock.lockProcessLogin.RUnlock()
	return calls
}

// ProcessPasskeyLogin calls ProcessPasskeyLoginFunc.
func (mock *ManagerMock) ProcessPasskeyLogin(ctx context.Context, userID string, desiredAccountID string, meta *authentication.LoginMetadata) (*auth.TokenResponse, error) {
	if mock.ProcessPasskeyLoginFunc == nil {
		panic("ManagerMock.ProcessPasskeyLoginFunc: method is nil but Manager.ProcessPasskeyLogin was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		UserID           string
		DesiredAccountID string
		Meta             *authentication.LoginMetadata
	}{
		Ctx:              ctx,
		UserID:           userID,
		DesiredAccountID: desiredAccountID,
		Meta:             meta,
	}
	mock.lockProcessPasskeyLogin.Lock()
	mock.calls.ProcessPasskeyLogin = append(mock.calls.ProcessPasskeyLogin, callInfo)
	mock.lockProcessPasskeyLogin.Unlock()
	return mock.ProcessPasskeyLoginFunc(ctx, userID, desiredAccountID, meta)
}

// ProcessPasskeyLoginCalls gets all the calls that were made to ProcessPasskeyLogin.
// Check the length with:
//
//	len(mockedManager.ProcessPasskeyLoginCalls())
func (mock *ManagerMock) ProcessPasskeyLoginCalls() []struct {
	Ctx              context.Context
	UserID           string
	DesiredAccountID string
	Meta             *authentication.LoginMetadata
} {
	var calls []struct {
		Ctx              context.Context
		UserID           string
		DesiredAccountID string
		Meta             *authentication.LoginMetadata
	}
	mock.lockProcessPasskeyLogin.RLock()
	calls = mock.calls.ProcessPasskeyLogin
	mock.lockProcessPasskeyLogin.RUnlock()
	return calls
}

// Ensure, that AuthenticatorMock does implement authentication.Authenticator.
// If this is not the case, regenerate this file with moq.
var _ authentication.Authenticator = &AuthenticatorMock{}

// AuthenticatorMock is a mock implementation of authentication.Authenticator.
//
//	func TestSomethingThatUsesAuthenticator(t *testing.T) {
//
//		// make and configure a mocked authentication.Authenticator
//		mockedAuthenticator := &AuthenticatorMock{
//			HashPasswordFunc: func(ctx context.Context, password string) (string, error) {
//				panic("mock out the HashPassword method")
//			},
//			PasswordMatchesFunc: func(ctx context.Context, hash string, password string) (bool, error) {
//				panic("mock out the PasswordMatches method")
//			},
//		}
//
//		// use mockedAuthenticator in code that requires authentication.Authenticator
//		// and then make assertions.
//
//	}
type AuthenticatorMock struct {
	// HashPasswordFunc mocks the HashPassword method.
	HashPasswordFunc func(ctx context.Context, password string) (string, error)

	// PasswordMatchesFunc mocks the PasswordMatches method.
	PasswordMatchesFunc func(ctx context.Context, hash string, password string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// HashPassword holds details about calls to the HashPassword method.
		HashPassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Password is the password argument value.
			Password string
		}
		// PasswordMatches holds details about calls to the PasswordMatches method.
		PasswordMatches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
			// Password is the password argument value.
			Password string
		}
	}
	lockHashPassword    sync.RWMutex
	lockPasswordMatches sync.RWMutex
}

// HashPassword calls HashPasswordFunc.
func (mock *AuthenticatorMock) HashPassword(ctx context.Context, password string) (string, error) {
	if mock.HashPasswordFunc == nil {
		panic("AuthenticatorMock.HashPasswordFunc: method is nil but Authenticator.HashPassword was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Password string
	}{
		Ctx:      ctx,
		Password: password,
	}
	mock.lockHashPassword.Lock()
	mock.calls.HashPassword = append(mock.calls.HashPassword, callInfo)
	mock.lockHashPassword.Unlock()
	return mock.HashPasswordFunc(ctx, password)
}

// HashPasswordCalls gets all the calls that were made to HashPassword.
// Check the length with:
//
//	len(mockedAuthenticator.HashPasswordCalls())
func (mock *AuthenticatorMock) HashPasswordCalls() []struct {
	Ctx      context.Context
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Password string
	}
	mock.lockHashPassword.RLock()
	calls = mock.calls.HashPassword
	mock.lockHashPassword.RUnlock()
	return calls
}

// PasswordMatches calls PasswordMatchesFunc.
func (mock *AuthenticatorMock) PasswordMatches(ctx context.Context, hash string, password string) (bool, error) {
	if mock.PasswordMatchesFunc == nil {
		panic("AuthenticatorMock.PasswordMatchesFunc: method is nil but Authenticator.PasswordMatches was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Hash     string
		Password string
	}{
		Ctx:      ctx,
		Hash:     hash,
		Password: password,
	}
	mock.lockPasswordMatches.Lock()
	mock.calls.PasswordMatches = append(mock.calls.PasswordMatches, callInfo)
	mock.lockPasswordMatches.Unlock()
	return mock.PasswordMatchesFunc(ctx, hash, password)
}

// PasswordMatchesCalls gets all the calls that were made to PasswordMatches.
// Check the length with:
//
//	len(mockedAuthenticator.PasswordMatchesCalls())
func (mock *AuthenticatorMock) PasswordMatchesCalls() []struct {
	Ctx      context.Context
	Hash     string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Hash     string
		Password string
	}
	mock.lockPasswordMatches.RLock()
	calls = mock.calls.PasswordMatches
	mock.lockPasswordMatches.RUnlock()
	return calls
}
