// Code generated by cmd/tools/codegen/fakes. DO NOT EDIT.

package fakes

import (
	"math"
	"time"

	types "github.com/primandproper/dinnerdonebetter/backend/internal/domain/oauth"

	"github.com/primandproper/platform-go/v10/filtering"
	"github.com/primandproper/platform-go/v10/identifiers"

	fake "github.com/brianvoe/gofakeit/v7"
)

func init() {
	if err := fake.Seed(time.Now().UnixNano()); err != nil {
		panic(err)
	}
}

// exampleQuantity is how many elements a faked list has.
const exampleQuantity = 3

// BuildFakeID builds a fake ID.
func BuildFakeID() string {
	return identifiers.New()
}

// BuildFakeTime builds a fake time.
func BuildFakeTime() time.Time {
	return fake.Date().Add(0).Truncate(time.Second).UTC()
}

// buildFakeNumber builds a fake number comfortably above zero and below every integer
// width the domains use, so that it survives a conversion to any of them and no validator
// mistakes it for unset.
func buildFakeNumber() float64 {
	return math.Round(float64((fake.Number(101, math.MaxInt8-1) * 100) / 100))
}

// buildUniqueString builds a fake string.
func buildUniqueString() string {
	return fake.LoremIpsumSentence(7)
}

// buildFakePassword builds a fake password.
func buildFakePassword() string {
	return fake.Password(true, true, true, true, false, 32)
}

// BuildFakeOAuth2Client builds a faked OAuth2Client.
func BuildFakeOAuth2Client() *types.OAuth2Client {
	return &types.OAuth2Client{
		CreatedAt:    BuildFakeTime(),
		ArchivedAt:   nil,
		Name:         fake.Password(true, true, true, false, false, 32),
		Description:  "",
		ClientID:     BuildFakeID(),
		ID:           BuildFakeID(),
		ClientSecret: buildFakePassword(),
	}
}

// BuildFakeOAuth2ClientsList builds a faked OAuth2Client list.
func BuildFakeOAuth2ClientsList() *filtering.QueryFilteredResult[types.OAuth2Client] {
	var examples []*types.OAuth2Client
	for range exampleQuantity {
		examples = append(examples, BuildFakeOAuth2Client())
	}

	return &filtering.QueryFilteredResult[types.OAuth2Client]{
		Pagination: filtering.Pagination{
			Cursor:          BuildFakeID(),
			MaxResponseSize: 50,
			FilteredCount:   exampleQuantity / 2,
			TotalCount:      exampleQuantity,
		},
		Data: examples,
	}
}

// BuildFakeOAuth2ClientToken builds a faked OAuth2ClientToken.
func BuildFakeOAuth2ClientToken() *types.OAuth2ClientToken {
	return &types.OAuth2ClientToken{
		RefreshCreatedAt:    BuildFakeTime(),
		AccessCreatedAt:     BuildFakeTime(),
		CodeCreatedAt:       BuildFakeTime(),
		RedirectURI:         fake.URL(),
		Code:                buildUniqueString(),
		CodeChallenge:       buildUniqueString(),
		CodeChallengeMethod: "S256",
		BelongsToUser:       BuildFakeID(),
		Access:              buildUniqueString(),
		ClientID:            BuildFakeID(),
		Refresh:             buildUniqueString(),
		ID:                  BuildFakeID(),
		CodeExpiresAt:       time.Hour,
		AccessExpiresAt:     time.Hour,
		RefreshExpiresAt:    time.Hour,
	}
}

// BuildFakeOAuth2ClientCreationResponse builds a faked OAuth2ClientCreationResponse.
func BuildFakeOAuth2ClientCreationResponse() *types.OAuth2ClientCreationResponse {
	client := BuildFakeOAuth2Client()

	return &types.OAuth2ClientCreationResponse{
		ClientID:     client.ClientID,
		ClientSecret: client.ClientSecret,
		Name:         "",
		Description:  "",
		ID:           client.ID,
	}
}

// BuildFakeOAuth2ClientCreationRequestInput builds a faked OAuth2ClientCreationRequestInput.
func BuildFakeOAuth2ClientCreationRequestInput() *types.OAuth2ClientCreationRequestInput {
	client := BuildFakeOAuth2Client()

	return &types.OAuth2ClientCreationRequestInput{
		Name:        client.Name,
		Description: client.Description,
	}
}
