// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: webhooks/webhooks_service_types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { ResponseDetails } from '../common';
import { Pagination, QueryFilter } from '../filtering';
import {
  Webhook,
  WebhookContentType,
  webhookContentTypeFromJSON,
  webhookContentTypeToJSON,
  WebhookEventType,
  WebhookMethod,
  webhookMethodFromJSON,
  webhookMethodToJSON,
  WebhookTriggerConfig,
} from './webhooks_messages';

export const protobufPackage = 'webhooks';

export interface WebhookCreationRequestInput {
  name: string;
  contentType: WebhookContentType;
  url: string;
  method: WebhookMethod;
  /**
   * event_types are the catalog event types this webhook subscribes to.
   *
   * Field 5 previously carried WebhookTriggerEventCreationRequestInput, which let a caller
   * define new catalog rows inline. That is gone: the catalog is generated from the events the
   * application actually publishes, so an event type a caller invents is one nothing will ever
   * emit. Subscribing to an unknown type is now rejected rather than silently stored.
   */
  eventTypes: string[];
}

export interface WebhookTriggerConfigCreationRequestInput {
  belongsToWebhook: string;
  eventType: string;
}

export interface CreateWebhookRequest {
  input: WebhookCreationRequestInput | undefined;
}

export interface CreateWebhookResponse {
  responseDetails: ResponseDetails | undefined;
  created: Webhook | undefined;
  /**
   * secret is the hex-encoded HMAC signing key, returned exactly once.
   *
   * It is on the creation response and on no read message, so there is no request an attacker
   * with read access can make that yields it. A caller who loses it calls RotateWebhookSecret.
   *
   * Deliveries carry X-Platform-Signature: v1,t=<unix>,s=<hex>, over "v1.<t>.<body>". The
   * timestamp is inside the signed material, which is what makes a captured delivery expire —
   * verify it before spending an HMAC. platform-go's webhooks.Verify is the reference
   * implementation.
   */
  secret: string;
}

export interface AddWebhookTriggerConfigRequest {
  webhookId: string;
  input: WebhookTriggerConfigCreationRequestInput | undefined;
}

export interface AddWebhookTriggerConfigResponse {
  responseDetails: ResponseDetails | undefined;
  created: WebhookTriggerConfig | undefined;
}

export interface ArchiveWebhookRequest {
  webhookId: string;
}

export interface ArchiveWebhookResponse {
  responseDetails: ResponseDetails | undefined;
}

export interface ArchiveWebhookTriggerConfigRequest {
  webhookId: string;
  webhookTriggerConfigId: string;
}

export interface ArchiveWebhookTriggerConfigResponse {
  responseDetails: ResponseDetails | undefined;
}

export interface GetWebhookRequest {
  webhookId: string;
}

export interface GetWebhookResponse {
  responseDetails: ResponseDetails | undefined;
  result: Webhook | undefined;
}

export interface GetWebhooksRequest {
  filter: QueryFilter | undefined;
}

export interface GetWebhooksResponse {
  responseDetails: ResponseDetails | undefined;
  pagination: Pagination | undefined;
  results: Webhook[];
}

/**
 * RotateWebhookSecret mints a new signing secret for a webhook.
 *
 * Deliveries are signed under both the new key and the outgoing one until this is called again,
 * so a subscriber accepts either signature while it switches over. Rotating twice retires the
 * original key.
 */
export interface RotateWebhookSecretRequest {
  webhookId: string;
}

export interface RotateWebhookSecretResponse {
  responseDetails: ResponseDetails | undefined;
  /** secret is the new hex-encoded HMAC signing key, returned exactly once. */
  secret: string;
}

export interface GetWebhookEventTypesRequest {}

export interface GetWebhookEventTypesResponse {
  responseDetails: ResponseDetails | undefined;
  results: WebhookEventType[];
}

function createBaseWebhookCreationRequestInput(): WebhookCreationRequestInput {
  return { name: '', contentType: 0, url: '', method: 0, eventTypes: [] };
}

export const WebhookCreationRequestInput: MessageFns<WebhookCreationRequestInput> = {
  encode(message: WebhookCreationRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== '') {
      writer.uint32(10).string(message.name);
    }
    if (message.contentType !== 0) {
      writer.uint32(16).int32(message.contentType);
    }
    if (message.url !== '') {
      writer.uint32(26).string(message.url);
    }
    if (message.method !== 0) {
      writer.uint32(32).int32(message.method);
    }
    for (const v of message.eventTypes) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WebhookCreationRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebhookCreationRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.contentType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.method = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.eventTypes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WebhookCreationRequestInput {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      contentType: isSet(object.contentType)
        ? webhookContentTypeFromJSON(object.contentType)
        : isSet(object.content_type)
          ? webhookContentTypeFromJSON(object.content_type)
          : 0,
      url: isSet(object.url) ? globalThis.String(object.url) : '',
      method: isSet(object.method) ? webhookMethodFromJSON(object.method) : 0,
      eventTypes: globalThis.Array.isArray(object?.eventTypes)
        ? object.eventTypes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.event_types)
          ? object.event_types.map((e: any) => globalThis.String(e))
          : [],
    };
  },

  toJSON(message: WebhookCreationRequestInput): unknown {
    const obj: any = {};
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.contentType !== 0) {
      obj.contentType = webhookContentTypeToJSON(message.contentType);
    }
    if (message.url !== '') {
      obj.url = message.url;
    }
    if (message.method !== 0) {
      obj.method = webhookMethodToJSON(message.method);
    }
    if (message.eventTypes?.length) {
      obj.eventTypes = message.eventTypes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WebhookCreationRequestInput>, I>>(base?: I): WebhookCreationRequestInput {
    return WebhookCreationRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WebhookCreationRequestInput>, I>>(object: I): WebhookCreationRequestInput {
    const message = createBaseWebhookCreationRequestInput();
    message.name = object.name ?? '';
    message.contentType = object.contentType ?? 0;
    message.url = object.url ?? '';
    message.method = object.method ?? 0;
    message.eventTypes = object.eventTypes?.map((e) => e) || [];
    return message;
  },
};

function createBaseWebhookTriggerConfigCreationRequestInput(): WebhookTriggerConfigCreationRequestInput {
  return { belongsToWebhook: '', eventType: '' };
}

export const WebhookTriggerConfigCreationRequestInput: MessageFns<WebhookTriggerConfigCreationRequestInput> = {
  encode(message: WebhookTriggerConfigCreationRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.belongsToWebhook !== '') {
      writer.uint32(10).string(message.belongsToWebhook);
    }
    if (message.eventType !== '') {
      writer.uint32(26).string(message.eventType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WebhookTriggerConfigCreationRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebhookTriggerConfigCreationRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.belongsToWebhook = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WebhookTriggerConfigCreationRequestInput {
    return {
      belongsToWebhook: isSet(object.belongsToWebhook)
        ? globalThis.String(object.belongsToWebhook)
        : isSet(object.belongs_to_webhook)
          ? globalThis.String(object.belongs_to_webhook)
          : '',
      eventType: isSet(object.eventType)
        ? globalThis.String(object.eventType)
        : isSet(object.event_type)
          ? globalThis.String(object.event_type)
          : '',
    };
  },

  toJSON(message: WebhookTriggerConfigCreationRequestInput): unknown {
    const obj: any = {};
    if (message.belongsToWebhook !== '') {
      obj.belongsToWebhook = message.belongsToWebhook;
    }
    if (message.eventType !== '') {
      obj.eventType = message.eventType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WebhookTriggerConfigCreationRequestInput>, I>>(
    base?: I,
  ): WebhookTriggerConfigCreationRequestInput {
    return WebhookTriggerConfigCreationRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WebhookTriggerConfigCreationRequestInput>, I>>(
    object: I,
  ): WebhookTriggerConfigCreationRequestInput {
    const message = createBaseWebhookTriggerConfigCreationRequestInput();
    message.belongsToWebhook = object.belongsToWebhook ?? '';
    message.eventType = object.eventType ?? '';
    return message;
  },
};

function createBaseCreateWebhookRequest(): CreateWebhookRequest {
  return { input: undefined };
}

export const CreateWebhookRequest: MessageFns<CreateWebhookRequest> = {
  encode(message: CreateWebhookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input !== undefined) {
      WebhookCreationRequestInput.encode(message.input, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWebhookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.input = WebhookCreationRequestInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWebhookRequest {
    return { input: isSet(object.input) ? WebhookCreationRequestInput.fromJSON(object.input) : undefined };
  },

  toJSON(message: CreateWebhookRequest): unknown {
    const obj: any = {};
    if (message.input !== undefined) {
      obj.input = WebhookCreationRequestInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWebhookRequest>, I>>(base?: I): CreateWebhookRequest {
    return CreateWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWebhookRequest>, I>>(object: I): CreateWebhookRequest {
    const message = createBaseCreateWebhookRequest();
    message.input =
      object.input !== undefined && object.input !== null
        ? WebhookCreationRequestInput.fromPartial(object.input)
        : undefined;
    return message;
  },
};

function createBaseCreateWebhookResponse(): CreateWebhookResponse {
  return { responseDetails: undefined, created: undefined, secret: '' };
}

export const CreateWebhookResponse: MessageFns<CreateWebhookResponse> = {
  encode(message: CreateWebhookResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.created !== undefined) {
      Webhook.encode(message.created, writer.uint32(18).fork()).join();
    }
    if (message.secret !== '') {
      writer.uint32(26).string(message.secret);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWebhookResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.created = Webhook.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.secret = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWebhookResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      created: isSet(object.created) ? Webhook.fromJSON(object.created) : undefined,
      secret: isSet(object.secret) ? globalThis.String(object.secret) : '',
    };
  },

  toJSON(message: CreateWebhookResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.created !== undefined) {
      obj.created = Webhook.toJSON(message.created);
    }
    if (message.secret !== '') {
      obj.secret = message.secret;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWebhookResponse>, I>>(base?: I): CreateWebhookResponse {
    return CreateWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWebhookResponse>, I>>(object: I): CreateWebhookResponse {
    const message = createBaseCreateWebhookResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.created =
      object.created !== undefined && object.created !== null ? Webhook.fromPartial(object.created) : undefined;
    message.secret = object.secret ?? '';
    return message;
  },
};

function createBaseAddWebhookTriggerConfigRequest(): AddWebhookTriggerConfigRequest {
  return { webhookId: '', input: undefined };
}

export const AddWebhookTriggerConfigRequest: MessageFns<AddWebhookTriggerConfigRequest> = {
  encode(message: AddWebhookTriggerConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.webhookId !== '') {
      writer.uint32(10).string(message.webhookId);
    }
    if (message.input !== undefined) {
      WebhookTriggerConfigCreationRequestInput.encode(message.input, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddWebhookTriggerConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddWebhookTriggerConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhookId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = WebhookTriggerConfigCreationRequestInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddWebhookTriggerConfigRequest {
    return {
      webhookId: isSet(object.webhookId)
        ? globalThis.String(object.webhookId)
        : isSet(object.webhook_id)
          ? globalThis.String(object.webhook_id)
          : '',
      input: isSet(object.input) ? WebhookTriggerConfigCreationRequestInput.fromJSON(object.input) : undefined,
    };
  },

  toJSON(message: AddWebhookTriggerConfigRequest): unknown {
    const obj: any = {};
    if (message.webhookId !== '') {
      obj.webhookId = message.webhookId;
    }
    if (message.input !== undefined) {
      obj.input = WebhookTriggerConfigCreationRequestInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddWebhookTriggerConfigRequest>, I>>(base?: I): AddWebhookTriggerConfigRequest {
    return AddWebhookTriggerConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddWebhookTriggerConfigRequest>, I>>(
    object: I,
  ): AddWebhookTriggerConfigRequest {
    const message = createBaseAddWebhookTriggerConfigRequest();
    message.webhookId = object.webhookId ?? '';
    message.input =
      object.input !== undefined && object.input !== null
        ? WebhookTriggerConfigCreationRequestInput.fromPartial(object.input)
        : undefined;
    return message;
  },
};

function createBaseAddWebhookTriggerConfigResponse(): AddWebhookTriggerConfigResponse {
  return { responseDetails: undefined, created: undefined };
}

export const AddWebhookTriggerConfigResponse: MessageFns<AddWebhookTriggerConfigResponse> = {
  encode(message: AddWebhookTriggerConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.created !== undefined) {
      WebhookTriggerConfig.encode(message.created, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddWebhookTriggerConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddWebhookTriggerConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.created = WebhookTriggerConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddWebhookTriggerConfigResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      created: isSet(object.created) ? WebhookTriggerConfig.fromJSON(object.created) : undefined,
    };
  },

  toJSON(message: AddWebhookTriggerConfigResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.created !== undefined) {
      obj.created = WebhookTriggerConfig.toJSON(message.created);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddWebhookTriggerConfigResponse>, I>>(base?: I): AddWebhookTriggerConfigResponse {
    return AddWebhookTriggerConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddWebhookTriggerConfigResponse>, I>>(
    object: I,
  ): AddWebhookTriggerConfigResponse {
    const message = createBaseAddWebhookTriggerConfigResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.created =
      object.created !== undefined && object.created !== null
        ? WebhookTriggerConfig.fromPartial(object.created)
        : undefined;
    return message;
  },
};

function createBaseArchiveWebhookRequest(): ArchiveWebhookRequest {
  return { webhookId: '' };
}

export const ArchiveWebhookRequest: MessageFns<ArchiveWebhookRequest> = {
  encode(message: ArchiveWebhookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.webhookId !== '') {
      writer.uint32(10).string(message.webhookId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveWebhookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhookId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchiveWebhookRequest {
    return {
      webhookId: isSet(object.webhookId)
        ? globalThis.String(object.webhookId)
        : isSet(object.webhook_id)
          ? globalThis.String(object.webhook_id)
          : '',
    };
  },

  toJSON(message: ArchiveWebhookRequest): unknown {
    const obj: any = {};
    if (message.webhookId !== '') {
      obj.webhookId = message.webhookId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveWebhookRequest>, I>>(base?: I): ArchiveWebhookRequest {
    return ArchiveWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveWebhookRequest>, I>>(object: I): ArchiveWebhookRequest {
    const message = createBaseArchiveWebhookRequest();
    message.webhookId = object.webhookId ?? '';
    return message;
  },
};

function createBaseArchiveWebhookResponse(): ArchiveWebhookResponse {
  return { responseDetails: undefined };
}

export const ArchiveWebhookResponse: MessageFns<ArchiveWebhookResponse> = {
  encode(message: ArchiveWebhookResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveWebhookResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchiveWebhookResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
    };
  },

  toJSON(message: ArchiveWebhookResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveWebhookResponse>, I>>(base?: I): ArchiveWebhookResponse {
    return ArchiveWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveWebhookResponse>, I>>(object: I): ArchiveWebhookResponse {
    const message = createBaseArchiveWebhookResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    return message;
  },
};

function createBaseArchiveWebhookTriggerConfigRequest(): ArchiveWebhookTriggerConfigRequest {
  return { webhookId: '', webhookTriggerConfigId: '' };
}

export const ArchiveWebhookTriggerConfigRequest: MessageFns<ArchiveWebhookTriggerConfigRequest> = {
  encode(message: ArchiveWebhookTriggerConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.webhookId !== '') {
      writer.uint32(10).string(message.webhookId);
    }
    if (message.webhookTriggerConfigId !== '') {
      writer.uint32(18).string(message.webhookTriggerConfigId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveWebhookTriggerConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveWebhookTriggerConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhookId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.webhookTriggerConfigId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchiveWebhookTriggerConfigRequest {
    return {
      webhookId: isSet(object.webhookId)
        ? globalThis.String(object.webhookId)
        : isSet(object.webhook_id)
          ? globalThis.String(object.webhook_id)
          : '',
      webhookTriggerConfigId: isSet(object.webhookTriggerConfigId)
        ? globalThis.String(object.webhookTriggerConfigId)
        : isSet(object.webhook_trigger_config_id)
          ? globalThis.String(object.webhook_trigger_config_id)
          : '',
    };
  },

  toJSON(message: ArchiveWebhookTriggerConfigRequest): unknown {
    const obj: any = {};
    if (message.webhookId !== '') {
      obj.webhookId = message.webhookId;
    }
    if (message.webhookTriggerConfigId !== '') {
      obj.webhookTriggerConfigId = message.webhookTriggerConfigId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveWebhookTriggerConfigRequest>, I>>(
    base?: I,
  ): ArchiveWebhookTriggerConfigRequest {
    return ArchiveWebhookTriggerConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveWebhookTriggerConfigRequest>, I>>(
    object: I,
  ): ArchiveWebhookTriggerConfigRequest {
    const message = createBaseArchiveWebhookTriggerConfigRequest();
    message.webhookId = object.webhookId ?? '';
    message.webhookTriggerConfigId = object.webhookTriggerConfigId ?? '';
    return message;
  },
};

function createBaseArchiveWebhookTriggerConfigResponse(): ArchiveWebhookTriggerConfigResponse {
  return { responseDetails: undefined };
}

export const ArchiveWebhookTriggerConfigResponse: MessageFns<ArchiveWebhookTriggerConfigResponse> = {
  encode(message: ArchiveWebhookTriggerConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveWebhookTriggerConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveWebhookTriggerConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchiveWebhookTriggerConfigResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
    };
  },

  toJSON(message: ArchiveWebhookTriggerConfigResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveWebhookTriggerConfigResponse>, I>>(
    base?: I,
  ): ArchiveWebhookTriggerConfigResponse {
    return ArchiveWebhookTriggerConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveWebhookTriggerConfigResponse>, I>>(
    object: I,
  ): ArchiveWebhookTriggerConfigResponse {
    const message = createBaseArchiveWebhookTriggerConfigResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    return message;
  },
};

function createBaseGetWebhookRequest(): GetWebhookRequest {
  return { webhookId: '' };
}

export const GetWebhookRequest: MessageFns<GetWebhookRequest> = {
  encode(message: GetWebhookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.webhookId !== '') {
      writer.uint32(10).string(message.webhookId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWebhookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhookId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWebhookRequest {
    return {
      webhookId: isSet(object.webhookId)
        ? globalThis.String(object.webhookId)
        : isSet(object.webhook_id)
          ? globalThis.String(object.webhook_id)
          : '',
    };
  },

  toJSON(message: GetWebhookRequest): unknown {
    const obj: any = {};
    if (message.webhookId !== '') {
      obj.webhookId = message.webhookId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWebhookRequest>, I>>(base?: I): GetWebhookRequest {
    return GetWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWebhookRequest>, I>>(object: I): GetWebhookRequest {
    const message = createBaseGetWebhookRequest();
    message.webhookId = object.webhookId ?? '';
    return message;
  },
};

function createBaseGetWebhookResponse(): GetWebhookResponse {
  return { responseDetails: undefined, result: undefined };
}

export const GetWebhookResponse: MessageFns<GetWebhookResponse> = {
  encode(message: GetWebhookResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.result !== undefined) {
      Webhook.encode(message.result, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWebhookResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.result = Webhook.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWebhookResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      result: isSet(object.result) ? Webhook.fromJSON(object.result) : undefined,
    };
  },

  toJSON(message: GetWebhookResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.result !== undefined) {
      obj.result = Webhook.toJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWebhookResponse>, I>>(base?: I): GetWebhookResponse {
    return GetWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWebhookResponse>, I>>(object: I): GetWebhookResponse {
    const message = createBaseGetWebhookResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.result =
      object.result !== undefined && object.result !== null ? Webhook.fromPartial(object.result) : undefined;
    return message;
  },
};

function createBaseGetWebhooksRequest(): GetWebhooksRequest {
  return { filter: undefined };
}

export const GetWebhooksRequest: MessageFns<GetWebhooksRequest> = {
  encode(message: GetWebhooksRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filter !== undefined) {
      QueryFilter.encode(message.filter, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWebhooksRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWebhooksRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = QueryFilter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWebhooksRequest {
    return { filter: isSet(object.filter) ? QueryFilter.fromJSON(object.filter) : undefined };
  },

  toJSON(message: GetWebhooksRequest): unknown {
    const obj: any = {};
    if (message.filter !== undefined) {
      obj.filter = QueryFilter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWebhooksRequest>, I>>(base?: I): GetWebhooksRequest {
    return GetWebhooksRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWebhooksRequest>, I>>(object: I): GetWebhooksRequest {
    const message = createBaseGetWebhooksRequest();
    message.filter =
      object.filter !== undefined && object.filter !== null ? QueryFilter.fromPartial(object.filter) : undefined;
    return message;
  },
};

function createBaseGetWebhooksResponse(): GetWebhooksResponse {
  return { responseDetails: undefined, pagination: undefined, results: [] };
}

export const GetWebhooksResponse: MessageFns<GetWebhooksResponse> = {
  encode(message: GetWebhooksResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      Pagination.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    for (const v of message.results) {
      Webhook.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWebhooksResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWebhooksResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = Pagination.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.results.push(Webhook.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWebhooksResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      pagination: isSet(object.pagination) ? Pagination.fromJSON(object.pagination) : undefined,
      results: globalThis.Array.isArray(object?.results) ? object.results.map((e: any) => Webhook.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetWebhooksResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.pagination !== undefined) {
      obj.pagination = Pagination.toJSON(message.pagination);
    }
    if (message.results?.length) {
      obj.results = message.results.map((e) => Webhook.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWebhooksResponse>, I>>(base?: I): GetWebhooksResponse {
    return GetWebhooksResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWebhooksResponse>, I>>(object: I): GetWebhooksResponse {
    const message = createBaseGetWebhooksResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? Pagination.fromPartial(object.pagination)
        : undefined;
    message.results = object.results?.map((e) => Webhook.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRotateWebhookSecretRequest(): RotateWebhookSecretRequest {
  return { webhookId: '' };
}

export const RotateWebhookSecretRequest: MessageFns<RotateWebhookSecretRequest> = {
  encode(message: RotateWebhookSecretRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.webhookId !== '') {
      writer.uint32(10).string(message.webhookId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RotateWebhookSecretRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRotateWebhookSecretRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhookId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RotateWebhookSecretRequest {
    return {
      webhookId: isSet(object.webhookId)
        ? globalThis.String(object.webhookId)
        : isSet(object.webhook_id)
          ? globalThis.String(object.webhook_id)
          : '',
    };
  },

  toJSON(message: RotateWebhookSecretRequest): unknown {
    const obj: any = {};
    if (message.webhookId !== '') {
      obj.webhookId = message.webhookId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RotateWebhookSecretRequest>, I>>(base?: I): RotateWebhookSecretRequest {
    return RotateWebhookSecretRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RotateWebhookSecretRequest>, I>>(object: I): RotateWebhookSecretRequest {
    const message = createBaseRotateWebhookSecretRequest();
    message.webhookId = object.webhookId ?? '';
    return message;
  },
};

function createBaseRotateWebhookSecretResponse(): RotateWebhookSecretResponse {
  return { responseDetails: undefined, secret: '' };
}

export const RotateWebhookSecretResponse: MessageFns<RotateWebhookSecretResponse> = {
  encode(message: RotateWebhookSecretResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.secret !== '') {
      writer.uint32(18).string(message.secret);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RotateWebhookSecretResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRotateWebhookSecretResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.secret = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RotateWebhookSecretResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      secret: isSet(object.secret) ? globalThis.String(object.secret) : '',
    };
  },

  toJSON(message: RotateWebhookSecretResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.secret !== '') {
      obj.secret = message.secret;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RotateWebhookSecretResponse>, I>>(base?: I): RotateWebhookSecretResponse {
    return RotateWebhookSecretResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RotateWebhookSecretResponse>, I>>(object: I): RotateWebhookSecretResponse {
    const message = createBaseRotateWebhookSecretResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.secret = object.secret ?? '';
    return message;
  },
};

function createBaseGetWebhookEventTypesRequest(): GetWebhookEventTypesRequest {
  return {};
}

export const GetWebhookEventTypesRequest: MessageFns<GetWebhookEventTypesRequest> = {
  encode(_: GetWebhookEventTypesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWebhookEventTypesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWebhookEventTypesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetWebhookEventTypesRequest {
    return {};
  },

  toJSON(_: GetWebhookEventTypesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWebhookEventTypesRequest>, I>>(base?: I): GetWebhookEventTypesRequest {
    return GetWebhookEventTypesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWebhookEventTypesRequest>, I>>(_: I): GetWebhookEventTypesRequest {
    const message = createBaseGetWebhookEventTypesRequest();
    return message;
  },
};

function createBaseGetWebhookEventTypesResponse(): GetWebhookEventTypesResponse {
  return { responseDetails: undefined, results: [] };
}

export const GetWebhookEventTypesResponse: MessageFns<GetWebhookEventTypesResponse> = {
  encode(message: GetWebhookEventTypesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    for (const v of message.results) {
      WebhookEventType.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWebhookEventTypesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWebhookEventTypesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.results.push(WebhookEventType.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWebhookEventTypesResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => WebhookEventType.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetWebhookEventTypesResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.results?.length) {
      obj.results = message.results.map((e) => WebhookEventType.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWebhookEventTypesResponse>, I>>(base?: I): GetWebhookEventTypesResponse {
    return GetWebhookEventTypesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWebhookEventTypesResponse>, I>>(object: I): GetWebhookEventTypesResponse {
    const message = createBaseGetWebhookEventTypesResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.results = object.results?.map((e) => WebhookEventType.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
