// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/auth"

	"github.com/primandproper/platform-go/v10/filtering"
)

// Ensure, that PasswordResetTokenDataManagerMock does implement auth.PasswordResetTokenDataManager.
// If this is not the case, regenerate this file with moq.
var _ auth.PasswordResetTokenDataManager = &PasswordResetTokenDataManagerMock{}

// PasswordResetTokenDataManagerMock is a mock implementation of auth.PasswordResetTokenDataManager.
//
//	func TestSomethingThatUsesPasswordResetTokenDataManager(t *testing.T) {
//
//		// make and configure a mocked auth.PasswordResetTokenDataManager
//		mockedPasswordResetTokenDataManager := &PasswordResetTokenDataManagerMock{
//			CreatePasswordResetTokenFunc: func(ctx context.Context, input *auth.PasswordResetTokenDatabaseCreationInput) (*auth.PasswordResetToken, error) {
//				panic("mock out the CreatePasswordResetToken method")
//			},
//			GetPasswordResetTokenByIDFunc: func(ctx context.Context, passwordResetTokenID string) (*auth.PasswordResetToken, error) {
//				panic("mock out the GetPasswordResetTokenByID method")
//			},
//			GetPasswordResetTokenByTokenFunc: func(ctx context.Context, passwordResetTokenID string) (*auth.PasswordResetToken, error) {
//				panic("mock out the GetPasswordResetTokenByToken method")
//			},
//			RedeemPasswordResetTokenFunc: func(ctx context.Context, passwordResetTokenID string) error {
//				panic("mock out the RedeemPasswordResetToken method")
//			},
//		}
//
//		// use mockedPasswordResetTokenDataManager in code that requires auth.PasswordResetTokenDataManager
//		// and then make assertions.
//
//	}
type PasswordResetTokenDataManagerMock struct {
	// CreatePasswordResetTokenFunc mocks the CreatePasswordResetToken method.
	CreatePasswordResetTokenFunc func(ctx context.Context, input *auth.PasswordResetTokenDatabaseCreationInput) (*auth.PasswordResetToken, error)

	// GetPasswordResetTokenByIDFunc mocks the GetPasswordResetTokenByID method.
	GetPasswordResetTokenByIDFunc func(ctx context.Context, passwordResetTokenID string) (*auth.PasswordResetToken, error)

	// GetPasswordResetTokenByTokenFunc mocks the GetPasswordResetTokenByToken method.
	GetPasswordResetTokenByTokenFunc func(ctx context.Context, passwordResetTokenID string) (*auth.PasswordResetToken, error)

	// RedeemPasswordResetTokenFunc mocks the RedeemPasswordResetToken method.
	RedeemPasswordResetTokenFunc func(ctx context.Context, passwordResetTokenID string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreatePasswordResetToken holds details about calls to the CreatePasswordResetToken method.
		CreatePasswordResetToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *auth.PasswordResetTokenDatabaseCreationInput
		}
		// GetPasswordResetTokenByID holds details about calls to the GetPasswordResetTokenByID method.
		GetPasswordResetTokenByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PasswordResetTokenID is the passwordResetTokenID argument value.
			PasswordResetTokenID string
		}
		// GetPasswordResetTokenByToken holds details about calls to the GetPasswordResetTokenByToken method.
		GetPasswordResetTokenByToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PasswordResetTokenID is the passwordResetTokenID argument value.
			PasswordResetTokenID string
		}
		// RedeemPasswordResetToken holds details about calls to the RedeemPasswordResetToken method.
		RedeemPasswordResetToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PasswordResetTokenID is the passwordResetTokenID argument value.
			PasswordResetTokenID string
		}
	}
	lockCreatePasswordResetToken     sync.RWMutex
	lockGetPasswordResetTokenByID    sync.RWMutex
	lockGetPasswordResetTokenByToken sync.RWMutex
	lockRedeemPasswordResetToken     sync.RWMutex
}

// CreatePasswordResetToken calls CreatePasswordResetTokenFunc.
func (mock *PasswordResetTokenDataManagerMock) CreatePasswordResetToken(ctx context.Context, input *auth.PasswordResetTokenDatabaseCreationInput) (*auth.PasswordResetToken, error) {
	if mock.CreatePasswordResetTokenFunc == nil {
		panic("PasswordResetTokenDataManagerMock.CreatePasswordResetTokenFunc: method is nil but PasswordResetTokenDataManager.CreatePasswordResetToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *auth.PasswordResetTokenDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreatePasswordResetToken.Lock()
	mock.calls.CreatePasswordResetToken = append(mock.calls.CreatePasswordResetToken, callInfo)
	mock.lockCreatePasswordResetToken.Unlock()
	return mock.CreatePasswordResetTokenFunc(ctx, input)
}

// CreatePasswordResetTokenCalls gets all the calls that were made to CreatePasswordResetToken.
// Check the length with:
//
//	len(mockedPasswordResetTokenDataManager.CreatePasswordResetTokenCalls())
func (mock *PasswordResetTokenDataManagerMock) CreatePasswordResetTokenCalls() []struct {
	Ctx   context.Context
	Input *auth.PasswordResetTokenDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *auth.PasswordResetTokenDatabaseCreationInput
	}
	mock.lockCreatePasswordResetToken.RLock()
	calls = mock.calls.CreatePasswordResetToken
	mock.lockCreatePasswordResetToken.RUnlock()
	return calls
}

// GetPasswordResetTokenByID calls GetPasswordResetTokenByIDFunc.
func (mock *PasswordResetTokenDataManagerMock) GetPasswordResetTokenByID(ctx context.Context, passwordResetTokenID string) (*auth.PasswordResetToken, error) {
	if mock.GetPasswordResetTokenByIDFunc == nil {
		panic("PasswordResetTokenDataManagerMock.GetPasswordResetTokenByIDFunc: method is nil but PasswordResetTokenDataManager.GetPasswordResetTokenByID was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		PasswordResetTokenID string
	}{
		Ctx:                  ctx,
		PasswordResetTokenID: passwordResetTokenID,
	}
	mock.lockGetPasswordResetTokenByID.Lock()
	mock.calls.GetPasswordResetTokenByID = append(mock.calls.GetPasswordResetTokenByID, callInfo)
	mock.lockGetPasswordResetTokenByID.Unlock()
	return mock.GetPasswordResetTokenByIDFunc(ctx, passwordResetTokenID)
}

// GetPasswordResetTokenByIDCalls gets all the calls that were made to GetPasswordResetTokenByID.
// Check the length with:
//
//	len(mockedPasswordResetTokenDataManager.GetPasswordResetTokenByIDCalls())
func (mock *PasswordResetTokenDataManagerMock) GetPasswordResetTokenByIDCalls() []struct {
	Ctx                  context.Context
	PasswordResetTokenID string
} {
	var calls []struct {
		Ctx                  context.Context
		PasswordResetTokenID string
	}
	mock.lockGetPasswordResetTokenByID.RLock()
	calls = mock.calls.GetPasswordResetTokenByID
	mock.lockGetPasswordResetTokenByID.RUnlock()
	return calls
}

// GetPasswordResetTokenByToken calls GetPasswordResetTokenByTokenFunc.
func (mock *PasswordResetTokenDataManagerMock) GetPasswordResetTokenByToken(ctx context.Context, passwordResetTokenID string) (*auth.PasswordResetToken, error) {
	if mock.GetPasswordResetTokenByTokenFunc == nil {
		panic("PasswordResetTokenDataManagerMock.GetPasswordResetTokenByTokenFunc: method is nil but PasswordResetTokenDataManager.GetPasswordResetTokenByToken was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		PasswordResetTokenID string
	}{
		Ctx:                  ctx,
		PasswordResetTokenID: passwordResetTokenID,
	}
	mock.lockGetPasswordResetTokenByToken.Lock()
	mock.calls.GetPasswordResetTokenByToken = append(mock.calls.GetPasswordResetTokenByToken, callInfo)
	mock.lockGetPasswordResetTokenByToken.Unlock()
	return mock.GetPasswordResetTokenByTokenFunc(ctx, passwordResetTokenID)
}

// GetPasswordResetTokenByTokenCalls gets all the calls that were made to GetPasswordResetTokenByToken.
// Check the length with:
//
//	len(mockedPasswordResetTokenDataManager.GetPasswordResetTokenByTokenCalls())
func (mock *PasswordResetTokenDataManagerMock) GetPasswordResetTokenByTokenCalls() []struct {
	Ctx                  context.Context
	PasswordResetTokenID string
} {
	var calls []struct {
		Ctx                  context.Context
		PasswordResetTokenID string
	}
	mock.lockGetPasswordResetTokenByToken.RLock()
	calls = mock.calls.GetPasswordResetTokenByToken
	mock.lockGetPasswordResetTokenByToken.RUnlock()
	return calls
}

// RedeemPasswordResetToken calls RedeemPasswordResetTokenFunc.
func (mock *PasswordResetTokenDataManagerMock) RedeemPasswordResetToken(ctx context.Context, passwordResetTokenID string) error {
	if mock.RedeemPasswordResetTokenFunc == nil {
		panic("PasswordResetTokenDataManagerMock.RedeemPasswordResetTokenFunc: method is nil but PasswordResetTokenDataManager.RedeemPasswordResetToken was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		PasswordResetTokenID string
	}{
		Ctx:                  ctx,
		PasswordResetTokenID: passwordResetTokenID,
	}
	mock.lockRedeemPasswordResetToken.Lock()
	mock.calls.RedeemPasswordResetToken = append(mock.calls.RedeemPasswordResetToken, callInfo)
	mock.lockRedeemPasswordResetToken.Unlock()
	return mock.RedeemPasswordResetTokenFunc(ctx, passwordResetTokenID)
}

// RedeemPasswordResetTokenCalls gets all the calls that were made to RedeemPasswordResetToken.
// Check the length with:
//
//	len(mockedPasswordResetTokenDataManager.RedeemPasswordResetTokenCalls())
func (mock *PasswordResetTokenDataManagerMock) RedeemPasswordResetTokenCalls() []struct {
	Ctx                  context.Context
	PasswordResetTokenID string
} {
	var calls []struct {
		Ctx                  context.Context
		PasswordResetTokenID string
	}
	mock.lockRedeemPasswordResetToken.RLock()
	calls = mock.calls.RedeemPasswordResetToken
	mock.lockRedeemPasswordResetToken.RUnlock()
	return calls
}

// Ensure, that UserSessionDataManagerMock does implement auth.UserSessionDataManager.
// If this is not the case, regenerate this file with moq.
var _ auth.UserSessionDataManager = &UserSessionDataManagerMock{}

// UserSessionDataManagerMock is a mock implementation of auth.UserSessionDataManager.
//
//	func TestSomethingThatUsesUserSessionDataManager(t *testing.T) {
//
//		// make and configure a mocked auth.UserSessionDataManager
//		mockedUserSessionDataManager := &UserSessionDataManagerMock{
//			CreateUserSessionFunc: func(ctx context.Context, input *auth.UserSessionDatabaseCreationInput) (*auth.UserSession, error) {
//				panic("mock out the CreateUserSession method")
//			},
//			GetActiveSessionsForUserFunc: func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[auth.UserSession], error) {
//				panic("mock out the GetActiveSessionsForUser method")
//			},
//			GetUserSessionByRefreshTokenIDFunc: func(ctx context.Context, refreshTokenID string) (*auth.UserSession, error) {
//				panic("mock out the GetUserSessionByRefreshTokenID method")
//			},
//			GetUserSessionBySessionTokenIDFunc: func(ctx context.Context, sessionTokenID string) (*auth.UserSession, error) {
//				panic("mock out the GetUserSessionBySessionTokenID method")
//			},
//			RevokeAllSessionsForUserFunc: func(ctx context.Context, userID string) error {
//				panic("mock out the RevokeAllSessionsForUser method")
//			},
//			RevokeAllSessionsForUserExceptFunc: func(ctx context.Context, userID string, sessionID string) error {
//				panic("mock out the RevokeAllSessionsForUserExcept method")
//			},
//			RevokeUserSessionFunc: func(ctx context.Context, sessionID string, userID string) error {
//				panic("mock out the RevokeUserSession method")
//			},
//			TouchSessionLastActiveFunc: func(ctx context.Context, sessionTokenID string) error {
//				panic("mock out the TouchSessionLastActive method")
//			},
//			UpdateSessionTokenIDsFunc: func(ctx context.Context, sessionID string, newSessionTokenID string, newRefreshTokenID string, newExpiresAt time.Time) error {
//				panic("mock out the UpdateSessionTokenIDs method")
//			},
//		}
//
//		// use mockedUserSessionDataManager in code that requires auth.UserSessionDataManager
//		// and then make assertions.
//
//	}
type UserSessionDataManagerMock struct {
	// CreateUserSessionFunc mocks the CreateUserSession method.
	CreateUserSessionFunc func(ctx context.Context, input *auth.UserSessionDatabaseCreationInput) (*auth.UserSession, error)

	// GetActiveSessionsForUserFunc mocks the GetActiveSessionsForUser method.
	GetActiveSessionsForUserFunc func(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[auth.UserSession], error)

	// GetUserSessionByRefreshTokenIDFunc mocks the GetUserSessionByRefreshTokenID method.
	GetUserSessionByRefreshTokenIDFunc func(ctx context.Context, refreshTokenID string) (*auth.UserSession, error)

	// GetUserSessionBySessionTokenIDFunc mocks the GetUserSessionBySessionTokenID method.
	GetUserSessionBySessionTokenIDFunc func(ctx context.Context, sessionTokenID string) (*auth.UserSession, error)

	// RevokeAllSessionsForUserFunc mocks the RevokeAllSessionsForUser method.
	RevokeAllSessionsForUserFunc func(ctx context.Context, userID string) error

	// RevokeAllSessionsForUserExceptFunc mocks the RevokeAllSessionsForUserExcept method.
	RevokeAllSessionsForUserExceptFunc func(ctx context.Context, userID string, sessionID string) error

	// RevokeUserSessionFunc mocks the RevokeUserSession method.
	RevokeUserSessionFunc func(ctx context.Context, sessionID string, userID string) error

	// TouchSessionLastActiveFunc mocks the TouchSessionLastActive method.
	TouchSessionLastActiveFunc func(ctx context.Context, sessionTokenID string) error

	// UpdateSessionTokenIDsFunc mocks the UpdateSessionTokenIDs method.
	UpdateSessionTokenIDsFunc func(ctx context.Context, sessionID string, newSessionTokenID string, newRefreshTokenID string, newExpiresAt time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateUserSession holds details about calls to the CreateUserSession method.
		CreateUserSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *auth.UserSessionDatabaseCreationInput
		}
		// GetActiveSessionsForUser holds details about calls to the GetActiveSessionsForUser method.
		GetActiveSessionsForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// GetUserSessionByRefreshTokenID holds details about calls to the GetUserSessionByRefreshTokenID method.
		GetUserSessionByRefreshTokenID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RefreshTokenID is the refreshTokenID argument value.
			RefreshTokenID string
		}
		// GetUserSessionBySessionTokenID holds details about calls to the GetUserSessionBySessionTokenID method.
		GetUserSessionBySessionTokenID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionTokenID is the sessionTokenID argument value.
			SessionTokenID string
		}
		// RevokeAllSessionsForUser holds details about calls to the RevokeAllSessionsForUser method.
		RevokeAllSessionsForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// RevokeAllSessionsForUserExcept holds details about calls to the RevokeAllSessionsForUserExcept method.
		RevokeAllSessionsForUserExcept []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// SessionID is the sessionID argument value.
			SessionID string
		}
		// RevokeUserSession holds details about calls to the RevokeUserSession method.
		RevokeUserSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID string
			// UserID is the userID argument value.
			UserID string
		}
		// TouchSessionLastActive holds details about calls to the TouchSessionLastActive method.
		TouchSessionLastActive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionTokenID is the sessionTokenID argument value.
			SessionTokenID string
		}
		// UpdateSessionTokenIDs holds details about calls to the UpdateSessionTokenIDs method.
		UpdateSessionTokenIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID string
			// NewSessionTokenID is the newSessionTokenID argument value.
			NewSessionTokenID string
			// NewRefreshTokenID is the newRefreshTokenID argument value.
			NewRefreshTokenID string
			// NewExpiresAt is the newExpiresAt argument value.
			NewExpiresAt time.Time
		}
	}
	lockCreateUserSession              sync.RWMutex
	lockGetActiveSessionsForUser       sync.RWMutex
	lockGetUserSessionByRefreshTokenID sync.RWMutex
	lockGetUserSessionBySessionTokenID sync.RWMutex
	lockRevokeAllSessionsForUser       sync.RWMutex
	lockRevokeAllSessionsForUserExcept sync.RWMutex
	lockRevokeUserSession              sync.RWMutex
	lockTouchSessionLastActive         sync.RWMutex
	lockUpdateSessionTokenIDs          sync.RWMutex
}

// CreateUserSession calls CreateUserSessionFunc.
func (mock *UserSessionDataManagerMock) CreateUserSession(ctx context.Context, input *auth.UserSessionDatabaseCreationInput) (*auth.UserSession, error) {
	if mock.CreateUserSessionFunc == nil {
		panic("UserSessionDataManagerMock.CreateUserSessionFunc: method is nil but UserSessionDataManager.CreateUserSession was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *auth.UserSessionDatabaseCreationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateUserSession.Lock()
	mock.calls.CreateUserSession = append(mock.calls.CreateUserSession, callInfo)
	mock.lockCreateUserSession.Unlock()
	return mock.CreateUserSessionFunc(ctx, input)
}

// CreateUserSessionCalls gets all the calls that were made to CreateUserSession.
// Check the length with:
//
//	len(mockedUserSessionDataManager.CreateUserSessionCalls())
func (mock *UserSessionDataManagerMock) CreateUserSessionCalls() []struct {
	Ctx   context.Context
	Input *auth.UserSessionDatabaseCreationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *auth.UserSessionDatabaseCreationInput
	}
	mock.lockCreateUserSession.RLock()
	calls = mock.calls.CreateUserSession
	mock.lockCreateUserSession.RUnlock()
	return calls
}

// GetActiveSessionsForUser calls GetActiveSessionsForUserFunc.
func (mock *UserSessionDataManagerMock) GetActiveSessionsForUser(ctx context.Context, userID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[auth.UserSession], error) {
	if mock.GetActiveSessionsForUserFunc == nil {
		panic("UserSessionDataManagerMock.GetActiveSessionsForUserFunc: method is nil but UserSessionDataManager.GetActiveSessionsForUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		UserID: userID,
		Filter: filter,
	}
	mock.lockGetActiveSessionsForUser.Lock()
	mock.calls.GetActiveSessionsForUser = append(mock.calls.GetActiveSessionsForUser, callInfo)
	mock.lockGetActiveSessionsForUser.Unlock()
	return mock.GetActiveSessionsForUserFunc(ctx, userID, filter)
}

// GetActiveSessionsForUserCalls gets all the calls that were made to GetActiveSessionsForUser.
// Check the length with:
//
//	len(mockedUserSessionDataManager.GetActiveSessionsForUserCalls())
func (mock *UserSessionDataManagerMock) GetActiveSessionsForUserCalls() []struct {
	Ctx    context.Context
	UserID string
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Filter *filtering.QueryFilter
	}
	mock.lockGetActiveSessionsForUser.RLock()
	calls = mock.calls.GetActiveSessionsForUser
	mock.lockGetActiveSessionsForUser.RUnlock()
	return calls
}

// GetUserSessionByRefreshTokenID calls GetUserSessionByRefreshTokenIDFunc.
func (mock *UserSessionDataManagerMock) GetUserSessionByRefreshTokenID(ctx context.Context, refreshTokenID string) (*auth.UserSession, error) {
	if mock.GetUserSessionByRefreshTokenIDFunc == nil {
		panic("UserSessionDataManagerMock.GetUserSessionByRefreshTokenIDFunc: method is nil but UserSessionDataManager.GetUserSessionByRefreshTokenID was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		RefreshTokenID string
	}{
		Ctx:            ctx,
		RefreshTokenID: refreshTokenID,
	}
	mock.lockGetUserSessionByRefreshTokenID.Lock()
	mock.calls.GetUserSessionByRefreshTokenID = append(mock.calls.GetUserSessionByRefreshTokenID, callInfo)
	mock.lockGetUserSessionByRefreshTokenID.Unlock()
	return mock.GetUserSessionByRefreshTokenIDFunc(ctx, refreshTokenID)
}

// GetUserSessionByRefreshTokenIDCalls gets all the calls that were made to GetUserSessionByRefreshTokenID.
// Check the length with:
//
//	len(mockedUserSessionDataManager.GetUserSessionByRefreshTokenIDCalls())
func (mock *UserSessionDataManagerMock) GetUserSessionByRefreshTokenIDCalls() []struct {
	Ctx            context.Context
	RefreshTokenID string
} {
	var calls []struct {
		Ctx            context.Context
		RefreshTokenID string
	}
	mock.lockGetUserSessionByRefreshTokenID.RLock()
	calls = mock.calls.GetUserSessionByRefreshTokenID
	mock.lockGetUserSessionByRefreshTokenID.RUnlock()
	return calls
}

// GetUserSessionBySessionTokenID calls GetUserSessionBySessionTokenIDFunc.
func (mock *UserSessionDataManagerMock) GetUserSessionBySessionTokenID(ctx context.Context, sessionTokenID string) (*auth.UserSession, error) {
	if mock.GetUserSessionBySessionTokenIDFunc == nil {
		panic("UserSessionDataManagerMock.GetUserSessionBySessionTokenIDFunc: method is nil but UserSessionDataManager.GetUserSessionBySessionTokenID was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		SessionTokenID string
	}{
		Ctx:            ctx,
		SessionTokenID: sessionTokenID,
	}
	mock.lockGetUserSessionBySessionTokenID.Lock()
	mock.calls.GetUserSessionBySessionTokenID = append(mock.calls.GetUserSessionBySessionTokenID, callInfo)
	mock.lockGetUserSessionBySessionTokenID.Unlock()
	return mock.GetUserSessionBySessionTokenIDFunc(ctx, sessionTokenID)
}

// GetUserSessionBySessionTokenIDCalls gets all the calls that were made to GetUserSessionBySessionTokenID.
// Check the length with:
//
//	len(mockedUserSessionDataManager.GetUserSessionBySessionTokenIDCalls())
func (mock *UserSessionDataManagerMock) GetUserSessionBySessionTokenIDCalls() []struct {
	Ctx            context.Context
	SessionTokenID string
} {
	var calls []struct {
		Ctx            context.Context
		SessionTokenID string
	}
	mock.lockGetUserSessionBySessionTokenID.RLock()
	calls = mock.calls.GetUserSessionBySessionTokenID
	mock.lockGetUserSessionBySessionTokenID.RUnlock()
	return calls
}

// RevokeAllSessionsForUser calls RevokeAllSessionsForUserFunc.
func (mock *UserSessionDataManagerMock) RevokeAllSessionsForUser(ctx context.Context, userID string) error {
	if mock.RevokeAllSessionsForUserFunc == nil {
		panic("UserSessionDataManagerMock.RevokeAllSessionsForUserFunc: method is nil but UserSessionDataManager.RevokeAllSessionsForUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockRevokeAllSessionsForUser.Lock()
	mock.calls.RevokeAllSessionsForUser = append(mock.calls.RevokeAllSessionsForUser, callInfo)
	mock.lockRevokeAllSessionsForUser.Unlock()
	return mock.RevokeAllSessionsForUserFunc(ctx, userID)
}

// RevokeAllSessionsForUserCalls gets all the calls that were made to RevokeAllSessionsForUser.
// Check the length with:
//
//	len(mockedUserSessionDataManager.RevokeAllSessionsForUserCalls())
func (mock *UserSessionDataManagerMock) RevokeAllSessionsForUserCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockRevokeAllSessionsForUser.RLock()
	calls = mock.calls.RevokeAllSessionsForUser
	mock.lockRevokeAllSessionsForUser.RUnlock()
	return calls
}

// RevokeAllSessionsForUserExcept calls RevokeAllSessionsForUserExceptFunc.
func (mock *UserSessionDataManagerMock) RevokeAllSessionsForUserExcept(ctx context.Context, userID string, sessionID string) error {
	if mock.RevokeAllSessionsForUserExceptFunc == nil {
		panic("UserSessionDataManagerMock.RevokeAllSessionsForUserExceptFunc: method is nil but UserSessionDataManager.RevokeAllSessionsForUserExcept was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    string
		SessionID string
	}{
		Ctx:       ctx,
		UserID:    userID,
		SessionID: sessionID,
	}
	mock.lockRevokeAllSessionsForUserExcept.Lock()
	mock.calls.RevokeAllSessionsForUserExcept = append(mock.calls.RevokeAllSessionsForUserExcept, callInfo)
	mock.lockRevokeAllSessionsForUserExcept.Unlock()
	return mock.RevokeAllSessionsForUserExceptFunc(ctx, userID, sessionID)
}

// RevokeAllSessionsForUserExceptCalls gets all the calls that were made to RevokeAllSessionsForUserExcept.
// Check the length with:
//
//	len(mockedUserSessionDataManager.RevokeAllSessionsForUserExceptCalls())
func (mock *UserSessionDataManagerMock) RevokeAllSessionsForUserExceptCalls() []struct {
	Ctx       context.Context
	UserID    string
	SessionID string
} {
	var calls []struct {
		Ctx       context.Context
		UserID    string
		SessionID string
	}
	mock.lockRevokeAllSessionsForUserExcept.RLock()
	calls = mock.calls.RevokeAllSessionsForUserExcept
	mock.lockRevokeAllSessionsForUserExcept.RUnlock()
	return calls
}

// RevokeUserSession calls RevokeUserSessionFunc.
func (mock *UserSessionDataManagerMock) RevokeUserSession(ctx context.Context, sessionID string, userID string) error {
	if mock.RevokeUserSessionFunc == nil {
		panic("UserSessionDataManagerMock.RevokeUserSessionFunc: method is nil but UserSessionDataManager.RevokeUserSession was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		SessionID string
		UserID    string
	}{
		Ctx:       ctx,
		SessionID: sessionID,
		UserID:    userID,
	}
	mock.lockRevokeUserSession.Lock()
	mock.calls.RevokeUserSession = append(mock.calls.RevokeUserSession, callInfo)
	mock.lockRevokeUserSession.Unlock()
	return mock.RevokeUserSessionFunc(ctx, sessionID, userID)
}

// RevokeUserSessionCalls gets all the calls that were made to RevokeUserSession.
// Check the length with:
//
//	len(mockedUserSessionDataManager.RevokeUserSessionCalls())
func (mock *UserSessionDataManagerMock) RevokeUserSessionCalls() []struct {
	Ctx       context.Context
	SessionID string
	UserID    string
} {
	var calls []struct {
		Ctx       context.Context
		SessionID string
		UserID    string
	}
	mock.lockRevokeUserSession.RLock()
	calls = mock.calls.RevokeUserSession
	mock.lockRevokeUserSession.RUnlock()
	return calls
}

// TouchSessionLastActive calls TouchSessionLastActiveFunc.
func (mock *UserSessionDataManagerMock) TouchSessionLastActive(ctx context.Context, sessionTokenID string) error {
	if mock.TouchSessionLastActiveFunc == nil {
		panic("UserSessionDataManagerMock.TouchSessionLastActiveFunc: method is nil but UserSessionDataManager.TouchSessionLastActive was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		SessionTokenID string
	}{
		Ctx:            ctx,
		SessionTokenID: sessionTokenID,
	}
	mock.lockTouchSessionLastActive.Lock()
	mock.calls.TouchSessionLastActive = append(mock.calls.TouchSessionLastActive, callInfo)
	mock.lockTouchSessionLastActive.Unlock()
	return mock.TouchSessionLastActiveFunc(ctx, sessionTokenID)
}

// TouchSessionLastActiveCalls gets all the calls that were made to TouchSessionLastActive.
// Check the length with:
//
//	len(mockedUserSessionDataManager.TouchSessionLastActiveCalls())
func (mock *UserSessionDataManagerMock) TouchSessionLastActiveCalls() []struct {
	Ctx            context.Context
	SessionTokenID string
} {
	var calls []struct {
		Ctx            context.Context
		SessionTokenID string
	}
	mock.lockTouchSessionLastActive.RLock()
	calls = mock.calls.TouchSessionLastActive
	mock.lockTouchSessionLastActive.RUnlock()
	return calls
}

// UpdateSessionTokenIDs calls UpdateSessionTokenIDsFunc.
func (mock *UserSessionDataManagerMock) UpdateSessionTokenIDs(ctx context.Context, sessionID string, newSessionTokenID string, newRefreshTokenID string, newExpiresAt time.Time) error {
	if mock.UpdateSessionTokenIDsFunc == nil {
		panic("UserSessionDataManagerMock.UpdateSessionTokenIDsFunc: method is nil but UserSessionDataManager.UpdateSessionTokenIDs was just called")
	}
	callInfo := struct {
		Ctx               context.Context
		SessionID         string
		NewSessionTokenID string
		NewRefreshTokenID string
		NewExpiresAt      time.Time
	}{
		Ctx:               ctx,
		SessionID:         sessionID,
		NewSessionTokenID: newSessionTokenID,
		NewRefreshTokenID: newRefreshTokenID,
		NewExpiresAt:      newExpiresAt,
	}
	mock.lockUpdateSessionTokenIDs.Lock()
	mock.calls.UpdateSessionTokenIDs = append(mock.calls.UpdateSessionTokenIDs, callInfo)
	mock.lockUpdateSessionTokenIDs.Unlock()
	return mock.UpdateSessionTokenIDsFunc(ctx, sessionID, newSessionTokenID, newRefreshTokenID, newExpiresAt)
}

// UpdateSessionTokenIDsCalls gets all the calls that were made to UpdateSessionTokenIDs.
// Check the length with:
//
//	len(mockedUserSessionDataManager.UpdateSessionTokenIDsCalls())
func (mock *UserSessionDataManagerMock) UpdateSessionTokenIDsCalls() []struct {
	Ctx               context.Context
	SessionID         string
	NewSessionTokenID string
	NewRefreshTokenID string
	NewExpiresAt      time.Time
} {
	var calls []struct {
		Ctx               context.Context
		SessionID         string
		NewSessionTokenID string
		NewRefreshTokenID string
		NewExpiresAt      time.Time
	}
	mock.lockUpdateSessionTokenIDs.RLock()
	calls = mock.calls.UpdateSessionTokenIDs
	mock.lockUpdateSessionTokenIDs.RUnlock()
	return calls
}
