// Command valid_env_vars regenerates the constants naming every environment variable that can
// override a configuration field, plus the .env.example that lists them for an operator.
//
// The walk itself lives in platform's config/envvars. What is left here is the three things that
// are ours: which constraint names the loadable config structs, which module's source has to be
// read alongside our own, and the .env example, which platform does not emit.
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/primandproper/dinnerdonebetter/backend/internal/config"

	"github.com/primandproper/platform-go/v11/config/envvars"
)

const (
	// unionKey names the generic constraint the Load* functions require of a loadable config
	// struct. Deriving the struct list from it is what makes the output complete by
	// construction: a new config struct cannot become loadable without appearing here.
	unionKey = "internal/config.configurations"

	// platformModulePrefix bounds which dependency modules get parsed alongside this one. Most
	// generated constants come from platform config structs embedded in ours, and parsing the
	// rest of the module graph would cost time without contributing a key.
	platformModulePrefix = "github.com/primandproper/platform-go"

	outputPath  = "internal/config/envvars/env_vars.go"
	dotEnvPath  = ".env.example"
	rootTypeEnv = "APIServiceConfig"
)

func main() {
	ctx := context.Background()

	dir, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	opts := envvars.Options{
		Dir:          dir,
		Prefix:       config.EnvVarPrefix,
		UnionKey:     unionKey,
		OutputPath:   outputPath,
		Package:      "envvars",
		Dependencies: []string{platformModulePrefix},
	}

	if err = envvars.Generate(ctx, opts); err != nil {
		log.Fatalf("generating env var constants: %v", err)
	}

	// Collected a second time rather than threaded out of Generate: Collect is the exported
	// half precisely so a caller can build something else out of the same set, and the walk is
	// cached behind it.
	variables, err := envvars.Collect(ctx, opts)
	if err != nil {
		log.Fatalf("collecting env vars for %s: %v", dotEnvPath, err)
	}

	if err = writeDotEnvExample(dir, variables); err != nil {
		log.Fatalf("writing %s: %v", dotEnvPath, err)
	}
}

// writeDotEnvExample lists every variable that overrides an APIServiceConfig field, with the
// envDefault it falls back to as the value.
//
// Only that config's variables are listed. The other services' configs are assembled out of the
// same platform structs, so their variables are the same names wherever the fields overlap, and
// listing all of them would be a longer file saying the same thing.
func writeDotEnvExample(dir string, variables []envvars.Variable) error {
	lines := []string{
		"# .env.example — generated by cmd/tools/codegen/valid_env_vars. DO NOT EDIT.",
		"#",
		"# Copy this file to .env and fill in the values relevant to your environment.",
		"# Set DOTENV_FILEPATH to the path of your .env file so the service loads it.",
		"# Values in .env override the JSON config file but are overridden by actual",
		"# process environment variables.",
		"#",
		"# Only APIServiceConfig variables are listed here; other service configs",
		"# share the same variable names where their fields overlap.",
		"",
	}

	// Collect returns variables sorted by name, so the file is stable without sorting again.
	for i := range variables {
		if !overridesAPIServiceConfig(&variables[i]) {
			continue
		}

		lines = append(lines, fmt.Sprintf("%s=%s", variables[i].Name, variables[i].Default))
	}

	lines = append(lines, "")

	return os.WriteFile(filepath.Join(dir, dotEnvPath), []byte(strings.Join(lines, "\n")), 0o0600)
}

// overridesAPIServiceConfig reports whether any of a variable's field paths is rooted at the API
// service's config. A variable reachable from several configuration structs carries one path per
// struct, so this is a search rather than a look at the first one.
func overridesAPIServiceConfig(variable *envvars.Variable) bool {
	for _, fieldPath := range variable.FieldPaths {
		if root, _, _ := strings.Cut(fieldPath, "."); root == rootTypeEnv {
			return true
		}
	}

	return false
}
