// Code generated by cmd/tools/codegen/converters. DO NOT EDIT.

package converters

import (
	"github.com/primandproper/dinnerdonebetter/backend/internal/domain/issuereports"

	"github.com/primandproper/platform-go/v11/identifiers"
)

// ConvertIssueReportToIssueReportUpdateRequestInput builds an IssueReportUpdateRequestInput from an IssueReport.
func ConvertIssueReportToIssueReportUpdateRequestInput(x *issuereports.IssueReport) *issuereports.IssueReportUpdateRequestInput {
	return &issuereports.IssueReportUpdateRequestInput{
		IssueType:        &x.IssueType,
		Details:          &x.Details,
		RelevantTable:    &x.RelevantTable,
		RelevantRecordID: &x.RelevantRecordID,
	}
}

// ConvertIssueReportCreationRequestInputToIssueReportDatabaseCreationInput builds an IssueReportDatabaseCreationInput from an IssueReportCreationRequestInput.
func ConvertIssueReportCreationRequestInputToIssueReportDatabaseCreationInput(x *issuereports.IssueReportCreationRequestInput, userID string, accountID string) *issuereports.IssueReportDatabaseCreationInput {
	return &issuereports.IssueReportDatabaseCreationInput{
		ID:               identifiers.New(),
		IssueType:        x.IssueType,
		Details:          x.Details,
		RelevantTable:    x.RelevantTable,
		RelevantRecordID: x.RelevantRecordID,
		// Comes from the session rather than the request body, so the manager stamps it
		// after this.
		CreatedByUser: userID,
		// Comes from the session rather than the request body, so the manager stamps it
		// after this.
		BelongsToAccount: accountID,
	}
}

// ConvertIssueReportToIssueReportCreationRequestInput builds an IssueReportCreationRequestInput from an IssueReport.
func ConvertIssueReportToIssueReportCreationRequestInput(x *issuereports.IssueReport) *issuereports.IssueReportCreationRequestInput {
	return &issuereports.IssueReportCreationRequestInput{
		IssueType:        x.IssueType,
		Details:          x.Details,
		RelevantTable:    x.RelevantTable,
		RelevantRecordID: x.RelevantRecordID,
	}
}

// ConvertIssueReportToIssueReportDatabaseCreationInput builds an IssueReportDatabaseCreationInput from an IssueReport.
func ConvertIssueReportToIssueReportDatabaseCreationInput(x *issuereports.IssueReport) *issuereports.IssueReportDatabaseCreationInput {
	return &issuereports.IssueReportDatabaseCreationInput{
		ID:               x.ID,
		IssueType:        x.IssueType,
		Details:          x.Details,
		RelevantTable:    x.RelevantTable,
		RelevantRecordID: x.RelevantRecordID,
		CreatedByUser:    x.CreatedByUser,
		BelongsToAccount: x.BelongsToAccount,
	}
}
