---
on:
  pull_request:
    paths:
      - ios/**/*.swift
      - ios/.swiftlint.yml
      - ios/Makefile
      - ios/scripts/lint.sh
      - ios/scripts/ensure_swiftlint.sh
      - .github/workflows/ios_lint.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: ios lint
jobs:
  swift:
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run SwiftLint
        working-directory: ios
        run: make lint
